### ISSUE TITLE
Do a mock up of the distribution of the elemets in LearnPack's UI

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1029]
Do a mock up of the distribution that the UI will have, think about functionalities that we should include

**Comment by karlacuevasc** [comment]
Hrs: <hrs>3 hrs</hrs>
Design: [Figma Link](https://www.figma.com/file/bGEs6sD2ioQjqamvU8cfRs/Learnpack-New-Design?node-id=0%3A1)

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>3</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>3</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>3</hrs>
