### ISSUE TITLE
Excercise Bug: 11-Font-Awesome-Icons

### ISSUE THREAD

**Issue by Alejandrinaflores** [learnpack/learnpack#1031]
Describe the bug:

**1. Exercise Name:** 11-Font-Awesome-Icons

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

When I complete the code following the instructions and compile didn´t show me the right result, it supposed to be ok
![COMPILE ERROR](https://user-images.githubusercontent.com/108097278/176306881-44fb290b-0ab7-4346-9aba-e3efabf0290d.jpg)

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<link rel="stylesheet" type="text/css" href="./styles.css" />
		<script src="https://kit.fontawesome.com/072e5df971.js" crossorigin="anonymous"></script>
		<title>11 Font Awesome</title>
	</head>
	<body>
		<ul>
			<li><i class="fa fa-camera-retro"></i> Hello</li>
			<li><i class="fa fa-airbnb"></i>World</li>
			<li><i class="fa fa-flag"></i>Travel</li>
		</ul>
	</body>
</html>

**Comment by UmiKami** [comment]
Nothing needs to be changed, it works as it should even with the elements provided by the user. Possible user error.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.03</hrs>
