### ISSUE TITLE
Exerxise bug: 67 - Event and less than 9

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#1033]
mastering js

![334BF9CC-0770-49AD-AE65-421E5DBA250C](https://user-images.githubusercontent.com/426452/176570781-7cdbb4ca-a98e-426e-9b3a-d57a57573ae5.jpeg)

![9C5B4F13-8E04-4DBE-B222-F47D4852C21B](https://user-images.githubusercontent.com/426452/176570795-c8f88e89-54cd-436c-a36c-afa6030982d5.jpeg)

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/131
Hrs: <hrs>0.20</hrs>

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/131
Hrs: <hrs>0.20</hrs>
