### ISSUE TITLE
Excercise Bug: 11-Your_first_if

### ISSUE THREAD

**Issue by paoagui92** [learnpack/learnpack#1036]
Describe the bug:

**1. Exercise Name:** 11-Your_first_if

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

Las frases que se indican en los test no coinciden con las descritas en las instrucciones del ejercicio, ejm:
![image](https://user-images.githubusercontent.com/58713748/177441686-7dc50310-76c9-43a2-80c8-edcfca3d922c.png)
![image](https://user-images.githubusercontent.com/58713748/177441790-bb14f406-f138-45d9-af55-aa1eeba66c47.png)

**Comment by tommygonzaleza** [comment]
Hello! Thank you for reporting this issue, anyway it has been reported already, here it is: https://github.com/learnpack/learnpack/issues/1034
