### ISSUE TITLE
Excercise Bug: 11-Your_first_if

### ISSUE THREAD

**Issue by SennCode** [learnpack/learnpack#1044]
Describe the bug: Las frases del enunciado tienen diferencias y devuelve un error : 

"We still have a bit of driving left to go?". y "I'm parking, I see you right now".

**1. Exercise Name:** 11-Your_first_if

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by tommygonzaleza** [comment]
Hello! Thank you for reporting the issue, anyway, it has been reported already, here it is: https://github.com/learnpack/learnpack/issues/1034
