### ISSUE TITLE
Excercise Bug: 02-pipenv-installation

### ISSUE THREAD

**Issue by javier-bustillo** [learnpack/learnpack#1047]
Describe the bug:

**1. Exercise Name:** 02-pipenv-installation

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

 if you split editor on Gitpod, there is no test button enabled to continue to the next step.

**Comment by tommygonzaleza** [comment]
I couldn´t replicate what the issue is, can you please provide more information, maybe a screenshot could be good
