### ISSUE TITLE
Excercise Bug: 08-adding-styles

### ISSUE THREAD

**Issue by JaneshkaF** [learnpack/learnpack#1054]
Describe the bug:

**1. Exercise Name:** 08-adding-styles

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

I copy and pasted the code from the instructions and it keeps saying "error" with the code. But when I build the page, it builds exactly how its supposed to be. I am pretty sure that I typed the code in properly so I feel it may be an issue with the program. However if I am wrong, please let me know ;)

**Comment by UmiKami** [comment]
Copy and pasted the code into the styles.css and it works fine. No issues found.

**Comment by UmiKami** [comment]
Issue found in the readme, instructions tells users to create a style.css file instead of a style**s**.css

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/exercise-postcard/pull/58
Hrs: <hrs>0.07</hrs>
