### ISSUE TITLE
Excercise Bug: 05.1-sum_odd_items

### ISSUE THREAD

**Issue by samuelpalaciosdev** [learnpack/learnpack#1061]
Describe the bug: Change sumOdds name of function to sum_odds

**1. Exercise Name:** 05.1-sum_odd_items

**2. Repository URL:** https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/92
Hrs: <hrs> 0.17 </hrs>

**Comment by UmiKami** [comment]
Added function to check if function sumOdds exist.
The functions and test both clearly state the function should be call sumOdds, no need to change the name to sum_odds.

**Comment by tommygonzaleza** [comment]
Thank you, Ernesto, anyway I think the @samuelpalaciosdev is right, the name of the function should sum_odds instead of sumOdds because on python we should use snake_case

**Comment by tommygonzaleza** [comment]
I just fixed myself

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.17</hrs>
