### ISSUE TITLE
Excercise Bug: 05-Defining-vs-Calling-a-function

### ISSUE THREAD

**Issue by dmilanop** [learnpack/learnpack#1062]
Describe the bug:

**1. Exercise Name:** 05-Defining-vs-Calling-a-function

**2. Repository URL:** https://github.com/4GeeksAcademy/python-functions-programming-exercises

**Comment by dsilva06** [comment]
I can't quite see the error here, might be defining the function in JS and not python

**Comment by dsilva06** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/36
hrs: <hrs>0.30</hrs>
