### ISSUE TITLE
Excercise Bug: 08.1-Mixed-array

### ISSUE THREAD

**Issue by Navarroseb** [learnpack/learnpack#1063]
Describe the bug:

I return the expected result but i have two tasks incomplete: 
- (fail) 0. Use the console.log function once to print the newArray on the console
- Loop the array and console.log all of its item types.

This is my code: (
let newArr = [];
for( i = 0; i < mix.length; i++){
   let item = mix[i];
   newArr.push(typeof item)
}
console.log(newArr); 

)

**1. Exercise Name:** 08.1-Mixed-array

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by dsilva06** [comment]
everything is alright, maybe forgot to create a new array. Must create a new array to store what is asked on the test

**Comment by dsilva06** [comment]
PR:https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/80
HRS: <hrs>0.5</hrs>

**Comment by dsilva06** [comment]
modificar READme(2)// funcion que reciba array y retorne array nuevo con los tipos de datos(test.js)//
modificar solution.hide.js

**Comment by dsilva06** [comment]
hrs: <hrs>0.8</hrs>

**Comment by tommygonzaleza** [comment]
- [ ] You should check the console's output
- [ ] You shouldn't ask to create a function in the READMEs as you are not doing it on the solution.hide.js either.

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/87
hrs: <hrs>1</hrs>
