### ISSUE TITLE
Excercise Bug: 07.2-finish-post-todo

### ISSUE THREAD

**Issue by nizarmonza** [learnpack/learnpack#1065]
Describe the bug:
- i added my code correctly however the test keps failing. I think there might be a bug on the test because I did everything the instructions told me to do.

**1. Exercise Name:** 07.2-finish-post-todo

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

<img width="1440" alt="Screen Shot 2022-07-25 at 11 11 41" src="https://user-images.githubusercontent.com/102087932/180835744-99b92c06-6157-4ab6-b062-7ea478d0356b.png">
<img width="1440" alt="Screen Shot 2022-07-25 at 10 47 24" src="https://user-images.githubusercontent.com/102087932/180835233-6ad0e907-6dde-43dc-908a-5c580d2cdf7a.png">
<img width="1440" alt="Screen Shot 2022-07-25 at 10 47 33" src="https://user-images.githubusercontent.com/102087932/180835243-ce132155-87cb-4d0b-8763-0e2d964aac9a.png">

**Comment by UmiKami** [comment]
Tests post request was posting json format with the `data` parameter. `data` parameter forces user to use `the get_json(Force = True)` method for it to work and not return a 400 error.

`json` parameter turns dict into json string automatically, no need for `json.dumps()`
The parameter works with the code in the instructions and does not return error 400 when we use `reponse.json`

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/python-flask-api-tutorial/pull/48
Hrs: <hrs>0.33</hrs>
