### ISSUE TITLE
Review the Tests CSS (1 / 2)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1071]
Improve the tests of the following exercises. Remember that tests in HTML/CSS are a bit different.

Repository: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Exercises: From `01-Hello-World` to `04.2-Apply-several-classes`

Here you have some HTML/CSS Unit Tests Examples: https://docs.learnpack.co/programming-languages/html-css

**This should be done by August 01 of 2022**

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/html-tutorial-exercises-course/

**Comment by UmiKami** [comment]
01.2 Your First Style
Instead of checking for background blue, it is now checking for anchor color "yellow"

**Comment by UmiKami** [comment]
<hrs>0.07</hrs>

**Comment by UmiKami** [comment]
01-Hello-world
Created tests to check if the user is not modifying the code they were given.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.24</hrs>

**Comment by UmiKami** [comment]
01.1 The-Stye-Tag
Added tests to check if p tag exists, if p tag has style color "blue", and if the user is NOT using inline styling

**Comment by UmiKami** [comment]
Hrs: <hrs>0.34</hrs>

**Comment by UmiKami** [comment]
01.2 Your First Style
Further iterated upon the tests, formatted them using ES6 standards, and used the `test` method instead of the `it` method.
Additionally, added another test to check that the user is not using inline style.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.41</hrs>

**Comment by UmiKami** [comment]
01.2 Your Seconds Style
Further iterated upon the tests, formatted them using ES6 standards, and used the `test` method instead of the `it` method.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.44</hrs>

**Comment by UmiKami** [comment]
Added solution files for 1-1.3

**Comment by UmiKami** [comment]
Hrs: <hrs>0.54</hrs>

**Comment by UmiKami** [comment]
02-Separate Sheet

Upgraded tests to modern current standard and added test to check for background color of blue

**Comment by UmiKami** [comment]
Hrs: <hrs>0.71</hrs>

**Comment by UmiKami** [comment]
02.1-Background
Upgraded tests to modern standard JS and Jest, and improved readability of test code.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.83</hrs>

**Comment by UmiKami** [comment]
03-Inline Styles
Just upgraded it to a more modern format using ES6 and test functions.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.86</hrs>

**Comment by UmiKami** [comment]
04-Class selector
Added test and solution file

**Comment by UmiKami** [comment]
Hrs: <hrs>0.96</hrs>

**Comment by UmiKami** [comment]
04.1-Combined  Rules
Just updated tests to ES6 format, cleaned up some code, and fixed minor issue with head content test
Added solution file

**Comment by UmiKami** [comment]
Hrs: <hrs>1.11</hrs>

**Comment by UmiKami** [comment]
04.1-04.2 - Fixed titles on html
04.2- Added test file and added solution file

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/60
Hrs: <hrs>1.24</hrs>
