### ISSUE TITLE
Review the Tests CSS (2 / 2)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1072]
Improve the tests of the following exercises. Remember that tests in HTML/CSS are a bit different.

Repository: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Exercises: From `04.3-id-Selector` to `13-Anchor-Like-Button`

Here you have some HTML/CSS Unit Tests Examples: https://docs.learnpack.co/programming-languages/html-css

**This should be done by August 01 of 2022**

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/html-tutorial-exercises-course/

**Comment by UmiKami** [comment]
04.3 The ID CSS Selector
Added solution file and test file
Checks if span element exist
Checks if such element has the requested id name
Checks no inlline styles are being applied

**Comment by UmiKami** [comment]
Hrs: <hrs>0.12</hrs>

**Comment by UmiKami** [comment]
05 Specificity
Added solution
Improved tests with ES6 and Test method

**Comment by UmiKami** [comment]
Hrs: <hrs>0.24</hrs>

**Comment by UmiKami** [comment]
06 Practicing Rules
Improved tests
Fixed minor issues with tests
Added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.47</hrs>

**Comment by UmiKami** [comment]
07 Very Specific Rules
Fixed minor errors, added solution, and improved test format

**Comment by UmiKami** [comment]
08 Rounded Image
Fixed minor errors, added solution, and improved test format

**Comment by UmiKami** [comment]
Hrs: <hrs>0.78</hrs>

**Comment by UmiKami** [comment]
09 3D Anchor Styles
Added test to prevent user from changing some of the default styles that diminish the purpose of the exercise
Fixed minor issues
Improved format

**Comment by UmiKami** [comment]
Hrs: <hrs>0.91</hrs>

**Comment by UmiKami** [comment]
10 Your Own Font
Fixed issue with CSS rules returning undefined in test
Improved tests
Added solution files for CSS and HTML

**Comment by UmiKami** [comment]
Hrs: <hrs>1.03</hrs>

**Comment by UmiKami** [comment]
11 Font Awesome Icons
Cleaned up some code in the test.js
Fixed minor issues
Added solution

**Comment by UmiKami** [comment]
12 Relative length em rem
Cleaned up some code in the test.js
Added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>1.26</hrs>

**Comment by UmiKami** [comment]
13 Anchor Like Button
Removed unnecessary test.
Cleaned up some code in the test.js
Changed instructions to be more specific on background color.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/61
Hrs: <hrs>1.39</hrs>

**Comment by tommygonzaleza** [comment]
- [ ] The seventh exercise test should check that the user is using `!important` to override the styles
- [ ] The test of the 8th exercise is checking for the wrong solution

**Comment by UmiKami** [comment]
07 Very Specific Rules
- Used regex to check that the user is using !important on the ul li selector color property.

**Comment by UmiKami** [comment]
Hrs: <hrs>1.51</hrs>

**Comment by UmiKami** [comment]
08 Rounded Image

- Deleted unnecessary tests
- Added tests that assert actual solution
- Provided further documentation on the instructions 
- Fixed minor errors on README
- Added additional necessary style (`object-position: top`) to solution.hide.csss

**Comment by UmiKami** [comment]
Hrs: <hrs>1.76</hrs>
