### ISSUE TITLE
Excercise Bug: 18-While_loop

### ISSUE THREAD

**Issue by jeroginaca** [learnpack/learnpack#1087]
Describe the bug:

**1. Exercise Name:** 18-While_loop

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

When I press Test this screen appears
<img width="509" alt="Captura de Pantalla 2022-08-01 a la(s) 16 52 41" src="https://user-images.githubusercontent.com/108022277/182177691-d960d20f-5632-4e87-b0c7-b0b160ee15f7.png">
.

**Comment by tommygonzaleza** [comment]
Hello! The problem is that you have a syntax error in your code. If you want, you can share the code with me and I can help you figure out what the problem is
