### ISSUE TITLE
Excercise Bug: 001-isOldEnoughToDrink

### ISSUE THREAD

**Issue by poncianogr** [learnpack/learnpack#1088]
Describe the bug:

**1. Exercise Name:** 001-isOldEnoughToDrink

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

There was a new update, and whenever you try to do an exercise, a new tutorial pops up and it compiles anytime u write a letter and even if u cheat and copy the answer it gives an error. This bug is in every single exercise of the learnpack.

**Comment by tommygonzaleza** [comment]
Hello! We are working on this issue right now, it will be fixed as soon as possible. By now you can remove the autosave
