### ISSUE TITLE
Excercise Bug: 06-Practicing-Rules

### ISSUE THREAD

**Issue by martinlopez1234** [learnpack/learnpack#1089]
Describe the bug:

**1. Exercise Name:** 06-Practicing-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Pusieron Font-type en vez de font-family para cambiar el estilo de texto.**

**Comment by UmiKami** [comment]
Typo fixed on both READMEs
Part of Test CSS revision: https://github.com/learnpack/learnpack/issues/1072

**Comment by UmiKami** [comment]
Hrs: <hrs>0.05</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.05</hrs>
