### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by 0110000101100010ir** [learnpack/learnpack#109]
# What was the expected behavior?

**in the exercise question, it is showing, "you'll see 101 on green afterwards." instead of you'll see 11 on green afterwards.** 

## Other details: 
1. Exercises: 15-Your-First-Loop
2. Current URL: https://a2572e6c-8d67-4a45-99c0-f00bd42f88dc.ws-us02.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by ElviraQDP** [comment]
Thank you will fix it!
