### ISSUE TITLE
Excercise Bug: 12-my-first-table

### ISSUE THREAD

**Issue by frako23** [learnpack/learnpack#1090]
Describe the bug:

**1. Exercise Name:** 12-my-first-table

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

I have placed all the code and still it does not allow me to finish the task

![mi resultado](https://user-images.githubusercontent.com/110043949/182425020-e0027022-7314-452d-9469-984c6aa0a193.png)
![no me permite seguir](https://user-images.githubusercontent.com/110043949/182425021-bfb55398-9d1d-4e58-9482-40df0c1e5011.png)
![mi codigo](https://user-images.githubusercontent.com/110043949/182425026-dca6f123-2818-4664-86dc-7f1c70e13afb.png)

**Comment by UmiKami** [comment]
User error. The height attribute in the `tr` within the `thead` should `40px` **NOT** `40`

**Comment by UmiKami** [comment]
Hrs: <hrs>0.07</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.07</hrs>
