### ISSUE TITLE
Excercise Bug: 04.3-Add_items_to_array

### ISSUE THREAD

**Issue by dbullor** [learnpack/learnpack#1093]
Describe the bug: No es necesariamente un Bug, pero en español, en la descripción del ejercicio dice que los alumnos no deben usar loop, pero luego en las pistas dice que deben usar loop, entonces creo puede ser medio confuso. Viéndolo en inglés no dice, en las pistas, que deban usar loop.

**1. Exercise Name:** 04.3-Add_items_to_array

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by UmiKami** [comment]
Fixed Spanish README.md

- User is NOT obligated to use a loop to add two items to the array; hence the portion requiring loops was removed.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/82
Hrs: <hrs>0.03</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.03</hrs>

**Comment by tommygonzaleza** [comment]
Hrs:<hrs>0.03</hrs>
