### ISSUE TITLE
Answer #public-support channel's questions

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1098]
Answer all #public-support channel questions.

They should be answered in a short time, we are expecting to answer them within 20 minutes.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.58</hrs>

**Comment by UmiKami** [comment]
Helped solving a coding problem from hackerrank
Helped someone understand how site domains work
Helped someone having issues with github push and pull rebase
Helped someone with JEST test on react
Helped someone understand how css files work
Helped someone with a javascript exercise involving DOM and getting input value
Helped someone having issues with gitpod cookies throwing an error
Helped someone find where the specific errors are found when tests do not pass

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.58</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.58</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.58</hrs>
