### ISSUE TITLE
Test Issue Python

### ISSUE THREAD

**Issue by jatv93** [learnpack/learnpack#11]
Exercise 9 in python-http-requests-api-tutorial-exercises

The test does not validate the result even when it is printing the title of each post:

x (fail) 0. Return a list of post titles like: ['title 1','title 2', 'title 3']

**Comment by josemamunoz** [comment]
El test está bueno, adjunto la imagen

![image](https://user-images.githubusercontent.com/63678589/96946942-1a236f80-14b8-11eb-87f3-c18941cca470.png)

**Comment by alesanchezr** [comment]
@jatv93 tienes la solucion que tu intentaste? Estamos probando y funciona perfecto.

**Comment by jatv93** [comment]
![image](https://user-images.githubusercontent.com/48845580/97382866-17a38a00-18ab-11eb-81ab-8e0d7ea3c632.png)

**Comment by jatv93** [comment]
@alesanchezr viste esto?

**Comment by tommygonzaleza** [comment]
El test está funcionando bien, el problema es que el test prueba tu función y como estás haciendo el request afuera de ella, no lo toma en cuenta y cuando hace la prueba con la función es como si lo demás no existiera. De todas formas para evitar que siga pasando cambie el README.md y lo agregue a las instrucciones.

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises/pull/6
Hrs: <hrs>0.5</hrs>
