### ISSUE TITLE
Excercise Bug: 022-isEitherEven

### ISSUE THREAD

**Issue by SennCode** [learnpack/learnpack#1103]
Describe the bug: No pasa el test 

**1. Exercise Name:** 022-isEitherEven

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercise
<img width="1266" alt="Captura de Pantalla 2022-08-11 a las 20 39 35" src="https://user-images.githubusercontent.com/20642061/184221837-ce1b8be5-9eea-4510-a83d-7c6d71fabd66.png">
s

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/139
