### ISSUE TITLE
Create the Tests of CSS Layouts

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1105]
Improve the tests of the following exercises. Remember that tests in HTML/CSS are a bit different.

Repository: https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

Exercises: From `01-introduction` to `10-static-layout`

Here you have some HTML/CSS Unit Tests Examples: https://docs.learnpack.co/programming-languages/html-css

**This should be done by August 18 of 2022**

**Comment by UmiKami** [comment]
02 Display None
- Added tests
- Added CSS solution
- Added id to ul tag on index.html
- Added more specific CSS link on index.html

**Comment by UmiKami** [comment]
Hrs: <hrs>0.20</hrs>

**Comment by UmiKami** [comment]
03 Position Relative vs Absolute
- Added test to check user has not modified a great extent of original html file

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>

**Comment by UmiKami** [comment]
04 Move the image behind the text

- Added test to check the z-index of the image is below 0, hence putting the image behind the text
- Added solution file

**Comment by UmiKami** [comment]
Hrs: <hrs>0.12</hrs>

**Comment by UmiKami** [comment]
05 Float example
- Added solution
- Fixed wrong code suggestion on hints section in both README files
- Added test
- Improved format of default styles.css file code

**Comment by UmiKami** [comment]
Hrs: <hrs>0.13</hrs>

**Comment by UmiKami** [comment]
06 Center content
- Added HTML and CSS solution files
- Added tests | checks for new div being created and its styles
- Made instructions clearer for testing

**Comment by UmiKami** [comment]
Hrs: <hrs>0.12</hrs>

**Comment by UmiKami** [comment]
07 Sidebar
- Added instructions to readmes
- Added solution
- Added test for display property of wrapper, background colors, and width prop of content div

**Comment by UmiKami** [comment]
Hrs: <hrs>0.25</hrs>

**Comment by UmiKami** [comment]
08 Split Screen in Three
- added wrapper id to parent div
- added tests to check for width of columns and display prop on wrapper
- added CSS solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.07</hrs>

**Comment by UmiKami** [comment]
09 beautify
- added solution files
- added tests that check for key styles
- added tests that check for placement of strong tag
- added test that check for certain amount of 'x' element
- added test that checks if require elements exist

**Comment by UmiKami** [comment]
hrs: <hrs>0.50</hrs>

**Comment by UmiKami** [comment]
09.1 Before and After
- added tests to check for properties to be changed in css
- added solution CSS

**Comment by UmiKami** [comment]
hrs: <hrs> 0.17</hrs>

**Comment by UmiKami** [comment]
09.2 Calendar Icon

- To make it flexible tests only check the user does not change the default HTML
- Added CSS solution file

**Comment by UmiKami** [comment]
hrs: <hrs>0.17</hrs>

**Comment by UmiKami** [comment]
10 Static Layout
- Removed test.js because it is not convenient for this exercise.
- Added solution file
- Clarify instructions in both Spanish and English

**Comment by UmiKami** [comment]
Hrs: <hrs>0.22</hrs>

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/29
Hrs: <hrs>2.03</hrs>

**Comment by tommygonzaleza** [comment]
- [ ] Add validation for center element in 06-content-center (Add all possible center properties)

**Comment by UmiKami** [comment]
06 Center content
- Added most possible ways of centering a div, including those that use position absolute and margin auto.

**Comment by UmiKami** [comment]
Hrs: <hrs>2.40</hrs>

**Comment by UmiKami** [comment]
07 Sidebar
- All content modified to follow new instructions.

**Comment by UmiKami** [comment]
Hrs: <hrs>2.57</hrs>

**Comment by UmiKami** [comment]
09 beautify
- Fixed HTML solution. Had one misspelled ID.

**Comment by UmiKami** [comment]
Hrs: <hrs>2.74</hrs>

**Comment by UmiKami** [comment]
09.1 Before and After
- Tests should no longer be the same

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>

**Comment by UmiKami** [comment]
10 Static Layout
- Made instructions clearer. Told them to user display flex on the secondWrapper

**Comment by UmiKami** [comment]
Hrs: <hrs>2.89</hrs>
