### ISSUE TITLE
Excercise Bug: 11-Dynamic-HTML-String

### ISSUE THREAD

**Issue by dbullor** [learnpack/learnpack#1107]
Describe the bug: I put this code and the test runs ok. But the code is wrong, beacause i only see the year, no the another text.

The code: 
        let myString = "<p>Hello!</p> <strong>My friend</strong> we are in the year ";
        const moonLanding = new Date();
        document.write(moonLanding.getFullYear());

Sorry by my english.

**1. Exercise Name:** 11-Dynamic-HTML-String

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by UmiKami** [comment]
- Added test to check that `document.write` method is being called with `myString` variable
- Added test to check that there is no changes to default value of `myString` variable

**Comment by UmiKami** [comment]
Hrs: <hrs> 0.25 </hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.25</hrs>
