### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Mmandabes** [learnpack/learnpack#111]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

i am doing the react exrecises and the build is working fine, but when i try to test it gives an error even if the code is correct,
is there something i am doing wrong or do i need some package

## Other details: 
1. Exercises: 
2. Current URL: 
3. Repository: uknown

**Comment by ElviraQDP** [comment]
Could you please tell us whic
