### ISSUE TITLE
Error when changing a folder name on LearnPack project

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1114]
When you change a folder of a LearnPack repository while LearnPack is running, it will through an error when you get to that exercise's folder, it will look like this:

![image](https://user-images.githubusercontent.com/56565994/185505344-304183f5-5954-45a6-befe-8a7e91aec36c.png)

The solution for this problem will be to replace the current component that is being displayed for this error.

Here is how the error is being displayed: https://github.com/learnpack/coding-ide/blob/learnpack/src/js/home.js#L353

You should add another validation, to display a different error (The InternalError component) when this specific error message is displayed.

The solution that you will pass to the InternalError should be passed through the message property.

The solution will look like this:

![image](https://user-images.githubusercontent.com/56565994/185506636-86c2f357-6c98-4516-b79c-5b2f55007b81.png)

**Comment by UmiKami** [comment]
- Removed unnecessary smart input component on Home.js
- Added internal error to be render when there is an error loading exercise 
- The internal error passes the solution to resolve the specific issue in the form of html code
