### ISSUE TITLE
Excercise Bug: 04-Class-Selector

### ISSUE THREAD

**Issue by beaesreal** [learnpack/learnpack#1115]
Describe the bug:

**1. Exercise Name:** 04-Class-Selector

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

There's a little mistake. The class has two different names ".b-blue" on the exercise explanation on the right and ".b.blue" on the css code on the left, so it might be confusing :)

**Comment by UmiKami** [comment]
There are no errors. It is written the same in both the instructions and the CSS

**Comment by UmiKami** [comment]
Hrs: <hrs>0.02</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.02</hrs>
