### ISSUE TITLE
Excercise Bug: 07.1-test-post-todo

### ISSUE THREAD

**Issue by Waro** [learnpack/learnpack#1116]
Describe the bug:
the Test is failing due to missing endpoint POST.

here's the code in my app.py

@app.route('/todos', methods=['POST'])
def add_new_todo():
    request.get_json(force=True)
    request_body = request.json
    print("Incoming request with the following body", request_body)
    todos.append(request_body)
        return jsonify(todos), 200

**1. Exercise Name:** 07.1-test-post-todo

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

**Comment by UmiKami** [comment]
No issue found on 07.1 if instructions are followed.
The provided code is for exercise 07.02, in that case it's a user error.
`request_body` should be equal to `request.get_json(force=True)`

**Comment by UmiKami** [comment]
Hrs: <hrs>0.10</hrs>
