### ISSUE TITLE
Excercise Bug: 03-Multiply_two_values

### ISSUE THREAD

**Issue by Julian0816** [learnpack/learnpack#1117]
Describe the bug:

**1. Exercise Name:** 03-Multiply_two_values

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

The tests are not working

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/94
hrs:<hrs>0.2</hrs>
