### ISSUE TITLE
Excercise Bug: 06-lets-start-building

### ISSUE THREAD

**Issue by beaesreal** [learnpack/learnpack#1118]
Describe the bug:

**1. Exercise Name:** 06-lets-start-building

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard
![Captura de pantalla 2022-08-23 103934](https://user-images.githubusercontent.com/111488841/186113225-ac710e1a-bd79-4a9f-835d-673420a9269b.jpg)

It does not work. When I try to test the exercise, the code is not as expected and I have tried all the ways to do that and follow the tutorial but it still doesn't work. 

It says: 
Ready to compile or test...
Ready to compile or test...
Testing your exercise using the html engine.
Socket error: testing-error Could not find the error report for 06-lets-start-building
Could not find the error report for 06-lets-start-building
Ready to compile...

**Comment by tommygonzaleza** [comment]
Hello! There was an issue with plugin installed, we already fixed thee problem.

To solve it, you can open a new repository or run this command: 

```
learnpack plugins:uninstall @learnpack/html && learnpack plugins:install learnpack-html@0.0.20
```
