### ISSUE TITLE
Excercise Bug: 05.1-second-styles

### ISSUE THREAD

**Issue by JBritton2343** [learnpack/learnpack#1121]
Describe the bug:

**1. Exercise Name:** 05.1-second-styles

**2. Repository URL:** https://github.com/4GeeksAcademy/react-tutorial-exercises
unclear instructions the picture shows a white number 2 on the badge, but if you code color: white in the props it fails the tests, also specifying font sizes causes tests to fail.

**Comment by UmiKami** [comment]
- Added hints to make instructions clearer
- Modified test to check for white text color on badge styles

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/96
Hrs: <hrs>0.12</hrs>
