### ISSUE TITLE
Excercise Bug: 064-removeFromBack

### ISSUE THREAD

**Issue by david9833** [learnpack/learnpack#1129]
Describe the bug:

**1. Exercise Name:** 064-removeFromBack

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

Los test: No están funcionando correctamente. A la hora de pasar el test, están llamando a la función sin paréntesis y no da el ejercicio por válido. Los demás test, si los pasa correctamente.

1 Function removeFromBack must return something

         8 | test('Function removeFromBack must return something', () => {    
    >  9 |     expect(removeFromBack[1,2,3]).not.toBe(undefined);
           |                                       ^
      10 | });

2 Function removeFromBack must return a list

        12 | test('Function removeFromBack must return a list', () => {    
    > 13 |     expect(typeof removeFromBack[1,2,3]).toBe("object");
            |                                          ^
      14 | });

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/142
