### ISSUE TITLE
Excercise Bug: 033-isPersonOldEnoughToDrinkAndDrive

### ISSUE THREAD

**Issue by Jen-GM** [learnpack/learnpack#1130]
Describe the bug:

**1. Exercise Name:** 033-isPersonOldEnoughToDrinkAndDrive, 34, 35 and 36. Basically, all of the "old enough to" are repeated from the beginning.

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by tommygonzaleza** [comment]
Hello! Yes they are repeated but with a small change, you have to do it with objects the second time, we want you to try objects with something that you are already familiarized
