### ISSUE TITLE
Excercise Bug: 06-Practicing-Rules

### ISSUE THREAD

**Issue by Congrak** [learnpack/learnpack#1132]
Describe the bug:

i have the good answer but the promgam dont red font-family

/* add your styles here */
body {
	background: url(../../.learn/assets/background-vertical.jpg?raw=true) repeat-y;
	font-family: "Times New Roman", Times, serif;
	padding-left: 20px;
}

h1 {
	font-family: "Courier New", Courier, monospace;
	color: red;
	text-align: center;
}

h2 {
	text-decoration: underline;
}
#id1 {
	background-color: rgba(255, 255, 255, 0.2);
	padding: 5px;
}
a:hover {
	color: green;
	text-decoration: none;
}

**1. Exercise Name:** 06-Practicing-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Hello! Yes the test is being modified, thanks!
