### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by UnassignedByte2504** [learnpack/learnpack#1134]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

There's no video available in the provided link

https://assets.breatheco.de/apis/video/why-pair-programming.

**Comment by UmiKami** [comment]
User error. The video is still up and running.


![Image](https://user-images.githubusercontent.com/60261375/188220045-bca90883-d542-4a1a-b22b-a1dd8c465be6.png)


![Image](https://user-images.githubusercontent.com/60261375/188220087-ae9d4a08-f922-4486-930c-7444a019bfa0.png)

**Comment by UmiKami** [comment]
Hrs: <hrs>0.03</hrs>
