### ISSUE TITLE
Excercise Bug: 06-Practicing-Rules

### ISSUE THREAD

**Issue by dsbt01** [learnpack/learnpack#1137]
Describe the bug:

**1. Exercise Name:** 06-Practicing-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

the test for the fonts is wrong.   I did this:

body {
	font-family: "Times New Roman";
	background-image: url(../../.learn/assets/background-vertical.jpg?raw=true);
	background-repeat: repeat-y;
	padding-left: 20px;
}

but the test reported that the font is wrong:
   x (fail) 1. the font-family should be 'Times New Roman'

Same with:

h1 {
	font-family: "Courier";
	color: red;
	text-align: center;
}

the test is reporting this:

    x (fail) 3. the font-family in the H1 Tag should be 'Courier'

the test condition is wrong.

**Comment by tommygonzaleza** [comment]
This issue has been already solved, thanks for reporting it!
