### ISSUE TITLE
Excercise Bug: 10-Create_a_new_function

### ISSUE THREAD

**Issue by PieroMastro** [learnpack/learnpack#1138]
Describe the bug:

**1. Exercise Name:** 10-Create_a_new_function

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

The YouTube tutorial link refers to exercise 11 instead of the current one (see screenshot) , this is the embedded link: https://www.youtube.com/watch?v=N95pm7kv0a4&ab_channel=4Geeks

![Screenshot 2022-09-01 234304](https://user-images.githubusercontent.com/110270525/188054853-b7394812-3949-4fee-8bf7-e3987bf8ce61.png)

**Comment by tommygonzaleza** [comment]
Hello! Thanks for reporting this issue, we'll work to fix it!
