### ISSUE TITLE
Review exercises from 80 to 100 

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1139]
Tests of exercises from 80 to 100 are having some errors, please review them as soon as possible.

Repository: https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by UmiKami** [comment]
Hrs: <hrs>0.15</hrs>

**Comment by UmiKami** [comment]
081 addToFrontOfNew
- Added solution
- No issues found

**Comment by UmiKami** [comment]
Hrs: <hrs>0.25</hrs>

**Comment by UmiKami** [comment]
addToBackOfNew
- added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.28</hrs

**Comment by UmiKami** [comment]
Hrs: <hrs>0.28</hrs

**Comment by UmiKami** [comment]
083 getAllElementsButNth
- No issues found

**Comment by UmiKami** [comment]
Hrs: <hrs>0.30</hrs>

**Comment by UmiKami** [comment]
084 areValidCredentials
- Added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.35</hrs>

**Comment by UmiKami** [comment]
085 getIndexOf
- added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.47</hrs>

**Comment by UmiKami** [comment]
086 findMinLengthOfThreeWords
- Added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.54</hrs>

**Comment by UmiKami** [comment]
087 findMaxLengthOfThreeWords
- Added solution

**Comment by UmiKami** [comment]
Hrs:<hrs>0.57</hrs>

**Comment by UmiKami** [comment]
Hrs: <hrs>0.67</hrs>

**Comment by UmiKami** [comment]
089 getElementsThatEqual10AtProperty
- Added solution
- Change toBe to toEqual when checking for arrays to avoid test errors

**Comment by UmiKami** [comment]
Hrs: <hrs>0.79</hrs>

**Comment by UmiKami** [comment]
Hrs: <hrs> 0.81 </hrs>

**Comment by UmiKami** [comment]
091 countAllCharacters
- Added solution

**Comment by UmiKami** [comment]
Hrs: <hrs> 0.88 </hrs>

**Comment by UmiKami** [comment]
092 getElementsGreaterThan10AtProperty
- Added solution
- Change toBe to toEqual when checking for arrays to avoid test errors

**Comment by UmiKami** [comment]
Hrs: <hrs>0.91</hrs>

**Comment by UmiKami** [comment]
093 removeElement
- added solution

**Comment by UmiKami** [comment]
Hrs: <hrs>0.94</hrs>

**Comment by UmiKami** [comment]
094 getFirstElementOfProperty
- Added solution
- Fixed tests checking for wrong input

**Comment by UmiKami** [comment]
Hrs: <hrs>1.01</hrs>

**Comment by UmiKami** [comment]
095 getNthElementOfProperty
- Added solution
- Fixed test passing wrong parameters

**Comment by UmiKami** [comment]
Hrs: <hrs>1.11</hrs>

**Comment by UmiKami** [comment]
096 getLastElementOfProperty
- Added solution
- Change toBe to toEqual when checking for arrays to avoid test errors

**Comment by UmiKami** [comment]
097 keep
- Added solution
- Change toBe to toEqual when checking for arrays to avoid test errors

**Comment by UmiKami** [comment]
Hrs: <hrs>1.23</hrs>

**Comment by UmiKami** [comment]
098 getOddLengthWordsAtProperty
- Added solution
- Change toBe to toEqual when checking for arrays to avoid test errors
- Fixed test passing wrong parameters

**Comment by UmiKami** [comment]
Hrs: <hrs>1.35</hrs>

**Comment by UmiKami** [comment]
100 getAverageOfElementsAtProperty
- added solution
- fixed issue with test parameters

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/144
Hrs: <hrs>1.52</hrs>
