### ISSUE TITLE
Dom exercises have bugs in tests

### ISSUE THREAD

**Issue by ehiber** [learnpack/learnpack#1141]
Los tests no son cohorentes con los ejercicios, hay varios que fallan. Acá adjunto una prueba de ellos, pero la mayoría me parece que no están funcionando correctamente.

Al igual que los de eventos. 

Es decir, todo el modulo de THE DOM 

![image](https://user-images.githubusercontent.com/56272634/188695215-67773cc0-e4db-46eb-a041-7fb089506ab5.png)

**Comment by tommygonzaleza** [comment]
Hello! The problem is related with the version you have installed in your workspace, it works fine with the correct jest version. Anyway that is not something that students should care about so we'll try to figure out why gitpod didn't download the correct version

**Comment by tommygonzaleza** [comment]
@UmiKami Gitpod is not installing the correct version of jest (Given in the .gitpodDockerfile) .

Please try to find why it is not installing the correct version, you can ask to gitpod's support: https://www.gitpod.io/support

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/55
Hrs: <hrs>0.17</hrs>

**Comment by UmiKami** [comment]
Putting the version of jest between quotation marks fixes the issue
Reference: https://stackoverflow.com/a/50515522/14602567

**Comment by tommygonzaleza** [comment]
Perfect!
