### ISSUE TITLE
Excercise Bug: 07-Function-that-returns

### ISSUE THREAD

**Issue by JackCaldwellNichols** [learnpack/learnpack#1144]
Describe the bug: Instruction indicate to use 127 dollars but in test 137 dollars is expected. 

**1. Exercise Name:** 07-Function-that-returns

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

**Comment by UmiKami** [comment]
There is no issue with the test make sure you are doing it in the right order.


![Image](https://user-images.githubusercontent.com/60261375/190275583-c1f5016f-c365-44e8-99aa-cd17211fcd0d.png)

**Comment by UmiKami** [comment]
Added solution file

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/76
Hrs: <hrs>0.02</hrs>
