### ISSUE TITLE
Excercise Bug: 13-Your_first_switch

### ISSUE THREAD

**Issue by Lconforme** [learnpack/learnpack#1145]
Describe the bug:

**1. Exercise Name:** 13-Your_first_switch

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by UmiKami** [comment]
exercise works fine but added solution.hide

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/101
Hrs: <hrs>0.07</hrs>
