### ISSUE TITLE
Add solution.hide to the exercises of html forms

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1148]
- [ ] Add a solution.hide file to each exercise of the repository.

Repository: https://github.com/4GeeksAcademy/html-forms-tutorial-exercises

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/35
Hrs: <hrs>0.60</hrs>

**Comment by UmiKami** [comment]
Just added solutions and formatted two unformatted HTML files.
