### ISSUE TITLE
Excercise Bug: 11-Your_first_if

### ISSUE THREAD

**Issue by Dertyos** [learnpack/learnpack#1151]
Describe the bug:

**1. Exercise Name:** 11-Your_first_if

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

En las instrucciones pide "I'm parking, I'll see you right now"
Al testear busca "I'm parking. I'll see you right now"
la diferencia es que las instrucciones estan con "," y el test con "." por tanto no pasa el test.

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/102
hrs: <hrs>0.16</hrs>

**Comment by dsilva06** [comment]
there was nothing wrong with the test, the solution passed perfectly and the test were doing what they were supposed to do
