### ISSUE TITLE
Create bootstrap 5 lesson

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1153]
- [ ] Create a copy of this file: https://github.com/breatheco-de/content/blob/master/src/content/lesson/bootstrap-tutorial-of-bootstrap-4.md in the same location but with the name bootstrap-tutorial-of-bootstrap-5.md
- [ ] Use the same content contained in the file but migrate it to bootstrap v5: https://getbootstrap.com/docs/5.0/migration

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/content/pull/971

**Comment by UmiKami** [comment]
Hrs: <hrs>1.18</hrs>

**Comment by tommygonzaleza** [comment]
The image with components is missing

**Comment by UmiKami** [comment]
Image updated

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/content/pull/973
Hrs: <hrs>1.51</hrs>
