### ISSUE TITLE
Excercise Bug: 04.3-id-Selector

### ISSUE THREAD

**Issue by minervaDutta** [learnpack/learnpack#1156]
Describe the bug:

**1. Exercise Name:** 04.3-id-Selector

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Spelling of styles as "stiles" on line 1

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/67
hrs: <hrs>0.16</hrs>
