### ISSUE TITLE
Excercise Bug: 06-Create-DOM-Element-Second

### ISSUE THREAD

**Issue by Lconforme** [learnpack/learnpack#1158]
Describe the bug:

**1. Exercise Name:** 06-Create-DOM-Element-Second

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

Element won't set without deleting the h1

**Comment by UmiKami** [comment]
There is no need to delete the H1, you can put the img tag within the existing innerHTML declaration

Like this:
`document.body.innerHTML = `<h1>Hello World</h1><img src="http://placehold.it/350x150"/>`;`

**Comment by UmiKami** [comment]
Updated solution file to use working image link

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/57
Hrs: <hrs>0.10</hrs>

**Comment by tommygonzaleza** [comment]
- [ ] In the solution.hide.js add only the img instead of h1 and img
- [ ] Remove the test that check if the h1 exists

**Comment by UmiKami** [comment]
- Made index.js file clearer
- [X] Removed h1 and added img tag to solution.hide.js file
- [X] Removed the test that checks if the h1 exists

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/57
Hrs: <hrs>0.17</hrs>
