### ISSUE TITLE
Excercise Bug: 10-Your-Own-Font

### ISSUE THREAD

**Issue by Blancreyes** [learnpack/learnpack#1159]
Describe the bug:

**1. Exercise Name:** 10-Your-Own-Font

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

En la ejecución del ejercicio, luego de introducir las líenas de código y compilar, indica el siguiente error:
        x (fail) 2. The link should be included in the head tag

Sin embargo el link efectivamente está incluido en el HEAD tag:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/62549906/191489700-1da1d25a-96df-4b32-b3db-1f0648d63755.png">

**Comment by UmiKami** [comment]
- Fixed test looking for 2 links instead of 4
- Added 2 missing links to solution.html

**Comment by UmiKami** [comment]
Problema solucionado

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/69
Hrs: <hrs>0.08</hrs>
