### ISSUE TITLE
Excercise Bug: 01.3-Your-Second-Style

### ISSUE THREAD

**Issue by francisco9505** [learnpack/learnpack#1160]
Describe the bug: the exercise was already done

**1. Exercise Name:** 01.3-Your-Second-Style

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/70
hrs: <hrs>0.2</hrs>
