### ISSUE TITLE
Excercise Bug: 03-hello-without-head

### ISSUE THREAD

**Issue by pyslarash** [learnpack/learnpack#1161]
Describe the bug:
When I was typing my own H1 tags, the code wouldn't work. I typed them correctly and triple-checked. When I copy-pasted them, everything worked just fine.

**1. Exercise Name:** 03-hello-without-head

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Hey! That looks like a really weird issue, it could be related with vscode more than LearnPack, please let me know if it happens again and feel free to text me through slack so we can check it together
