### ISSUE TITLE
10-your-own-font is not checking the fontawesome url correctly

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1163]
Remember it should be very flexible, check the test and find the problem with it

![image](https://user-images.githubusercontent.com/56565994/192825851-80468c33-8f1b-4af5-bc61-c7c0bf46d07b.png)

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/70
hrs: <hrs>0.5</hrs>

**Comment by dsilva06** [comment]
made the test more flexible, now you can insert more than one link inside the head tag
