### ISSUE TITLE
07-Very-Specific-Rules tests are failing with a working solution

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1164]
Make sure the test is working fine and it is very flexible to different possible solutions

Repository: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

![image](https://user-images.githubusercontent.com/56565994/192826270-07bbd049-0e86-4431-aead-62c7a3d5baef.png)

**Comment by dsilva06** [comment]
pr :https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/71
hrs: <hrs>0.55</hrs>
