### ISSUE TITLE
Excercise Bug: 07.2-finish-post-todo

### ISSUE THREAD

**Issue by Systemjon** [learnpack/learnpack#1167]
Describe the bug:

**1. Exercise Name:** 07.2-finish-post-todo

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

al pasarlo a español dice otra cosa distinta en el ejemplo

**Comment by tommygonzaleza** [comment]
Hola! Ya este issue fue reportado, gracias de todas formas!
