### ISSUE TITLE
Create the solution.hide.py files for each exercise

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1169]
Create a solution file for each of the exercises in this tutorial

Repository: https://github.com/breatheco-de/python-flask-api-tutorial

**Comment by UmiKami** [comment]
_Added solutions for exercises:_ 

3, 3.1, 3.3, 5, 7, 7.2, 8, 8.2

_json.dumps was causing tests to not pass in the following exercises:_

8, 8.1, 8.2

**Solution:** Substituted data=json.dumps({}) with json=({})
