### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by vgvg123asd** [learnpack/learnpack#117]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

## Other details: 
1. Exercises: 01-hello-world
2. Current URL: https://e2162012-2eef-4136-bc91-582ed2789c9b.ws-eu01.gitpod.io
3. Repository: https://github.com/breatheco-de/python-flask-api-tutorial

**Comment by ElviraQDP** [comment]
Could you please explain the issue?
