### ISSUE TITLE
Add properties to learn.json of all tutorials

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1172]
Add the following properties to the learn.json of all the exercise tutorials
- bugs_link: `"https://github.com/learnpack/learnpack/issues/new"`
- video_solutions: true/false (Boolean depending if it has video_solutions or not)

Tutorials:
- [ ]  Build a postcard using HTML/CSS
- [ ]  HTML5 Forms (10 hrs)
- [ ]  Learn CSS (10 hrs)
- [ ]  Learn CSS Layouts (4 hrs)
- [ ]  Learn Bootstrap (10 hrs)
- [ ]  Introduction to The DOM (4 hrs)
- [ ]  Events inside The DOM (4 hrs)
- [ ]  Looping with Javascript (8 hrs)
- [ ]  Javascript Functions (2 hrs)
- [ ]  Object Oriented Programming is Javascript
- [ ]  Master Javascript with 150 exercises (50 hrs)
- [ ]  Learn React.js (3 hrs)
- [ ]  Unit testing with Jest (2 hrs)
- [ ]  Python for Beginners (20 hrs)
- [ ]  Practice Looping Lists and Tuples (30 hrs)
- [ ]  Practice functions (10 hrs)
- [ ]  Master Python (50 hrs)
- [ ]  Python API Requests (10 hrs)
- [ ]  Build API's with Python Flask

**Comment by kiddopro** [comment]
- [ ] https://github.com/breatheco-de/exercise-postcard/pull/67
- [ ] https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/77

**Comment by kiddopro** [comment]
Hrs: <hrs>1.3</hrs>
