### ISSUE TITLE
Excercise Bug: 073-countNumberOfKeys

### ISSUE THREAD

**Issue by betolix** [learnpack/learnpack#1175]
Describe the bug:

**1. Exercise Name:** 073-countNumberOfKeys

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

Code:

function countNumberOfKeys(obj) {
    // your code here
    var size = Object.keys(obj).length;
    return size;
}

let obj = {
    a: 1,
    b: 2,
    c: 3,
  };

  let output = countNumberOfKeys(obj);
  console.log(output); // --> 3

Output:

 ✓ (done) 0. Function countNumberOfKeys must exist
     ✓ (done) 1. Function countNumberOfKeys must return something
     ✓ (done) 2. Function countNumberOfKeys must return a number
     x (fail) 3. The function must returns how many properties the given object has.
     ✓ (done) 4. The function must returns how many properties the given object has.
     ✓ (done) 5. The function must returns how many properties the given object has.

Observation:
Testing not evaluating properly;

**Comment by UmiKami** [comment]
Issue fixed.

Reason: Variable was not properly declared on test.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/152
Hrs: <hrs>0.05</hrs>
