### ISSUE TITLE
Excercise Bug: 11-Font-Awesome-Icons

### ISSUE THREAD

**Issue by Johndbm** [learnpack/learnpack#1176]
Describe the bug:

**1. Exercise Name:** 11-Font-Awesome-Icons

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Bug:

Is the 4th step mandatory in that way? The web page loads succesfully, but the expected result of the excersise tells me the Font I should use must have a class "fas" as the first object from the example. Isn't this a variable value?

![image](https://user-images.githubusercontent.com/46007970/194735957-058de55b-fded-49f1-b9f9-19052f154c97.png)

![image](https://user-images.githubusercontent.com/46007970/194735850-31dc28fb-8043-4b5b-a426-760d67424b91.png)

Terminal Output:
![image](https://user-images.githubusercontent.com/46007970/194736007-3f7ef207-ef81-48bc-a879-19c671373c19.png)

` ✓ (done) 0. ul tag should exists
     ✓ (done) 1. At least 3 li tags should exist
     ✓ (done) 2. At least 3 i tags should exist
     ✓ (done) 3.  LI innerHTML exist
     x (fail) 4. the i tag should have a class "fas"`

**Comment by Johndbm** [comment]
Fonts-Awesome only have classes starting with "fa-xxxx"
![image](https://user-images.githubusercontent.com/46007970/194736275-c01b3995-e50d-49fa-89bb-fb4dfb5ac3cc.png)

**Comment by Johndbm** [comment]
It seems they changed the standard names from "**_fas_**-xxx" to "**fa**-xxx"
![image](https://user-images.githubusercontent.com/46007970/194736399-719289f0-33ef-4871-b210-d6a895a159e7.png)

**Comment by Johndbm** [comment]
Finally ended up _"cheating"_ using the same icon's class name, to keep moving.

Hope it helps to anyone else doing the _**Pre-Work**_

![image](https://user-images.githubusercontent.com/46007970/194736471-3195be0c-b311-40d3-aba3-c60183f81219.png)
![image](https://user-images.githubusercontent.com/46007970/194736487-8f122ac4-f2ae-4285-8d97-9f24641c498e.png)
![image](https://user-images.githubusercontent.com/46007970/194736539-81ec9018-32c3-4c0a-8792-ac6135be17cf.png)

**Comment by UmiKami** [comment]
fas = fa-solid
fab = fa-brand

fas is an abbreviation to avoid writing fa-solid

It is true that fas won't work with fa-brand. Initiating fix.

**Comment by UmiKami** [comment]
Made test more flexible, now it should accept any class with fa-
