### ISSUE TITLE
Excercise Bug: 104-getOddElementsAtProperty

### ISSUE THREAD

**Issue by betolix** [learnpack/learnpack#1177]
Describe the bug:

**1. Exercise Name:** 104-getOddElementsAtProperty

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**3. Code

let obj = {
  key: [1, 2, 3, 4, 5]
};

function getOddElementsAtProperty(obj, key) {
    // your code here
    if( !obj[key] || !Array.isArray(obj[key])|| obj[key].length<1 ) return[];
    
    arrX=[];
    cont=0;
    for(i=0;i<obj[key].length; i++){
      if(i%2==0){
        arrX[cont]=obj[key][i];
        cont++;
      }
    }
    return arrX;
}

let output = getOddElementsAtProperty(obj, 'key');
console.log(output); // --> [1, 3, 5]

**4. Output
    ✓ (done) 0. Function getOddElementsAtProperty must exist
     ✓ (done) 1. Function getOddElementsAtProperty must return something
     ✓ (done) 2. Function getOddElementsAtProperty must return an array
     ✓ (done) 3. The function must return the odd elements of the array located in the given key.
     ✓ (done) 4. If the array is empty, it should return an empty array.
     x (fail) 5. If it contains no odd elements, it should return an empty array.
     ✓ (done) 6. If the property in the given key is not an array, it should return an empty array.
     ✓ (done) 7. If the property in the given key is not an array, it should return an empty array.
     ✓ (done) 8. If the property in the given key is not an array, it should return an empty array.
     ✓ (done) 9. If there is no property on the key, it should return an empty array. 

**5. Observation:
Code fulfills requirements but the eval reports it as failing item 5.

**Comment by tommygonzaleza** [comment]
Hello! In your code, it looks like you are not declaring `arrX` and `cont`. It's currently working when you try to build it because the compiler is fixing it for you, but the test is more strict

**Comment by UmiKami** [comment]
Your solution is not correct:

1. Your `arrX` and `cont` variables are not being properly declared. You need to use either the `let` or `const` keywords before the variable name. You are also not properly declaring the `i` variable, it should be `let i = 0`
2. You are using the `i` variable to evaluate if it is even or odd. You are not supposed to evaluate if `i` is even or odd, you are supposed to evaluate which of the elements of the array at a given key are even or odd. 
    - Additionally, in your code, you are evaluating whether a number is even. The question wants you to evaluate whether a number is odd, **not** even. Any `num % 2 == 0` is even.
3. Regarding failing item 5. The test is correct. You should return an empty array if the array does **not** contain any odd numbers. You are never validating for this.

**Comment by UmiKami** [comment]
No PR needed.
Hrs: <hrs>0.13</hrs>
