### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by ARedondoVilla** [learnpack/learnpack#118]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

The declaration of function random() is a reserved word. The console show an error due to this definition. I´ve changed random() to get_random for solve this error.

## Other details: 
1. Exercises: 01.4-Add-item-to-list
2. Current URL: https://c0bd1608-103b-458d-8973-0f600236ba9d.ws-eu01.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

**Comment by ElviraQDP** [comment]
check once I'm revising Python exercises
