### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by soraiamm** [learnpack/learnpack#1183]
Describe the bug:

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

I've completed the exercise but when I test it, there is something incorrect in the test, it's failing on one point asking for me to do something that was never asked in the exercise, and when I go to solution my code is write, I'm sending a screen shot so you can see the test "fail" that is incorrect. See where it says "fail". See the exercise does not ask to do this step and when I do it it still says "fail" so something is wrong in the testing code.

<img width="2366" alt="Screen Shot 2022-10-11 at 10 06 45 AM" src="https://user-images.githubusercontent.com/115166327/195113631-0bc5e1a2-ff56-419f-9084-81d041086e33.png">

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/74
hrs: <hrs>0.2</hrs>

**Comment by dsilva06** [comment]
there is nothing wrong with the test code. Check the CSS carefully, the problem is where you are directing the styles to.
