### ISSUE TITLE
Excercise Bug: 10-Create_a_new_function

### ISSUE THREAD

**Issue by Jnv821** [learnpack/learnpack#1184]
Describe the bug: Instructions don't match the answer. The instructions asks to define a function `generateRandom` that generates a pseudo-random number between 0 and 9. The answer is to generate a random number using `Math.random()` and nothing more.

![image](https://user-images.githubusercontent.com/95052283/195179099-e056b30e-177f-46ce-9c24-47fc19556054.png)

**1. Exercise Name:** 10-Create_a_new_function

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by dsilva06** [comment]
made the instructions more understandable. There is a link that indicates how to use the Math.random && Math.floor functions(as we indicate in the instructions).
