### ISSUE TITLE
Excercise Bug: 071-removeStringValuesLongerThan

### ISSUE THREAD

**Issue by santiagoss01** [learnpack/learnpack#1185]
Describe the bug:

**1. Exercise Name:** 071-removeStringValuesLongerThan

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/151
hrs: <hrs>0.3</hrs>

**Comment by dsilva06** [comment]
gave a hint on the readme so that you can investigate more on how to solve the issue
