### ISSUE TITLE
Redo examples of bootstrap 5 lesson

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1187]
The examples are not good, use the examples provided by bootstrap and make sure they are different than bootstrap v4's examples.

- [ ] Redo examples of bootstrap v5's lesson
- [ ] Redo examples of bootstrap v4's lesson (In both languages)

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/content/pull/1012
Hrs: <hrs>0.17</hrs>

**Comment by UmiKami** [comment]
- [X] Redid navbar example in bootstrap v5 lesson
  - [X]  Fixed links at the bottom of the file too on the section "What you really need to know about Bootstrap"
- [X] Redid navbar example in bootstrap v4 lesson ES and EN

**Did not see any other examples that do not match their image preview**

**Comment by UmiKami** [comment]
Added font-awesome icons to all bootstrap lessons (4, 4es, 5, 5es)
