### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by janinaestrella** [learnpack/learnpack#119]
# What was the expected behavior?
The task is to be able to display the output according to the image but unfortunately, file not found is displayed and no other instructions were found.

Please take 2 minutes to explain what happened, include screenshot if possible.
![image](https://user-images.githubusercontent.com/67820584/99557442-fd009480-29c2-11eb-9dcc-b5cec0f4489c.png)

## Other details: 
1. Exercises: 05.1-second-styles
2. Current URL: https://bf19a7be-8d26-400a-87c6-cc07269eea38.ws-eu01.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by ElviraQDP** [comment]
Hemos arreglado el imagen
