### ISSUE TITLE
Excercise Bug: 04-Class-Selector

### ISSUE THREAD

**Issue by Pas0ta** [learnpack/learnpack#1191]
Describe the bug:

**1. Exercise Name:** 04-Class-Selector

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

en el archivo de test hay un error, la clase esta puesta como "b-blue" pero en el ejercicio se indica la clase ".b-blue" por lo que da error constantemente por mucho que este correcto. un saludo

**Comment by tommygonzaleza** [comment]
Hola! Lo que pasa es que cuando uno hace referencia a una clase, pone el punto al inicio ".clase" sin embargo al momento de usarla no se pone
