### ISSUE TITLE
When this repo is forked, it fails to build

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1193]
Anyway it works when you try it from the original one

Add a prefixed python version in the .gitpod.Dockerfile

Repository: https://github.com/breatheco-de/exercise-starwars-data-modeling

**Comment by UmiKami** [comment]
Works for me. Forked the repo, opened it with gitpod, everything built as it should.

**Comment by UmiKami** [comment]
A prefixed version of python should be installing already on:
`RUN pyenv install 3.6.4`

I was able to verify this after the fork and opening it with gitpod.


![Image](https://user-images.githubusercontent.com/60261375/197633170-69f850d7-0c1a-4d97-afd3-aeba1647b28b.png)

**Comment by UmiKami** [comment]
Created a new github account, forked the repository, currently awaiting for built to finish

**Comment by UmiKami** [comment]
Was able to replicate the error with my new github account

**Comment by UmiKami** [comment]
Proceeding to find fix

**Comment by UmiKami** [comment]
Seems to be a gitpod issue 

Runs with my main account (Umikami) even after deleting the fork and forking it again. However, it does not work with my new account. Could it be due to changes on gitpod that apply to new users but not old users?

**Comment by UmiKami** [comment]
This could be related although it is very recent: https://www.gitpod.io/changelog#projects-now-only-created-under-teams-not-personal-accounts

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/exercise-starwars-data-modeling/pull/19
Hrs: <hrs>1.25</hrs>

**Comment by UmiKami** [comment]
Had to downgrade pipenv to install dependencies without errors
