### ISSUE TITLE
Add the property projectType to all the tutorials

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1194]
Add the property `projectType: "tutorial"` to all the tutorials.

Tutorials:
- [ ]  Build a postcard using HTML/CSS
- [ ]  HTML5 Forms (10 hrs)
- [ ]  Learn CSS (10 hrs)
- [ ]  Learn CSS Layouts (4 hrs)
- [ ]  Learn Bootstrap (10 hrs)
- [ ]  Introduction to The DOM (4 hrs)
- [ ]  Events inside The DOM (4 hrs)
- [ ]  Looping with Javascript (8 hrs)
- [ ]  Javascript Functions (2 hrs)
- [ ]  Object Oriented Programming is Javascript
- [ ]  Master Javascript with 150 exercises (50 hrs)
- [ ]  Learn React.js (3 hrs)
- [ ]  Unit testing with Jest (2 hrs)
- [ ]  Python for Beginners (20 hrs)
- [ ]  Practice Looping Lists and Tuples (30 hrs)
- [ ]  Practice functions (10 hrs)
- [ ]  Master Python (50 hrs)
- [ ]  Python API Requests (10 hrs)
- [ ]  Build API's with Python Flask

**Comment by kiddopro** [comment]
Build a postcard using HTML/CSS - https://github.com/breatheco-de/exercise-postcard/pull/69
 HTML5 Forms (10 hrs) - https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/41
 Learn CSS (10 hrs) - https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/76
 Learn CSS Layouts (4 hrs) - https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/33
 Learn Bootstrap (10 hrs) - https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/42
 Introduction to The DOM (4 hrs) - https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/59
 Events inside The DOM (4 hrs) - https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/22
 Looping with Javascript (8 hrs) - https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/93
 Javascript Functions (2 hrs) - https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/78
 Object Oriented Programming is Javascript - https://github.com/4GeeksAcademy/object-oriented-javascript-tutorial-exercises/pull/17
 Master Javascript with 150 exercises (50 hrs) - https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/154
 Learn React.js (3 hrs) - https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/98
 Unit testing with Jest (2 hrs) - https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/43
 Python for Beginners (20 hrs) - https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/73
 Practice Looping Lists and Tuples (30 hrs) - https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/98
 Practice functions (10 hrs) - https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/41
 Master Python (50 hrs) - https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/45
 Python API Requests (10 hrs) - https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises/pull/17
 Build API's with Python Flask - https://github.com/breatheco-de/python-flask-api-tutorial/pull/54

**Comment by kiddopro** [comment]
Hrs: <hrs>0.75</hrs>
