### ISSUE TITLE
Excercise Bug: 10-static-layout

### ISSUE THREAD

**Issue by Hon07** [learnpack/learnpack#1195]
Describe the bug:
I do not know if its supposed to be there but from the excercise 9.2 on it would not let me test my code
**1. Exercise Name:** 10-static-layout

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

**Comment by tommygonzaleza** [comment]
Hello! Some tests were disabled because the exercises are so flexible
