### ISSUE TITLE
Excercise Bug: 06-Create-DOM-Element-Second

### ISSUE THREAD

**Issue by chemawall** [learnpack/learnpack#1198]
Describe the bug:

**1. Exercise Name:** 06-Create-DOM-Element-Second

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by UmiKami** [comment]
No issue found.

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.17</hrs>
