### ISSUE TITLE
Broken Image Link

### ISSUE THREAD

**Issue by ierrandonea** [learnpack/learnpack#12]
Hi! Ran the compiler and followed url but 404.
![image](https://user-images.githubusercontent.com/57204150/87329782-80861280-c505-11ea-94c0-771de5874b2c.png)
![image](https://user-images.githubusercontent.com/57204150/87329803-87ad2080-c505-11ea-87b4-d94c2829cb0c.png)
![image](https://user-images.githubusercontent.com/57204150/87329823-94317900-c505-11ea-8175-55b7217a4052.png)

**Comment by ElviraQDP** [comment]
the link is up and running!
