### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by SamHnnz** [learnpack/learnpack#120]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Basically the link is broken https://www.youtube.com/watch?v=2xDzVZcqtYI

## Other details: 
1. Exercises: 23-The-Beatles
2. Current URL: https://c4a0a2d9-0254-43a8-9ae5-61328d0303fa.ws-eu01.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by ElviraQDP** [comment]
issue solved
