### ISSUE TITLE
The exercises dropdown of the navbar

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1203]
- [ ] When you click on the hamburger, it should open the list of exercises.
- [ ] When you click on any of the exercises, it should close the dropdown and show the exercise's readme.
- [ ] When you click on the question mark icon, it should redirect you to the FAQ page. Check how we are getting the FAQ atm: https://github.com/learnpack/coding-ide/blob/35754fe4f0eb7e0cbe321f31e760a24d27a9c250/src/js/components/help/help.js

![image](https://user-images.githubusercontent.com/56565994/199370241-66a461de-5a4d-4fc7-b4de-58987f264d2b.png)

**Comment by karlacuevasc** [comment]
<hrs>3 hrs</hrs>
