### ISSUE TITLE
Navbar's Bug Icon

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1204]
- [x] When you click on the bugs icon, it should redirect the user to a different window. The link that the user should be redirected to will be included in the config file, you can access it this way: `config.config.bugsLink`.
- [x] You should also include in the query string, a template for GitHub issues, similar to the one we had in the previous coding-ide version: https://github.com/learnpack/coding-ide/blob/learnpack/src/js/home.js#L463
- [x] Make sure the bugsLink doesn't include a slash at the end (Add a validation and transform it if it has)
- [x] If there is now bugsLink, it shouldn't show the bugs icon

In the end, the link will look something like this:

```
bugLink={`${config.config.bugsLink}?assignees=&labels=&projects=learnpack/1&title=Excercise%20Bug:%20${this.state.current.slug}&body=Describe the bug:%0D%0A%0D%0A**1.%20Exercise%20Name:**%20${config.config.current.slug}%0D%0A%0D%0A**2.%20Repository%20URL:**%20${config.config.repository}`}
```

![image](https://user-images.githubusercontent.com/56565994/199370618-aab37550-b0a2-4f24-8888-798368247dd9.png)

**Comment by UmiKami** [comment]
PR: https://github.com/learnpack/learnpack-ide/pull/4
Hrs: <hrs>1.03</hrs>

**Comment by UmiKami** [comment]
- Added afterUpdate function to make sure the bugs button is removed after checking there is no bugs link
- Added removeEndSlash function which takes in a url, checks if that last character is a forward slash, and removes it. Else it returns the url as it was given.
- Added navigateToBugReportPage function which gets called from an on:click event in the bugs button. The functions checks if the bugslink is available and then opens a new blank window with the provided query string.
