### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by SheepDogg586** [learnpack/learnpack#1208]
Describe the bug:

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Code is set to odd rows within the table to have a background of yellow as instructions specify but is still being marked wrong.

**Comment by UmiKami** [comment]
The test works fine for me. Might need for details on the issue. Avoid using rgb or hex values to define the colors if your doing so. You can also refer to the solution.hide.css file to compare with your solution and check what you might be doing wrong. 

This is how it should look:

```css
tr:nth-child(odd) {
	background: yellow !important;
}
```

**Comment by UmiKami** [comment]
Hrs: <hrs>0.12</hrs>
