### ISSUE TITLE
Excercise Bug: 08-Rounded-Image

### ISSUE THREAD

**Issue by galdea** [learnpack/learnpack#1209]
Describe the bug:

No tutorial

**1. Exercise Name:** 08-Rounded-Image

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Hey! We will create tutorials for all the exercises in the short future, I'm creating the tasks so we can work on them. Thanks for letting us know
