### ISSUE TITLE
Excercise Bug: 11.2-header-styles Postcard

### ISSUE THREAD

**Issue by emanuel-c4** [learnpack/learnpack#1217]
Describe the bug: The English and Spanish versions are different in the Instructions section. 

**1. Exercise Name:** 11.2-header-styles

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

![image](https://user-images.githubusercontent.com/36056518/200943048-a550bcf4-d480-4988-977e-e66e57151409.png)

![image](https://user-images.githubusercontent.com/36056518/200942691-399fba68-c29d-4dc5-b5f8-32515daf1d02.png)

**Comment by tommygonzaleza** [comment]
Ya lo arreglamos, muchas gracias
