### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Cristian-Alvarez-CL** [learnpack/learnpack#122]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Me arroja error --> x (fail) 0. Did you create a function named "renderPerson" that expects five parameters?

Esta es mi funsion -->
var renderPerson = function(name, date, color, year, sex){
    let msj = `${name} is a ${year} years old ${sex} born on ${date} with ${color} eyes`;
	return msj;
}

![Captura de Pantalla 2020-11-25 a la(s) 21 12 06](https://user-images.githubusercontent.com/57689930/100293602-0198f000-2f63-11eb-98cb-f2461df02c28.png)

## Other details: 
1. Exercises: 09-Function-parameters
2. Current URL: https://bdb3d684-43a7-47f6-a278-b5d7f4a3d2e4.ws-us02.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

**Comment by ElviraQDP** [comment]
revisa bien tu cofigo!
