### ISSUE TITLE
Excercise Bug: 067-isEitherEvenAndLessThan9

### ISSUE THREAD

**Issue by olimpo127** [learnpack/learnpack#1224]
Describe the bug:

**1. Exercise Name:** 067-isEitherEvenAndLessThan9

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

The problem is not correctly explained:
"should return true only if one of the numbers is even" 
This means that ONLY if one is even should return true... However what it really means to ask is to return true if AT LEAST one of them is even.

Code is ok, just the written problem should be fixed

**Comment by tommygonzaleza** [comment]
Thank you! Solved
