### ISSUE TITLE
Excercise Bug: 027-computeAreaOfATriangle Master Javascript by Practice

### ISSUE THREAD

**Issue by emanuel-c4** [learnpack/learnpack#1225]
Describe the bug: Hay un espacio nbsp en el ejemplo. 
`## Example:` este es el actual texto
![image](https://user-images.githubusercontent.com/36056518/202938287-3492cbdc-2e77-4c93-a806-bf932b15b7d2.png)

**1. Exercise Name:** 027-computeAreaOfATriangle

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by tommygonzaleza** [comment]
Problem fixed!
