### ISSUE TITLE
Excercise Bug: 07.1-analysing-the-test

### ISSUE THREAD

**Issue by santiagoss01** [learnpack/learnpack#1229]
Describe the bug:
There is one part of the excercise steps missing. It jumps from 6 to 07.1. Slide 07 is not there and it contains crucial information.

**1. Exercise Name:** 07.1-analysing-the-test

**2. Repository URL:** https://github.com/breatheco-de/exercise-unit-test-with-jest

**Comment by tommygonzaleza** [comment]
Hello! Problem solved!
