### ISSUE TITLE
Excercise Bug: 10-Create_a_new_function

### ISSUE THREAD

**Issue by Betojr04** [learnpack/learnpack#1231]
Describe the bug:
Instructions require numbers between 1 and 10 but the test requires a number between 0 and 9.

**1. Exercise Name:** 10-Create_a_new_function

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by UmiKami** [comment]
Fixed test descriptions

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/110
Hrs: <hrs>0.08</hrs>
