### ISSUE TITLE
Excercise Bug: 09-Beautify

### ISSUE THREAD

**Issue by Otto777L** [learnpack/learnpack#1233]
Describe the bug:

**1. Exercise Name:** 09-Beautify

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

It asks for at least 6 div elements in the test, but it only works if there are 7 or more in the exercise.

**Comment by tommygonzaleza** [comment]
Hello! This problem has already been reported, we are working to fix it
