### ISSUE TITLE
Excercise Bug: 14-Random_numbers Javascript Beginner Tutorial

### ISSUE THREAD

**Issue by emanuel-c4** [learnpack/learnpack#1242]
Describe the bug:
Actualmente el ejercicio hace alusión a ejercicio 11, pero el 11 es la introdución a los if. En su caso debería ser el ejercicio 10, que es de generar un número aleatorio

![image](https://user-images.githubusercontent.com/36056518/205438986-9886e422-432f-4a03-8c62-a00b6464c020.png)

**1. Exercise Name:** 14-Random_numbers

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by tommygonzaleza** [comment]
Solved! Thanks
