### ISSUE TITLE
Excercise Bug: 153-isRotated

### ISSUE THREAD

**Issue by jossvo** [learnpack/learnpack#1248]
Describe the bug:

**1. Exercise Name:** 153-isRotated

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Test no. 5 is wrong: Expects true but is false**
The test no. 5 expects true but should be false because a letter n is missing. When checking the “solution" code, it seems to me that it reviews that all the letters are present, but not the same frequency, for example y changed 1 letter "o" for a letter "x" and the "solution" code still counted that string as a rotation of the original one.
![Screen Shot 2022-12-06 at 11 19 39](https://user-images.githubusercontent.com/63322149/205980558-d0820544-7414-41c6-a742-1cfb1fefd36c.png)

**Comment by UmiKami** [comment]
Needs further revision.
Partial Hrs: <hrs>0.45</hrs>

**Comment by UmiKami** [comment]
Verified leetcode working solution: 
```js
  if (A === B) return true;
	if (A.length !== B.length) return false;
  
  let i;
  for (i = 0; i < A.length; i++) {
    if (B[0] === A[i]) {
    	if (A.slice(i) === B.slice(0, B.length-i) &&     A.slice(0, i) === B.slice(-i)) {
    		return true;
    	} 
    }
  }
  return false;
```

The exercise needs to be reevaluated. Instructions unclear, tests unclear, solution unclear, and expected output unclear.

**Comment by tommygonzaleza** [comment]
Add better explanations to the instructions (English and Spanish), as a hint explain what rotated is, which is when the order of the letters is rotated to the right.

**Comment by tommygonzaleza** [comment]
MOdify:
- [ ] Instruction (English and Spanish)
- [ ] Tests
- [ ] Solution

**Comment by UmiKami** [comment]
MOdify:

- [ ]  Instruction (English and Spanish)
- [ ]  Tests
- [ ]  Solution

**Comment by UmiKami** [comment]
Added correct solution, fixed the failing tests, and added documentation on the instructions.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/165
Hrs: <hrs>0.15</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.6</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.6</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.6</hrs>
