### ISSUE TITLE
Excercise Bug: 10-Create_a_new_function

### ISSUE THREAD

**Issue by Taylora36** [learnpack/learnpack#1251]
Describe the bug: Test instructions are wrong, expecting between 0 and 9 when it should be between 1 and 10.

**1. Exercise Name:** 10-Create_a_new_function

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by tommygonzaleza** [comment]
This is the code from the test, it is asking for a number between 1 and 10
```
expect(generateRandom()).toBeGreaterThanOrEqual(1);
expect(generateRandom()).toBeLessThanOrEqual(10);
```
