### ISSUE TITLE
Master Javascript - 153

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#1252]
Buenos días! @Arnaldo Pérez @Javier Montilva El ejercicio numero 153 de mastering java cuenta con un error. Para el test 5(primer console log en captura) toma en cuenta un texto rotado pero que le falta una letra, aún así el sistema lo toma como bueno. Al revisar el código de la “solución”, veo que solo revisa si estan todas las letras, mas no su frecuencia, por lo que para el segundo console log podría cambiar una letra o por una x y el codigo de la solución lo sigue tomando como bueno, pero en realidad ya no sería una versión rotada del texto

**Comment by tommygonzaleza** [comment]
Same issue as: https://github.com/learnpack/learnpack/issues/1248
