### ISSUE TITLE
Excercise Bug: 06.2-Loop-from-the-top

### ISSUE THREAD

**Issue by Pierina-Brito** [learnpack/learnpack#1254]
Describe the bug:

**1. Exercise Name:** 06.2-Loop-from-the-top

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by UmiKami** [comment]
No issues were found with the code. You can also check the solution file to see how it is done.

![Image](https://user-images.githubusercontent.com/60261375/214981073-89469d9c-9afc-4d93-bade-3dc5fbf2b762.png)

**Comment by UmiKami** [comment]
Hrs: <hrs>0.05</hrs>
