### ISSUE TITLE
Excercise Bug: 04.1-Combined-Rules

### ISSUE THREAD

**Issue by valepereyra** [learnpack/learnpack#1255]
Describe the bug:

**1. Exercise Name:** 04.1-Combined-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
No issues were found. Tests pass if instructions are followed.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.06</hrs>
