### ISSUE TITLE
Excercise Bug: 09-Beautify

### ISSUE THREAD

**Issue by moncherry369** [learnpack/learnpack#1256]
Describe the bug: Doesn't seem to register divs 1-6 in descending order. Strong tags where in all divs as expected and failed the test. 

**1. Exercise Name:** 09-Beautify

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

**Comment by UmiKami** [comment]
Make sure you don't have nested divs.

The code inside your body should look like this:
```html
<body>
	<div id="div1">
		<strong>The Menu</strong>
	</div>
	<div id="div2">
		<strong><i>The Content</i></strong>
	</div>
	<div id="div3">
		<strong><i>The Other Stuff</i></strong>
	</div>
	<div id="div4">
		<strong>Second Content</strong>
	</div>
	<div id="div5">
		<strong><i>Second Content</i></strong>
	</div>
	<div id="div6">
		<strong><i>The Extra Stuff</i></strong>
	</div>
</body>
``` 
Notice how the divs are adjacent to each other and where one div begins, the other starts. Make sure you are not missing an ending tag.


It is essential to remove redundant tags that serve no purpose. This will improve readability.

**Comment by UmiKami** [comment]
For instance, something like this would make the test fail: 

```html
<div>
    <div id="div6">
	<strong><i>The Extra Stuff</i></strong>
    </div>
</div>
```
The outer div here is redundant. It serves no purpose in this case and makes the code harder to follow.

**Comment by UmiKami** [comment]
At this point, I find no need to change the tests.

**Comment by UmiKami** [comment]
HRS: <hrs>0.08</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.08</hrs>
