### ISSUE TITLE
Excercise Bug: 04-build-the-website

### ISSUE THREAD

**Issue by EffySolorzano** [learnpack/learnpack#1263]
Describe the bug:

**1. Exercise Name:** 04-build-the-website

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

Test button is not constant. Website needs to be refreshed (if opened in browser) for the icon to show up. All exercises can be affected randomly

**Comment by tommygonzaleza** [comment]
Some exercises don't have test, that's why it's not showing
