### ISSUE TITLE
Excercise Bug: 10-Your-Own-Font

### ISSUE THREAD

**Issue by Doctorine06** [learnpack/learnpack#1264]
Describe the bug:

**1. Exercise Name:** 10-Your-Own-Font

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
No issues were found. If instructions are followed, the tests should pass.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.05</hrs>
