### ISSUE TITLE
Excercise Bug: 23-Parking-Lot

### ISSUE THREAD

**Issue by frederico2191** [learnpack/learnpack#1265]
Describe the bug:

I write console.log() to print out the result but the test still fails. According to the solution I am doing everything well.

**1. Exercise Name:** 23-Parking-Lot

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by tommygonzaleza** [comment]
Hello can you provide us the code you used, please
