### ISSUE TITLE
Excercise Bug: 00-Welcome

### ISSUE THREAD

**Issue by mpobletee** [learnpack/learnpack#1266]
Describe the bug:

## Misspell for ready ##

**1. Exercise Name:** 00-Welcome

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

![image](https://user-images.githubusercontent.com/89754972/210856949-b316d7f9-e1ec-4bdb-bcc3-5f4611d61c5e.png)

**Comment by tommygonzaleza** [comment]
Thanks! Problem solved
