### ISSUE TITLE
Excercises Bug: 08-planning & 09-the-first-test

### ISSUE THREAD

**Issue by emanuel-c4** [learnpack/learnpack#1267]
Describe the bug:

Hay un error de sintaxis en inglés y español con la palabra Yen, figura como Yan

| Ejercicio 08 | Ejercicio 09 |
| :--: | :--: |
| Inglés | Inglés |
| ![image](https://user-images.githubusercontent.com/36056518/210861161-40a7e2ed-1652-48e4-a08b-5ee23102ae89.png) | ![image](https://user-images.githubusercontent.com/36056518/210861937-801b7732-179e-41e2-b3d4-b5b62ae7b2dd.png) |
| Español | |
| ![image](https://user-images.githubusercontent.com/36056518/210861571-5ba082e3-6389-49f0-a291-3fde6182b337.png) | |

**1. Exercises Name:**  08-planning & 09-the-first-test

**2. Repository URL:** https://github.com/breatheco-de/exercise-unit-test-with-jest

**Comment by dsilva06** [comment]
https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/45
hrs: <hrs>0.3</hrs>

**Comment by emanuel-c4** [comment]
> [breatheco-de/exercise-unit-test-with-jest#45](https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/45) hrs: 0.3

Solo se ha cambiado el nombre que figura en la columna Input, quedando pendiente todos los demás "Yan" del README.md, además la versión en español del ejercicio 08 no se ha editado

**Comment by tommygonzaleza** [comment]
Si, falta modificar los nombres de la funcion, los tests, etc

**Comment by tommygonzaleza** [comment]
<hrs>0.3</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.3</hrs>
