### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Jano6elmar** [learnpack/learnpack#127]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

quiero cambiar el idioma de la explicacion del ejercicio pero no me lo permite
![image](https://user-images.githubusercontent.com/74441253/101673513-087d3380-3a36-11eb-801e-6c3a715fab62.png)

![image](https://user-images.githubusercontent.com/74441253/101673925-922d0100-3a36-11eb-88c4-0834584e606a.png)

## Other details: 
1. Exercises: 04.2-Apply-several-classes
2. Current URL: https://a61db7bf-d3ac-435c-8c5d-51d54382d4fe.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by ElviraQDP** [comment]
The bug has been fixed! Thank you for letting us know.
