### ISSUE TITLE
Excercise Bug: 08-planning

### ISSUE THREAD

**Issue by rebecabergottini** [learnpack/learnpack#1275]
Describe the bug:

**1. Exercise Name:** 08-planning
En la siguiente línea del ejercicio 8 hay un error ortográfico.
 
_Nuestro programa necesita las siguientes funciones para convertir fromDollarToYen, fromEuroToDollar y fromYanToPound._

fromYanToPound debería de ser fromYenToPound

**2. Repository URL:** https://github.com/breatheco-de/exercise-unit-test-with-jest

**Comment by UmiKami** [comment]
fixed grammar error. Arreglado.

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/47
Hrs: <hrs>0.03</hrs>

**Comment by tommygonzaleza** [comment]
Debes modificar el test y el ejercicio, no solo el readme
