### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by kparra7491** [learnpack/learnpack#128]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Image link is dead

## Other details: 
1. Exercises: 03.3-component-properties
2. Current URL: https://f2505d45-ff71-4790-9f2b-6153acdf4321.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by alesanchezr** [comment]
What link? I don't see an image on that exercise 
https://github.com/4GeeksAcademy/react-tutorial-exercises/tree/master/exercises/03.3-component-properties
