### ISSUE TITLE
Excercise Bug: 05-returning-json

### ISSUE THREAD

**Issue by marisofip** [learnpack/learnpack#1282]
Describe the bug:

**1. Exercise Name:** 05-returning-json

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

Al hacer la traducción en español , nos da esto
  # puedes convertir esa variable en un string json así
    json_text = flask.jsonify(some_data)

que obviamente si se agrega ese flask que no va alli

**Comment by tommygonzaleza** [comment]
Gracias! Resuelto
