### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by EleazarMelendez** [learnpack/learnpack#1290]
Describe the bug:

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

The exercise text states: "Set the background-color of the second li of the ol to green (don't use the #id selector or .class selector)."

Developer uses inline "style" tag to change background color:

		<ol>
			<li>You are able to complete the exercises by yourself.</li>
			<li style="background-color: green">You understand what the teacher is talking about</li>
			<li>Your are able to have conversations about the topic</li>
		</ol>

Test fails the code. Terminal output Incorrectly demands " 
![Exercise 7 bug - CSS tutorial](https://user-images.githubusercontent.com/122404789/213572285-3c8f4cf1-5b35-4abe-b45f-160ef44ef161.png)
(fail) 1. The ul second element background should be green."

**Comment by UmiKami** [comment]
You should not be using inline styles. It is usually considered bad practice. The tests only consider the styles from the CSS file.

As to why it is consider bad practice to do inline styling generally: 

1. Decreased Maintainability: When CSS styles are inline, it makes it difficult to maintain the code as the same styles have to be copied across multiple pages or elements. This can lead to errors and inconsistencies in the codebase. 

2. Increased Page Size: Inline styles increase the page size, which can affect page load times and, ultimately, user experience. When styles are added inline, they are added to every element that needs them, even if those styles are not used anywhere else on the page.

3. Difficulty with Style Overrides: If the same style is defined both inline and in a separate CSS file, the inline style will override the CSS file, which can make it difficult to control the styling of a website.

4. Lack of Reusability: Inline styles are not reusable. If a style is defined inline, it cannot be used on other elements or pages without being copied and pasted manually.

5. Poor Separation of Concerns: Inline styles mix presentation and content, making it difficult to separate the two concerns. This can lead to code that is difficult to read and maintain.

**Comment by UmiKami** [comment]
Changes; 
- Added foot note on both READMEs to clarify that HTML file should not be modified or touched.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/83
Hrs: <hrs>0.13</hrs>
