### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by SalZeus** [learnpack/learnpack#1294]
Describe the bug: 
     ✓ (done) 0. The ul li color has to be red using !important
     x (fail) 1. The ul second element background should be green
     ✓ (done) 2. The odd rows of the table should have yellow background
     ✓ (done) 3. Write all your rules above the existing code
     ✓ (done) 4. You should not change the existing head tag elements 
feedback on line 2 should be "ol" and not "ul"

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
Fixed typo in test 2.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/83
Hrs: <hrs>0.05</hrs>
