### ISSUE TITLE
Excercise Bug: 04.1-Combined-Rules

### ISSUE THREAD

**Issue by Carolina-hora** [learnpack/learnpack#1295]
Describe the bug:

**1. Exercise Name:** 04.1-Combined-Rules
When I press the reset button, the exercise does not restart

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Hello! We are still working on adding that functionality to learnpack, it will be added in the next release
