### ISSUE TITLE
Excercise Bug: 08-Function-parameters

### ISSUE THREAD

**Issue by Julian0816** [learnpack/learnpack#1296]
Describe the bug:

**1. Exercise Name:** 08-Function-parameters

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

It is not a bug, just a typo
"Bob is a 23-year-old" male instead of "Bob is a 23 years old male"

**Comment by tommygonzaleza** [comment]
Hello! thanks!
