### ISSUE TITLE
Excercise Bug: 07-Buttons-Alert-And-Table

### ISSUE THREAD

**Issue by EleazarMelendez** [learnpack/learnpack#1298]
Describe the bug:

**1. Exercise Name:** 07-Buttons-Alert-And-Table

**2. Repository URL:** https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

The auto-grader will fail this exercise if any inline CSS is used for the styling. 

However, in order to replicate the yellow alert as it appears on the exercise (including with the round button), an SVG sprite MUST be added to the HTML code, as explained here (https://getbootstrap.com/docs/5.0/components/alerts/#icons) One of the attributes of the sprite by default includes inline CSS.

**Comment by tommygonzaleza** [comment]
Change the screenshot to exclude the icon, we prefer to still preventing users from using inline css @UmiKami

**Comment by UmiKami** [comment]
I updated the screenshot with the removed icon.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/44
Hrs: <hrs>0.30</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.3</hrs>
