### ISSUE TITLE
[Suggestion]: Excercise Bug: 02.1-Background

### ISSUE THREAD

**Issue by omiras** [learnpack/learnpack#1299]
Describe the bug:

**1. Exercise Name:** 02.1-Background

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

I would change step 5 of Instructions, I don't think there's a point in using _inherit_ value fot background-repeat rule. IMHO student will be more rewarded if they learn what's the default value for the background-repeat rule. Notice that also tests must be changed.

`5. Remove the background-repeat rule and Preview the exercise again. Now the background image will repeat over the x axis and y axis
`

**Comment by UmiKami** [comment]
Suggestion applied. Now using `repeat` instead of `inherit` for `background-repeat`
