### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by guillermosequera** [learnpack/learnpack#13]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

In the following exercise, we are asked to remove the space between the <divs>, but when we put the html tags together and compile them, they separate and leave the spaces again. 
This is what the code should look like.

`<body>
		<div>
			<div id="sectionA">A</div><div id="sectionB">B</div><div id="sectionC">C</div>
		</div>
	</body>`

but when compiling it gets like this:

`<div>
			<div id="sectionA">A</div>
			<div id="sectionB">B</div>
			<div id="sectionC">C</div>
</div>`

## Other details: 
1. Exercises: 08-Split-Screen-in-three
2. Current URL: https://abc57185-a749-4808-94a8-9529dbb4d5e5.ws-us02.gitpod.io
3. Repository: uknown

**Comment by tommygonzaleza** [comment]
You just need to add `display: flex;` to the parent div
