### ISSUE TITLE
Excercise Bug: 01.2-Your-First-Style

### ISSUE THREAD

**Issue by user1fernan** [learnpack/learnpack#1302]
Describe the bug:

A small thing, not quite a bug (sorry), the code says in green >/* change this style to blue */<, but the exercise says to change it to yellow

**1. Exercise Name:** 01.2-Your-First-Style

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by dsilva06** [comment]
hrs: <hrs>0.3</hrs>
