### ISSUE TITLE
Excercise Bug: 08-relative-vs-absolute-path

### ISSUE THREAD

**Issue by Pazdesarrolladora** [learnpack/learnpack#1306]
Describe the bug:

**1. Exercise Name:** 08-relative-vs-absolute-path

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

cada vez que intento copiar el url de la imagen para poder crear la ruta absoluta me aparece que la imagen esta rota

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/80
hrs: <hrs>0.3</hrs>

**Comment by dsilva06** [comment]
ahi se encuentra el link que se debe utilizar para refeljar la imagen

**Comment by tommygonzaleza** [comment]
Ese link varia segun el ambiente en el que este trabajando cada uno, en este caso al funcionar con esa url parece que el problema es que el estudiante no puso la ruta absoluta correcta
