### ISSUE TITLE
Excercise Bug: 14-save-on-github

### ISSUE THREAD

**Issue by Aedv90** [learnpack/learnpack#1316]
Describe the bug:

**1. Exercise Name:** 14-save-on-github

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

**Comment by Aedv90** [comment]
El link da error

 "Page Not Found

The page you're looking for does not seem to exist"

**Comment by tommygonzaleza** [comment]
Cual link te esta dando error? Yo estuve probando todos los demas y me funcionaban bien
