### ISSUE TITLE
Excercise Bug: 15-Max-integer-from-array

### ISSUE THREAD

**Issue by PRiveraA** [learnpack/learnpack#1321]
Describe the bug:

**1. Exercise Name:** 15-Max-integer-from-array

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

Both conditions are met, but test result is fail.
https://gitpod.io#snapshot/e10bc71e-6a7c-4b0a-abda-6df20a2b8a2b

**Comment by dsilva06** [comment]
https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/121
hrs: <hrs>0.4</hrs>

**Comment by dsilva06** [comment]
all tests passed perfectly, try double-checking your loops
