### ISSUE TITLE
Excercise Bug: 14-Divide-and-Conquer

### ISSUE THREAD

**Issue by Carolina-hora** [learnpack/learnpack#1322]
Describe the bug:

**1. Exercise Name:** 14-Divide-and-Conquer

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

let list_of_numbers = [4, 80, 85, 59, 37,25, 5, 64, 66,	81,20, 64, 41, 22, 76,76, 55, 96, 2, 68];

//So I have this code:
function mergeTwoList(){
    let odd = [];
    let even = [];
    
    list_of_numbers.forEach((item)=> {
        if (item%2===0) even.push(item);
        else odd.push(item);
    });
    
    return odd.concat(even);
}

let mergedArray = mergeTwoList();
console.log(mergedArray);

//When I build it, it gives this result, which seems right to me...
Building exercise 14-Divide-and-Conquer with node...
[
  85, 59, 37, 25,  5, 81, 41,
  55,  4, 80, 64, 66, 20, 64,
  22, 76, 76, 96,  2, 68
]

// But when I test it, it fails test 4 and 5.
 ✓ (done) 0. Function mergeTwoList should exist
     ✓ (done) 1. You have to use a "for" loop
     ✓ (done) 2. You have to use a "for" loop
     ✓ (done) 3. Function mergeTwoList must return an array
     x (fail) 4. The returned array must contain inside all the odd items first
     x (fail) 5. The returned array must contain inside all the even items at the end

**Comment by UmiKami** [comment]
The reason why the tests are not passing is because the function mergeTwoList is being tested with multiple arrays. These arrays are being passed as a parameter to the function. In your case, you are not accepting any parameters. 

Look at the solution:

let list_of_numbers = [4, 80, 85, 59, 37,25, 5, 64, 66,	81,20, 64, 41, 22, 76,76, 55, 96, 2, 68];

```javascript
// your code here
function mergeTwoList(array){
    let odd = []
    let even = []

    for (let i = 0; i < array.length; i++) {
        array[i] % 2 == 0 ? even.push(array[i]) : odd.push(array[i])
    }

    return odd.concat(even)
}
```

**Comment by UmiKami** [comment]
No issues found.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.10</hrs>
