### ISSUE TITLE
Excercise Bug: 079-joinThreeArrays

### ISSUE THREAD

**Issue by louitron** [learnpack/learnpack#1324]
Describe the bug:

**1. Exercise Name:** 079-joinThreeArrays

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

Tried the exercise with the following 2 solutions, which both return the expected output but were denied by the test.

Solution 1: 

function joinThreeArrays(arr1, arr2, arr3) {
  // your code here
  let newArray = [];
  newArray = newArray.concat(arr1, arr2, arr3)
  return newArray;
}

Solution 2: 

function joinThreeArrays(arr1, arr2, arr3) {
  // your code here
  let newArray = [...arr1, ...arr2, ...arr3 ];
  return newArray;
}

**Comment by UmiKami** [comment]
Tried all solutions you provided, and they all worked for me and the tests passed successfully. Tried other alternative solutions and they also passed.

Make sure you do not have any other code other than the solution code, aka, the function and the code inside of it. Nothing else outside of it including, console.log, or a function call.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.12</hrs>
