### ISSUE TITLE
Excercise Bug: 11-Dynamic-HTML-String

### ISSUE THREAD

**Issue by Hedonista17** [learnpack/learnpack#1326]
Describe the bug:

**1. Exercise Name:** 11-Dynamic-HTML-String
Segun la foto del ejercicio, lo que se espera que se imprima en la web es lo siguiente :
let myString = "<p>Hello!</p> <strong>My friend</strong>,we are in the year"+" "+ new Date().getFullYear() ;
document.write(myString);
![image](https://user-images.githubusercontent.com/120684452/222016895-ad86f202-a2e4-40d1-baf7-f968bda27059.png)

Sin embargo, cuando quieres testear el ejercicio te dice que es incorrecto y que lo que se espera unicamente es : 
let myString = "<p>Hello!</p> <strong>My friend</strong>,"+" "+ new Date().getFullYear() ;
document.write(myString);

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by UmiKami** [comment]
El regex esperaba: `let myString = "<p>Hello!</p> <strong>My friend</strong>, " + new Date().getFullYear();`

Ahora deberia funcionar con: `let myString = "<p>Hello!</p> <strong>My friend</strong>, we are in the year" + new Date().getFullYear();`

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/64
Hrs: <hrs>0.13</hrs>
