### ISSUE TITLE
Excercise Bug: 007-hours_and_minutes

### ISSUE THREAD

**Issue by romanconstantin1** [learnpack/learnpack#1329]
Describe the bug:

**1. Exercise Name:** 007-hours_and_minutes

**2. Repository URL:** https://github.com/4GeeksAcademy/master-python-programming-exercises

Error message:

>       assert app.hours_minutes(7320) == (2, 2)
E       assert (2, 122) == (2, 2)
E         At index 1 diff: 122 != 2
E         Use -v to get the full diff

the test has an incorrect check for the minutes value; 7320 seconds is not 2 minutes

**Comment by UmiKami** [comment]
It is two minutes:

7320 / 60 = 122 minutes

122 / 60 = 2.03 hours

122 % 60 = 2 minutes OR [0.03 hours is 2 minutes ](https://uh.edu/office-of-finance/payroll/time_conversion_chart_minutes_to_decimalhours.pdf)

Final answer: 2 hours and 2 minutes

**Comment by UmiKami** [comment]
No changes are needed.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>
