### ISSUE TITLE
Excercise Bug: 06.3-Loop-adding-two

### ISSUE THREAD

**Issue by HusseinSerhan** [learnpack/learnpack#1330]
Describe the bug: There is an issue with the test. Even after pasting the solution, if says that you are not using a "for" loop.

**1. Exercise Name:** 06.3-Loop-adding-two

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by UmiKami** [comment]
The test was failing before the dependencies being used were not being imported. Fixed that.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/122
Hrs: <hrs>0.10</hrs>
