### ISSUE TITLE
Excercise Bug: 21-Russian_Roulette

### ISSUE THREAD

**Issue by michelcub** [learnpack/learnpack#1331]
Describe the bug:

**1. Exercise Name:** 21-Russian_Roulette

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial
hay un problema con el parametro bulletPosition no esta declarado, cuando lo declaro y lo igualo a spinChamber(), ya funciona el juego pero a la hora de hacer el test no pasa el test

**Comment by UmiKami** [comment]
No es un problema, el parametro si está declarado.



![Image](https://user-images.githubusercontent.com/60261375/228959908-fb27e839-f78a-4b00-991a-406de94ef1f8.png)



Está es la solucion:

```js
// firePosition will be the position in which the gun will fire.
let firePosition = 1;

// The output of spinChamber will be a number and it can be passed as a parameter to the fireGun function.
const spinChamber = () => {
    let chamberPosition = Math.floor((Math.random() * 6) + 1);
    return chamberPosition;
};

// Remove the // below and complete the commented lines
const fireGun = (bulletPosition) => {
    if (bulletPosition === firePosition) {
        return ("You're dead!");
    }
    else return ("Keep playing!");
};

console.log(fireGun(spinChamber()));
```

Tambien la puedes encontrar en el archivo llamado "solution.hide.js"

Puedes comparar to solucion con la de ese archivo para ver que tienes diferente y que puede estar fallando.

**Comment by UmiKami** [comment]
No changers are needed.
Hrs: <hrs>0.07</hrs>
