### ISSUE TITLE
Excercise Bug: 05-Specificity

### ISSUE THREAD

**Issue by JOSELAGOSG** [learnpack/learnpack#1332]
Describe the bug:

**1. Exercise Name:** 05-Specificity

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

BUG: 2nd test "You should not delete or edit the existing code" always failing even without appending new lines at the bottom.

**Comment by UmiKami** [comment]
Test was not checking for the correct selector on the default CSS code. Fixed.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/98
Hrs: <hrs>0.07</hrs>
