### ISSUE TITLE
Excercise Bug: 06.3-Loop-adding-two

### ISSUE THREAD

**Issue by manu4970** [learnpack/learnpack#1335]
Describe the bug:

When i run the test isnt detecting the for loop

**1. Exercise Name:** 06.3-Loop-adding-two

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by tommygonzaleza** [comment]
The bug was already reported here: https://github.com/learnpack/learnpack/issues/1330
