### ISSUE TITLE
Excercise Bug: 06-Jumbotron-And-Three-Boxes

### ISSUE THREAD

**Issue by JavierGuerreroR** [learnpack/learnpack#1336]
Describe the bug:

**1. Exercise Name:** 06-Jumbotron-And-Three-Boxes

**2. Repository URL:** https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

I have done as asked and get a fail still for things that are there

     ✓ (done) 0. You should not change or delete the existing elements in the head tag
     ✓ (done) 1. You should not use the style tag.
     ✓ (done) 2. Do not use any inline styles, just use the bootstrap classes for styling
     ✓ (done) 3. The body should contain a div tag with the class container-fluid
     x (fail) 4. The first element of the first section should be an H1 tag
     ✓ (done) 5. The second element of the first section should be a P tag
     x (fail) 6. The third element of the first section should be a button tag with a blue button class
     x (fail) 7. The second sections should contain three columns of the same width
     x (fail) 8. The 3 columns should contain an H2, a p and a button 

		<div class="container-fluid">
			<div class="bg-light mt-2 mb-2">
				<h1>Hello, World!</h1>
				<p>
					I`m excited to use bootstrap because now i don't have to fight with CSS anymore, I made this layout in 20 minutes and befor
					bootstrap it took me 2hrs easy!
				</p>
				<button type="button" class="btn btn-primary">Primary</button>
			</div>
			<div class="row">
				<div class="col col-4 gap-3 mt-2">
					<h2>Heading</h2>
					<p>
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo obcaecati eligendi, pariatur iusto reprehenderit placeat
						nobis, sequi suscipit possimus, accusantium eaque? Commodi, ullam. Mollitia magnam minima ipsa? Laborum, assumenda iusto!
					</p>
					<button type="button" class="btn btn-light">View Details</button>
				</div>
				<div class="col col-4 gap-3 mt-2">
					<h2>Heading</h2>
					<p>
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo obcaecati eligendi, pariatur iusto reprehenderit placeat
						nobis, sequi suscipit possimus, accusantium eaque? Commodi, ullam. Mollitia magnam minima ipsa? Laborum, assumenda iusto!
					</p>
					<button type="button" class="btn btn-light">View Details</button>
				</div>
				<div class="col col-4 gap-3 mt-2">
					<h2>Heading</h2>
					<p>
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo obcaecati eligendi, pariatur iusto reprehenderit placeat
						nobis, sequi suscipit possimus, accusantium eaque? Commodi, ullam. Mollitia magnam minima ipsa? Laborum, assumenda iusto!
					</p>
					<button type="button" class="btn btn-light">View Details</button>
				</div>
			</div>
		</div>

**Comment by UmiKami** [comment]
No PR required.
Hrs: <hrs>0.08</hrs>
