### ISSUE TITLE
Excercise Bug: 06.3-Loop-adding-two

### ISSUE THREAD

**Issue by DrowLink** [learnpack/learnpack#1338]
Describe the bug:

Segundo test de que debe existir un for, esta fallando.  

`
let mySampleArray = [3423,5,4,47889,654,8,867543,23,48,56432,55,23,25,12];

for(let i = 0; i<mySampleArray.length; i = i + 2){
	console.log(mySampleArray[i]) 
}
`

**1. Exercise Name:** 06.3-Loop-adding-two

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by UmiKami** [comment]
No fui capaz the replicarlo. Use la mismo solucion proveida por @DrowLink y los tests pasaron.

**Comment by UmiKami** [comment]
No changes needed.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.05</hrs>
