### ISSUE TITLE
Excercise Bug: 05-Specificity

### ISSUE THREAD

**Issue by Paola596** [learnpack/learnpack#1341]
Describe the bug:

**1. Exercise Name:** 05-Specificity

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

 Hagas lo que hagas estos ejercicios consideran que esta bien si compila, así el objetivo no haya sido logrado.

**Comment by UmiKami** [comment]
Fixed on #1332
