### ISSUE TITLE
Excercise Bug: 09-Function-parameters

### ISSUE THREAD

**Issue by athousanddetails** [learnpack/learnpack#1348]
Describe the bug:

It returns " x (fail) 0. The function render_person must accept 5 parameters" when indeed render_person has 5 arguments. 

**1. Exercise Name:** 09-Function-parameters

**2. Repository URL:** https://github.com/4GeeksAcademy/python-functions-programming-exercises

**Comment by UmiKami** [comment]
Not bug, that means that your function definition should accept at least five parameters. 

Take a look at the solution: 

```python
# Your code goes here:
def render_person(name, birthdate, eye_color, age, sex): // accepting five parameters
    return name +" is a "+ str(age) +" years old " + sex +" born in " + birthdate + " with "+eye_color +" eyes"


# Do not edit below this line
print(render_person('Bob', '05/22/1983', 'green', 23, 'male')) // sending five arguments
```

**Comment by UmiKami** [comment]
Added solution file

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/44
Hrs: <hrs>0.17</hrs>
