### ISSUE TITLE
Excercise Bug: 03-first-flask-app

### ISSUE THREAD

**Issue by achapdesign** [learnpack/learnpack#1349]
Describe the bug:
Ive followed the instructions and my code is identical to the solution however it somehow doesnt pass the test

**1. Exercise Name:** 03-first-flask-app

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

**Comment by UmiKami** [comment]
I was not able to replicate the issue. As per the instructions, make sure you have a folder called `src` in the root of your project, and that the app.py is inside that folder, like this: 


![Image](https://user-images.githubusercontent.com/60261375/230487918-7f205bd2-2c14-4697-bcd3-93d201dd561a.png)

**Comment by UmiKami** [comment]
Hrs: <hrs>0.10</hrs>

**Comment by omiras** [comment]
@achapdesign Thanks for reporting. Attach always the steps you followed plus a screenshot to help maintainers to figure out the problem

**Platform**: Codespaces

**Steps to reproduce**
1. Follow allong the interactive tutorial until you reach this exercise
2. All the previous tests have been passed
3. The test does not pass even tough a src/app.py exists and the code is identical to the solution

It seems that Flask module is not reconignez in the environment:
![image](https://user-images.githubusercontent.com/3286458/236666506-b07dfb4f-684b-4591-a797-c8c9a66aeb59.png)

**Comment by ernestomedinam** [comment]
Hey, in the meantime maybe you could try installing flask globally `pip3 install flask` to be able to run the tests 🙃

**Comment by tommygonzaleza** [comment]
Hello! There was a problem related to the dependencies, our learnpack-python compiler was looking for the dependencies in a wrong path. It was fixed already
