### ISSUE TITLE
Excercise Bug: 04-Class-Selector

### ISSUE THREAD

**Issue by Yvv1214** [learnpack/learnpack#1350]
Describe the bug:

**1. Exercise Name:** 04-Class-Selector

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

 ✓ (done) 0. You should not change the existing head tag elements
     ✓ (done) 1. The body tag should not contains any inline style
     ✓ (done) 2. There should be two p tags
     x (fail) 3. Both p tags should have a class name 'b-blue' without the quotation marks 

Ive done my own example and it works but the ones for the assignment doesnt

                <p class=".b-blue">Hello!</p>
		<p class=".b-blue">World!</p>
		<p class="RED">the red one works but the other ones dont</p>
		<p class="blue">And the blue one too. It works</p>

.b-blue {
	background: blue;
}

.RED {
	color: red;
}

.blue {
	color: blue;
}

![Screenshot (67)](https://user-images.githubusercontent.com/39809411/227833863-ad6f67ba-da91-473e-9c63-38f33a16071f.png)

**Comment by Yvv1214** [comment]
ive done it without quotation marks and still wrong

**Comment by UmiKami** [comment]
Hi, I am sorry for the confusion. The name of the class is `b-blue` without the dot in front of it. The reason why it is not working for you is that on the HTML, you have the dot in front the name of the class.

Remember to always check the solution file if you get stuck.


![Image](https://user-images.githubusercontent.com/60261375/230485726-fad29f48-c8ac-4be9-a177-7ef17d2f0dbf.png)

**Comment by UmiKami** [comment]
Changes: Updated instructions for clarity.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/106
Hrs: <hrs>0.10</hrs>
