### ISSUE TITLE
Excercise Bug: 003-isOldEnoughToVote

### ISSUE THREAD

**Issue by Rodrigou0** [learnpack/learnpack#1352]
Describe the bug:

**1. Exercise Name:** 003-isOldEnoughToVote

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by UmiKami** [comment]
Solution file was wrong. Voting age in the US is 18 not 21.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/168
Hrs: <hrs>0.07</hrs>
