### ISSUE TITLE
Excercise Bug: 08-Function-parameters

### ISSUE THREAD

**Issue by JavierGuerreroR** [learnpack/learnpack#1353]
Describe the bug:  get help button loads forever, never actually does anything

**1. Exercise Name:** 08-Function-parameters

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

**Comment by UmiKami** [comment]
@tommygonzaleza this has to do with the get help button on the learnpack GUI 



![Image](https://user-images.githubusercontent.com/60261375/230492232-8d3058eb-a2b1-4bda-8712-7ff3332c3bb1.png)


it loads forever

**Comment by tommygonzaleza** [comment]
Already reported in another issue, we are working to fix it
