### ISSUE TITLE
Excercise Bug: 04-Class-Selector

### ISSUE THREAD

**Issue by TaniaMJ10** [learnpack/learnpack#1356]
Describe the bug:

**1. Exercise Name:** 04-Class-Selector

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
No issues were found. Please refer to the solution.hide.html and compare it to your solution. Alternatively, you can ask questions on the public support channel in slack.

Here's the correct solution as well:

```html
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./styles.css" />
		<title>04 Class selector</title>
	</head>

	<body>
		<p class="b-blue">Hello!</p>
		<p class="b-blue">World!</p>
	</body>
</html>
```

**Comment by UmiKami** [comment]
Hrs: <hrs>0.09</hrs>
