### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by Soniv-E** [learnpack/learnpack#1364]
Describe the bug:   x (fail) 3. Write all your rules above the existing code

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
Read the instructions carefully.

![Image](https://user-images.githubusercontent.com/60261375/236709710-259115de-2444-4ede-8b35-265d49bbd613.png)

**Comment by UmiKami** [comment]
No issues found.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>
