### ISSUE TITLE
Excercise Bug: 05-Specificity

### ISSUE THREAD

**Issue by Soniv-E** [learnpack/learnpack#1365]
Describe the bug:    x (fail) 1. You should not delete or edit the existing code

**1. Exercise Name:** 05-Specificity

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
As the test says, you should not edit anything above the line

![Image](https://user-images.githubusercontent.com/60261375/236709364-d5e1d99a-37ce-46a9-bb79-494a356fde16.png)


This is how the solution should look like:


![Image](https://user-images.githubusercontent.com/60261375/236709468-f88626b9-a875-4543-ad99-4146d867bafd.png)

**Comment by UmiKami** [comment]
No issues found.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.10</hrs>
