### ISSUE TITLE
Excercise Bug: 03.3-your-first-route

### ISSUE THREAD

**Issue by yonatancrespo** [learnpack/learnpack#1367]
Describe the bug: I did  everything correctly and it still says its wrong and i cant move on to the next steps 

**1. Exercise Name:** 03.3-your-first-route

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

**Comment by UmiKami** [comment]
I couldn't get replicate the issue. Test passed. 

Here's how my solution looks: 



![Image](https://user-images.githubusercontent.com/60261375/236711217-1b581e2d-4a6d-4dd5-8ecd-9cee6eac64a6.png)



Make sure the application is running like signaled by the arrow in the image above.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>
