### ISSUE TITLE
Excercise Bug: 134-convertScoreToGradeWithPlus

### ISSUE THREAD

**Issue by ValentinFrAr** [learnpack/learnpack#1376]
Describe the bug:

**1. Exercise Name:** 134-convertScoreToGradeWithPlus

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises
function convertScoreToGradeWithPlusAndMinus(score) {
    // your code here
    if (score >= 100 || score <= 0) return 'INVALID SCORE';
    else {
      if (score >= 90) {
        if (score >= 90 && score <= 92) return 'A+';
        if (score >= 98 && score <= 99) return 'A-';
        return 'A';
      }
      if (score >= 80) {
        if (score >= 80 && score <= 82) return 'B+';
        if (score >= 88 && score <= 89) return 'B-';
        return 'B';
      }
      if (score >= 70) {
        if (score >= 70 && score <= 72) return 'C+';
        if (score >= 78 && score <= 79) return 'C-';
        return 'C';
      }
      if (score >= 60) {
        if (score >= 60 && score <= 62) return 'D+';
        if (score >= 68 && score <= 69) return 'D-';
        return 'D';
      }
      if (score >= 0) {
        return 'F';
      }
    }

this code should work normally

**Comment by UmiKami** [comment]
The code works, but the output/answer is wrong.

A score of 91 should be A- but your code outputs A+:

```js
 if (score >= 90) {
        if (score >= 90 && score <= 92) return 'A+';
        if (score >= 98 && score <= 99) return 'A-';
        return 'A';
    }
```

Check your logic.

**Comment by UmiKami** [comment]
No issues were found.

**Comment by UmiKami** [comment]
Hrs: <hrs> 0.08 </hrs>
