### ISSUE TITLE
Excercise Bug: 005-getProperty

### ISSUE THREAD

**Issue by ChrisSasias** [learnpack/learnpack#1379]
Describe the bug:

**1. Exercise Name:** 005-getProperty

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

constantemente me muestra el mensaje 
🥺 Whoops! 🔥💻 Woops! There has been an internal error Try troubleshooting with these steps

trato de usar el famoso "learnpack start", muchas veces funciona otras veces no, 

me pasa cunado ejecuto los practice tanto en codespace como antiguamente me paso con gitpod, 

es incomodo y molesto generalmente sucede cuando presiono "test" pero otras veces sucede de la nada

**Comment by tommygonzaleza** [comment]
Eso suele pasar por algun error de sintaxis en el codigo al momento de correr el test
