### ISSUE TITLE
Excercise Bug: 01-Hello_World

### ISSUE THREAD

**Issue by jaac14** [learnpack/learnpack#1380]
Describe the bug:

**1. Exercise Name:** 01-Hello_World

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial
[](url)
![image](https://user-images.githubusercontent.com/124366885/232797440-4600cf5f-e8ba-4a53-a88d-99925bffc9d7.png)
los test no estan encontrando las resouestas

**Comment by tommygonzaleza** [comment]
Hola, quizas falto instalar el plugin de learnpack-node, recuerdas si lo hiciste?
