### ISSUE TITLE
Excercise Bug: 02-Display-none

### ISSUE THREAD

**Issue by Edulopesp** [learnpack/learnpack#1384]
Describe the bug:

**1. Exercise Name:** 02-Display-none

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

Every time a try to run the test or build it crashes and I have to get reseted somehow, even if I close and then do learnpack start it says "learpack/plugin not found" or something like that. If I refresh the page, I lose everything and can't start again. If I close it and then try to open it by continuing the exercise, it can't be opened, so I start again and I gotta remember that I can't build or test, but I need to test to go to the next exercise...

**Comment by tommygonzaleza** [comment]
this problem has been fixed already, sorry for the inconvenience
