### ISSUE TITLE
Excercise Bug: 01-alert-on-click

### ISSUE THREAD

**Issue by rubengargu** [learnpack/learnpack#1386]
Describe the bug:

**1. Exercise Name:** 01-alert-on-click

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises

Falta el boton test

**Comment by UmiKami** [comment]
@tommygonzaleza Ninguno de los ejercicios en este [repositiorio ](https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises)tienen tests. ¿Debería añadirlos?

**Comment by tommygonzaleza** [comment]
Este tutorial no tiene tests, por eso no aparece el checkmark
