### ISSUE TITLE
***Test button is missing in the whole lesson****Excercise Bug: 02-on-click-Hello-World

### ISSUE THREAD

**Issue by Jrealmorillo** [learnpack/learnpack#1387]
Describe the bug:

Test button is missing in the whole lesson, not only in this exercise. Therefore it is difficult for user to make sure whether code is correct or not.

**1. Exercise Name:** 02-on-click-Hello-World

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises

**Comment by tommygonzaleza** [comment]
These exercises don't have automated tests, that's why the button is not showing up. We are working to build the tests for these exercises and they will be ready soon
