### ISSUE TITLE
Excercise Bug: 03-Bootstrap-Grid

### ISSUE THREAD

**Issue by pedroalvaradoh** [learnpack/learnpack#1388]
Describe the bug: the web preview is not opening in browser it says something like "can't get preview"

**1. Exercise Name:** 03-Bootstrap-Grid

**2. Repository URL:** https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

**Comment by tommygonzaleza** [comment]
Hello! Do you have the workspace where that happened? Or can you help us replicate the issue please. I'm going to close it until I get a response
