### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by angelormz** [learnpack/learnpack#1389]
Describe the bug:

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

En este ejercicio se solicita en las instrucciones del punto 3:
Haz que las filas impares de la tabla tengan fondo amarillo usando `tr:nth-child`

Uso el atributo `even` que es para seleccionar elementos impares y me lo marca como erróneo y en la solución lo tienen como `odd` que es para elementos pares, para que verifiquen correctamente las instrucciones.

**Comment by tommygonzaleza** [comment]
[even](https://www.linguee.es/ingles-espanol/traduccion/even+number.html#:~:text=n%C3%BAmero%20par%20m,para%20jugar%20a%20este%20juego.) es para pares, odd es para impares, por eso te estaba fallando el test
