### ISSUE TITLE
Excercise Bug: 02-website-structure

### ISSUE THREAD

**Issue by Rossco1991** [learnpack/learnpack#1390]
![image_2023-04-27_174306445](https://user-images.githubusercontent.com/130109458/234997571-aff3c6c0-08a8-42c8-b4b6-04cc453fedc3.png)
Describe the bug:
Solution as shown shows error when attempting to build and test

**1. Exercise Name:** 02-website-structure

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
It looks like the problem is that you were modifying the solution value
