### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by Rossco1991** [learnpack/learnpack#1391]
![VerySpecific](https://user-images.githubusercontent.com/130109458/235278918-eef0bb17-453d-48a6-8a75-259229337115.png)

Describe the bug:
Code is written identical to the solution. When testing result is the same as the example as shown in learn pack and compiles the same way.
**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
The code isn't really 100% identical to the solution, `green `is written with capital G, for this reason the test is failing. This is a bug on the test side and will be fixed.

**Comment by UmiKami** [comment]
Tests made case insensitive, solution remains correct.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/121
Hrs: <hrs>0.12</hrs>
