### ISSUE TITLE
Revisar detalladamente cada ejercicio del tutorial de pandas

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1393]
Las instrucciones no piden lo mismo que los tests, es importante que esten 100% sincronizados

Este es el [repositorio](https://github.com/4GeeksAcademy/python-pandas-tutorial/tree/main)

**Comment by UmiKami** [comment]
- [ ] 2.2 updated > read me to specify variable name | print test to make it flexible against spaces
- [ ] 4 updated print test to make it flexible against spaces
- [ ] 4.1 added test to prevent the student from hard-coding the solution | asked student to print result to terminal
- [ ] 4.2 asked student to print result to terminal | updated print test to make it flexible against spaces
- [ ] 5 updated print test to make it flexible against spaces
- [ ] 5.1 fixed expected result in English instructions | added test to check if user is using dict
- [ ] 5.2 added missing step on the instructions | checked for hardcoded values
- [ ] 5.3 added missing step on / clarified the instructions | added test to check if right file is being read
- [ ] 5.4 added missing step on / clarified the instructions | added test to check if right file is being read
- [ ] 5.5 Same fix as previous two exercises
- [ ] 5.6 Same fix as previous exercise | check for loc function usage
- [ ] 5.7 Same fix as previous exercise | hardcode check
- [ ] 6 fixed wrong path in step 1 | fixed solution to check for first 5 | checks head function usage
- [ ] 6.1 Same fix as previous
- [ ] 6.2 Same fix as previous

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/14
Hrs: <hrs>2.48</hrs>

**Comment by UmiKami** [comment]
Note to self: Use `in` when checking for string equality instead of `==` to make it more flexible

**Comment by UmiKami** [comment]
Applied what I mentioned in my previous message

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/16
Hrs: <hrs>0.18</hrs>
