### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Diego-EC** [learnpack/learnpack#14]
# What was the expected behavior?

The link of the image is broken. It is not a big problem, I have used the link of the image of the previous exercise; I just wanted to report the bug.

## Other details: 
1. Exercises: 05-Float-example
2. Current URL: https://be0cfab3-d9fd-4d96-841e-d0f2b47d80c8.ws-eu01.gitpod.io
3. Repository: uknown

**Comment by ElviraQDP** [comment]
The link is up and running!
