### ISSUE TITLE
Excercise Bug: 04.1-Combined-Rules 

### ISSUE THREAD

**Issue by shaglot** [learnpack/learnpack#1401]
Describe the bug:

**1. Exercise Name:** 04.1-Combined-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Can´t reset the exercise

**Comment by tommygonzaleza** [comment]
Hello! Currently the reset functionality is only resetting the entry file (In this case the HTML) we are working to allow it to reset all the files
