### ISSUE TITLE
Excercise Bug: 08-Calling_your_first_function

### ISSUE THREAD

**Issue by DreaQuila** [learnpack/learnpack#1405]
Describe the bug:

**1. Exercise Name:** 08-Calling_your_first_function

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

Building/ Testing the code is causing a crash and I cant figure out why

**Comment by tommygonzaleza** [comment]
Hello! That problem is happening because you had a syntax error in your code. If you like, share your code here so I can help you fix it
