### ISSUE TITLE
In Spanish it should say Masculino and Femenino, instead of Male and Female. Also the instructions says LGBTI and the validation says LGTBI

### ISSUE THREAD

**Issue by JulioNorambuena** [learnpack/learnpack#1409]
Describe the bug:

**1. Exercise Name:** 03-Type-Radio

**2. Repository URL:** undefined

**Comment by UmiKami** [comment]
Test should now accept both solutions in Engish and Spanish

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/56
Hrs: <hrs>0.27</hrs>
