### ISSUE TITLE
Excercise Bug: 04-Multiply-Two-Values

### ISSUE THREAD

**Issue by Nito84** [learnpack/learnpack#1410]
Describe the bug:

**1. Exercise Name:** 04-Multiply-Two-Values

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by UmiKami** [comment]
Found no issues that would prevent the tests from passing. However, I added a test to prevent the students from hard-coding the expected output.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/84
Hrs: <hrs>0.15</hrs>
