### ISSUE TITLE
Excercise Bug: 06-String_concatenation

### ISSUE THREAD

**Issue by franz8818** [learnpack/learnpack#1411]
Describe the bug:

**1. Exercise Name:** 06-String_concatenation

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**3. The test don´t pass, my code is ok

**Comment by UmiKami** [comment]
Make sure you do not have any extra spaces in your solution. 
The solution is just filling the empty string. 

let myVar1 = 'Hello';
let myVar2 = 'World';

**Comment by UmiKami** [comment]
PR: N/A
Hrs: <hrs>0.07</hrs>

**Comment by franz8818** [comment]
Hello Ernesto, thanks for answering. I realized that he was duplicating part of the code.

Franz Seidel
Macht Bikes
Celular 3162702385
