### ISSUE TITLE
Excercise Bug: 01-hello-world

### ISSUE THREAD

**Issue by donnizetti** [learnpack/learnpack#1421]
Describe the bug:

**1. Exercise Name:** 01-hello-world

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
The tests looks fine, can you provide us with more information about what the bug is and how to replicate it please

**Comment by tommygonzaleza** [comment]
Puedes utilizar Github para eso, lo aprenderas mas adelante en el curso. De todas maneras si tu entras al repositorio donde trabajaste puedes ver los codespaces que has abierto
