### ISSUE TITLE
Excercise Bug: 09-Max_integer_from_list

### ISSUE THREAD

**Issue by fernandaluft** [learnpack/learnpack#1423]
Describe the bug: it seems the correct answer requires a function but the exercise doesn't mention we have to create a function.

**1. Exercise Name:** 09-Max_integer_from_list

**2. Repository URL:** https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

**Comment by UmiKami** [comment]
Clarified function to be more clear on as to what is expected by the tests

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/105 
Hrs: <hrs>0.17</hrs>
