### ISSUE TITLE
Cambios en el test del ejercicio 08-Function-that-returns

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1424]
El primer test debe permitir que la funcion reciba numeros o variables como parametro

Repository: https://github.com/4GeeksAcademy/python-functions-programming-exercises

Exercises: 08-Function-that-returns

**Comment by UmiKami** [comment]
Primer test ahora acepta parametros alfanumericos.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/47
Hrs: <hrs>0.10</hrs>
