### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by xoeliazar** [learnpack/learnpack#1425]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course
El link del video no funciona y no deja avanzar el ejercicio.

**Comment by UmiKami** [comment]
El video estaba subido en la pagina the apis the breathecode. Como esta está caida, el video no es accessible.

**Comment by UmiKami** [comment]
@tommygonzaleza los videos de youtube reciben un CORS error.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.10</hrs>
