### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by lvvargas-aponte** [learnpack/learnpack#1427]
Describe the bug: source provided for video is not available. Code builds and executes as expected but no video is show. 

link provided in exercise: https://assets.breatheco.de/apis/video/why-pair-programming

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
This bug has been reported already, thanks anyway!
