### ISSUE TITLE
Excercise Bug: 20.5-Map-arrays-of-objects

### ISSUE THREAD

**Issue by Adjani09** [learnpack/learnpack#1431]
Describe the bug:

**1. Exercise Name:** 20.5-Map-arrays-of-objects

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

Aparece demasiadas veces este error, no importa cuanto cambie el codigo, sigue apareciendo y creo que ya es un error del test.

**Expected substring:** "Hello, my name is Joe and I am **36** years old,Hello, my name is Bob and I am 48 years old,Hello, my name is Erika and I am 34 years old,Hello, my name is Dylan and I am 23 years old,Hello, my name is Steve and I am 20 years old"
    
**Received string:**    "Hello, my name is Joe and I am **37** years old,Hello, my name is Bob and I am 48 years old,Hello, my name is Erika and I am 34 years old,Hello, my name is Dylan and I am 23 years old,Hello, my name is Steve and I am 20 years old

**Comment by UmiKami** [comment]
El error esta pasando porque en tu output estas diciendo que Joe tiene 37 años pero lo esperado es que tenga 36 años:

El resultado de tu codigo:

my name is Joe and I am **37 years old**

No obstante, el resultado esperado es 

my name is Joe and I am **36 years old**

Joe nacio el 24 de Octubre de 1986, lo que quiere decir que Joe actualmente tendria 36 años, lo cual significa que el resultado esparado es el correcto y el test está bien.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.12</hrs>

**Comment by Adjani09** [comment]
Buen día,
Tuve que poner 37 para que me dejara pasar el test.

**Comment by UmiKami** [comment]
Buenas tardes,

Hay un test que no pasa por que tu solución está dando 37 en vez de 36. Hay veces ningún test pasan por errores sintácticos, el más pequeño error de dicha naturaleza puede llevar a que ningun test pase. 

Esta es la solución:

```js
let people = [
	{ name: 'Joe', birthDate: new Date(1986,10,24) },
	{ name: 'Bob', birthDate: new Date(1975,5,24) },
	{ name: 'Erika', birthDate: new Date(1989,6,12) },
	{ name: 'Dylan', birthDate: new Date(1999,12,14) },
	{ name: 'Steve', birthDate: new Date(2003,4,24) }
];

let simplifier = function(person){
	let today = new Date()
	let age = today.getFullYear() - person.birthDate.getFullYear();
	let monthDifference = today.getMonth() - person.birthDate.getMonth();

	if (monthDifference < 0 || (monthDifference === 0 && today.getDate() < person.birthDate.getDate())) {
		age--;
	}

	return `Hello, my name is ${person.name} and I am ${age} years old`;
};

console.log(people.map(simplifier));  
```

Aunque no sea la unica solución posible, puedes compararla con la tuya y más o menos ver que puede estar yendo mal. Lo tests pasan con esta solución y el resultado es el esparado tal como está dado en las instrucciones.

**Comment by UmiKami** [comment]
Añadí el archivo con la solución al ejercicio.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.25</hrs>

**Comment by Adjani09** [comment]
Gracias,

Voy a volverlo a probar, pero recuerdo que tuve que cambiar incluso el
código que ya estaba antes del mío para poder pasar el test.
Creo que tuve que cambiar la fecha.
Voy a volverlo a intentar 😅 muchas gracias.
