### ISSUE TITLE
Excercise Bug: 10-static-layout

### ISSUE THREAD

**Issue by EmmanuelLM87** [learnpack/learnpack#1432]
Describe the bug:

**1. Exercise Name:** 10-static-layout

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

La construcción del ejercicio no se muestra, carga constantemente la página del ejercicio de LearnPack y no carga el resultado. No se ve lo uno está haciendo con HTML o CSS.

**Comment by tommygonzaleza** [comment]
Hola! Estamos trabajando para solucionar este bug, parece ser por unos cambios que se agregaron a codespaces y por eso esta fallando ahi, ya estamos en esto
