### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by jaac14** [learnpack/learnpack#1437]
Describe the bug: el enlace del video esta caido.

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Hola! Gracias, estamos trabajando en esto

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
