### ISSUE TITLE
Excercise Bug: 10-Array-Methods

### ISSUE THREAD

**Issue by Yahaira326** [learnpack/learnpack#1438]
Describe the bug:

**1. Exercise Name:** 10-Array-Methods

**2. Repository URL:** https://github.com/4GeeksAcademy/python-functions-programming-exercises

Is not a bug but the link in the hint send  us to Python List sort() Method which is not the one we need to use for this excercise for this one is sorted() I got totally lost as I never use Python before and I hope other people dont pass the same

**Comment by UmiKami** [comment]
Fixed link. Now pointing to right documentation.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/49

**Comment by UmiKami** [comment]
Hrs: <hrs>0.05</hrs>

**Comment by tommygonzaleza** [comment]
El link anterior funcionaba
