### ISSUE TITLE
Excercise Bug: 04-Call-a-function

### ISSUE THREAD

**Issue by jssolar** [learnpack/learnpack#1440]
Describe the bug:

**1. Exercise Name:** 04-Call-a-function

**2. Repository URL:** https://github.com/4GeeksAcademy/python-functions-programming-exercises

**Comment by UmiKami** [comment]
Test was failing if space was added in the function call between function name and parentheses. 


For example this would fail even if it was still correct:

```python3
square_area1 = calculate_area (4,4) # the space between calculate_area and (4,4) would make the test fail
```

**Comment by UmiKami** [comment]
Added solution file

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/50
Hrs: <hrs>0.12</hrs>
