### ISSUE TITLE
Excercise Bug: 01.1-hello-jsx

### ISSUE THREAD

**Issue by diegoguillen70** [learnpack/learnpack#1441]
Describe the bug:

1. Repository URL:** https://github.com/4GeeksAcademy/react-tutorial-exercises
2. Bluid the code open tutorial. I'm not able to see the view on the exercises 

[Screencast from 08-13-2023 08:28:33 AM.webm](https://github.com/learnpack/learnpack/assets/137721556/3e5e7c2d-dea5-47da-aa8f-8a4e9464113f)

**Comment by SamuelCarmona83** [comment]
Funciona en Gitpod, pero no en CodeSpaces.

**Comment by tommygonzaleza** [comment]
Hola! Gracias, ya estamos trabajando para solcuionarlo

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/108/
