### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by zetaese0** [learnpack/learnpack#1442]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

url video not found
https://assets.breatheco.de/apis/video/why-pair-programming

![image](https://github.com/learnpack/learnpack/assets/141279892/d5275e2e-2d62-45df-9e46-0b43be395585)

**Comment by tommygonzaleza** [comment]
Hello! Yes, we are already working to fix it, thanks for reporting it!
