### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by MAvila5** [learnpack/learnpack#1443]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

THE LINK TO THE VIDEO DOES NOT APPEAR TO WORK ANYMORE: https://assets.breatheco.de/apis/video/why-pair-programming

**Comment by tommygonzaleza** [comment]
Yes, we are working to recover the video, please replace the video while we bring it back @UmiKami

**Comment by UmiKami** [comment]
As youtube videos do not work with video / source tags. It took me quite a while to find a working video. Ended up downloading it from youtube and hosting it on AWS S3.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/124

**Comment by UmiKami** [comment]
Hrs: <hrs>0.43</hrs>

**Comment by tommygonzaleza** [comment]
No sirve porque el video es de otra academia

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
