### ISSUE TITLE
Excercise Bug: 05.1-dataframe-dict

### ISSUE THREAD

**Issue by linama2593** [learnpack/learnpack#1444]
Describe the bug:

**1. Exercise Name:** 05.1-dataframe-dict

**2. Repository URL:** undefined

The test option marks the exercise as incorrect when there is code in # from previous exercises 
![bug](https://github.com/learnpack/learnpack/assets/142395141/e2fc5d32-0783-4da2-a39b-257612f804af)

**Comment by UmiKami** [comment]
Hrs: <hrs>0.18</hrs>
