### ISSUE TITLE
Excercise Bug: 05.5-print-columns

### ISSUE THREAD

**Issue by linama2593** [learnpack/learnpack#1445]
Describe the bug:

**1. Exercise Name:** 05.5-print-columns

**2. Repository URL:** undefined
The instructions ask to print columns "Name" and "Type" but the expected output shows there's no "Type column" but "Type 1"
![bug 2](https://github.com/learnpack/learnpack/assets/142395141/ad8e2d5c-14b7-483b-9d1e-982626cb5663)

**Comment by UmiKami** [comment]
Corrected field name from 'Type' to 'Type 1' on both readmes as indicated by the initial section of the instructions and required by the tests.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/20

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>
