### ISSUE TITLE
Excercise Bug: 001-hello_world

### ISSUE THREAD

**Issue by Linnovel** [learnpack/learnpack#1446]
Describe the bug:

**1. Exercise Name:** 001-hello_world

**2. Repository URL:** https://github.com/4GeeksAcademy/master-python-programming-exercises 

**3. The build and test buttons don't run the exercise, not just the first exercise, any exercise and you can't reset after clicking build or test.

**Comment by tommygonzaleza** [comment]
Hello, it looks like there was an error loading your workspace, did you try opening a new workspace

**Comment by Linnovel** [comment]
Hi. Yes. I re-opened another one and work correctly
