### ISSUE TITLE
Excercise Bug: 09-connecting-stylesheet

### ISSUE THREAD

**Issue by alonsoagueda** [learnpack/learnpack#1451]
Describe the bug:

**1. Exercise Name:** 09-connecting-stylesheet

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

It's not saving my progress, learn pack is telling me the timecard its done and its not, not loading the right image when building

**Comment by AnggieAlava** [comment]
The bug has been fixed, I attach `screnshot`  verifying that learnpack is saving the log of the steps, and the exercise does compile the correct image when building.



![Image](https://github.com/learnpack/learnpack/assets/131820456/61dc9a80-9275-42e7-a086-cd92d456504f)



![Image](https://github.com/learnpack/learnpack/assets/131820456/e748ae01-12ca-4890-a7d1-ec0077f209bb)
