### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by faviagc** [learnpack/learnpack#1452]
Describe the bug: It runs without a problem but when the page appears its blank. I tried grading it an it said that it passed all tests.

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
This issue has been reported already [here](https://github.com/learnpack/learnpack/issues/1443) and we are working to fix it
