### ISSUE TITLE
Excercise Bug: 03-Multiply_two_values

### ISSUE THREAD

**Issue by leimber** [learnpack/learnpack#1453]
Describe the bug:

**1. Exercise Name:** 03-Multiply_two_values

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by UmiKami** [comment]
Couldn't find any issues. Tested for flexibility issues but none.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.05</hrs>
