### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by Perxcreate** [learnpack/learnpack#1457]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

I can't find the video, the url provided doesn't open anything to me.
No puedo encontrar el video, la url no me abre nada a mi.

This is the url i'm talking about:
Esta es la url en cuestión:
 https://assets.breatheco.de/apis/video/why-pair-programming

**Comment by tommygonzaleza** [comment]
This issue has been reported already [here](https://github.com/learnpack/learnpack/issues/1443) and we are working to fix it
