### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by Luis-Roldan** [learnpack/learnpack#1458]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

the video url does not open and shows 404 not found

**Comment by tommygonzaleza** [comment]
This issue has been reported already [here](https://github.com/learnpack/learnpack/issues/1443) and we are working to fix it
