### ISSUE TITLE
Excercise Bug: 01-hello-world

### ISSUE THREAD

**Issue by Danielperezarenas** [learnpack/learnpack#1459]
Describe the bug:

**1. Exercise Name:** 01-hello-world

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Hello I'm trying the learnpack start to reset the exercises, but when I click on build, does not show the new window

**Comment by Danielperezarenas** [comment]
Sometimes I have to click on build multiple times

**Comment by UmiKami** [comment]
Try opening a new codespace. May be that works.

**Comment by UmiKami** [comment]
@tommygonzaleza this is learnpack / codespaces issues most likely. I was able to see that for the first exercise I had to click twice on the build button for it to open a new window.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.07</hrs>
