### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by sebacent** [learnpack/learnpack#1460]
**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Los test para los siguiente casos no están funcionando correctamente: 

1. Cuando el número de invitados está entre 101 y 199
2. Cuando el número de invitados está entre 100 y 51

Resetee desde el botón varias veces e incluso cerré y volví a abrir la pestaña pero no funcionó
Mi intento:
![image](https://github.com/learnpack/learnpack/assets/87677519/02d23194-79b3-4abf-abe3-b7a783733099)

Código del tutorial:
![image](https://github.com/learnpack/learnpack/assets/87677519/2424b57b-27f1-4f74-b53c-f114b2870f45)

Copiando el código del tutorial obtengo el mismo resultado:
![image](https://github.com/learnpack/learnpack/assets/87677519/9471dd23-a9d1-46bb-994d-1e2fb185519a)

**Comment by sebacent** [comment]
El error se encuentra en la última línea si se quita el símbolo de "$" pasa los test sin problemas!

**Comment by UmiKami** [comment]
El código que se provee por defecto usualmente no se cambia a no ser que se indique lo contrario en las instrucciones.

En esta series de ejercicios en particular, si ves, ↓ ❌   ❌↓, usualmente significa que no debes editar la linea de código justo debajo.


También note que la descripción de dos de los tests está mal. Eso se va a corregir.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/88
