### ISSUE TITLE
Excercise Bug: 09.2-Calendar-icon

### ISSUE THREAD

**Issue by amv87** [learnpack/learnpack#1463]
Describe the bug: When pressing reset, it does nothing. It happens on other exercises as well. It seems like it only resets the HTML code.

**1. Exercise Name:** 09.2-Calendar-icon

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

**Comment by tommygonzaleza** [comment]
Yes, we are working to fix the reset button for all the files instead of only the entry file
