### ISSUE TITLE
Excercise Bug: 033-addObjectProperty

### ISSUE THREAD

**Issue by RDLuisL** [learnpack/learnpack#1467]
Describe the bug:

**1. Exercise Name:** 033-addObjectProperty

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

Esta mal redactado el ejercicio me pareceque la idea es poner un nuevo role que se llame: manager en el primer objeto. de tal manera que Joe Blow tenga ahora un role de manager
![Captura](https://github.com/learnpack/learnpack/assets/102940535/26aa4b68-1518-410d-9e74-e31ccd872ec7)

**Comment by AnggieAlava** [comment]
@RDLuisL  Gracias por tu observacion!  El objetivo central del ejercicio es comprender cómo agregar nuevas propiedades a un objeto en JavaScript, independientemente del nombre o contenido de esas propiedades.

En el ejemplo, se utiliza "manager" como nombre de la propiedad para ilustrar cómo se agrega una nueva propiedad al primer objeto. Sin embargo, podríamos haber usado cualquier otro nombre, como "nuevoRol", y el concepto seguiría siendo el mismo: agregar una nueva propiedad al objeto.

Por lo tanto, el objetivo principal es aprender a manipular objetos en JavaScript y comprender cómo agregar nuevas propiedades dinámicamente. Agradezco tu observación y espero que esto aclare las cosas.

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/200/files

**Comment by tommygonzaleza** [comment]
- [ ] Agrega los cambios de las instrucciones en el README.md de ingles tambien

**Comment by AnggieAlava** [comment]
Fixed
