### ISSUE TITLE
Excercise Bug: 048-isEitherEvenAndLessThan9

### ISSUE THREAD

**Issue by RDLuisL** [learnpack/learnpack#1468]
![Captura 2](https://github.com/learnpack/learnpack/assets/102940535/cc77d9fe-781d-4d7a-bbc6-31e318430b96)
Describe the bug:

**1. Exercise Name:** 048-isEitherEvenAndLessThan9

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

el enunciado del ejercicio no esta acoorde con la prueba que se hace del codigo; leer las indicaciones y el testing de las imagenes
![Captura 1](https://github.com/learnpack/learnpack/assets/102940535/af99e363-ff69-4ed6-b9fc-d999851c996c)

**Comment by AnggieAlava** [comment]
### Test funciona correctamente

- El enunciado es claro indicando que hay dos condiciones que deben cumplirse 

1. Que al menos uno sea par
2. Y que ambos sean menores a 9

##### _Ambas condiciones son evaluadas en los test y funciona correctamente_
