### ISSUE TITLE
Excercise Bug: 10-replicate-html

### ISSUE THREAD

**Issue by abielsaf** [learnpack/learnpack#1470]
Describe the bug:

**1. Exercise Name:** 10-replicate-html

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Small typo on the image you have to replicate in html, "Is 12 AM and you don't want to go to sleep."

![image](https://github.com/learnpack/learnpack/assets/145146806/ffe6c979-79e3-41c6-8b29-05ddbb0cf56f)

But in the text that you can copy it's written the correct way. "It's 12am and you don't want to go to sleep."

![image](https://github.com/learnpack/learnpack/assets/145146806/6abef3b6-4827-4f82-80b6-bb9379de4439)

**Comment by AnggieAlava** [comment]
Link to PR : https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/131

**Comment by abielsaf** [comment]
Fixed.
