### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by velazcopolo** [learnpack/learnpack#1481]
Describe the bug: al momento de evaluar el código da positivo, pero al construir la pagina el archivo no aparece

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
