### ISSUE TITLE
Excercise Bug: 19-Bottles-Of-Milk

### ISSUE THREAD

**Issue by EugeneJosephCruz** [learnpack/learnpack#1484]
Describe the bug:
The solution doesn't have the same line breaks as the sample output in the description. Not even Alejandro could get his code to check out for this exercise in the checker (see solution video). Look at the displayed sample output and compare it to the solution and see that there should be a couple of \n's written in there to get them to match up. 

**1. Exercise Name:** 19-Bottles-Of-Milk

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by rvpacheco** [comment]
Se arreglo el solution y el test, para que tuviera el salto de linea como el ejemplo.

**Comment by tommygonzaleza** [comment]
- [ ] Quitale el salto de linea en el readme y con eso tanto el solution como el test queda funcionando bien

**Comment by rvpacheco** [comment]
ya se arreglo el readme
