### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by casalf724** [learnpack/learnpack#1485]
Describe the bug:

**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

user_input = int(input('How many people are coming to your wedding?\n'))

# Below is my code I get the correct answer on the terminal box but the learnpack instructions box goes red w/ error - never give up.
 
# ❌ ⬆ DON'T CHANGE THE CODE ABOVE  ⬆ ❌
price = 20000
if user_input <= 50:
    price = 4000
# ✅ ↓ Your code here ↓ ✅
elif user_input <= 100:
    price = 10000
elif user_input <= 200:
    price = 15000

# ✅ ↓ Your code here ↓ ✅

# ❌ ↓ DON'T CHANGE THE CODE BELOW ↓ ❌
print('Your wedding will cost $'+str(price)+' dollars')

**Comment by luiscmilano** [comment]
Excercise Bug: 08.2-How-Much-The-Wedding-Costs #1511

The string that is printed at the end of the exercise:

# :x: ↓ DO NOT CHANGE THE CODE BELOW ↓ :x:
print('Your wedding will cost $'+str(price)+' dollars').

This is different from the string set in the solution file to which the result is compared.

The "$" sign is left over and creates the error.

The message should be

print('Your wedding will cost '+str(price)+' dollars')

Without the "$" sign in the last line of the exercise.

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/learnpack/learnpack/issues/1487)
