### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by damianconpan** [learnpack/learnpack#1486]
Describe the bug: el siguiente link " https://assets.breatheco.de/apis/video/why-pair-programming." no lleva a ningun video, solo arroja error 404

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
