### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by HeTron** [learnpack/learnpack#1487]
Describe the bug:
To preface, I am just starting out. However, I am not super green so I decided to report this in hopes that I am correct and not just aloof.

It seems as if the test for this function is incorrect. The instructions say the numbers are inclusive but it looks like it is testing one of the conditions to be between 101 - 199 instead of 101-200. When I run it myself it checks out fine but when I test it, it fails due to the test paramaters.
<img width="1342" alt="Screenshot 2023-10-03 at 10 16 12 PM" src="https://github.com/learnpack/learnpack/assets/31374088/7ebed357-0cc8-4e53-a9eb-d258612a9dbd">

**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by luiscmilano** [comment]
Excercise Bug: 08.2-How-Much-The-Wedding-Costs #1511

The string that is printed at the end of the exercise:

# :x: ↓ DO NOT CHANGE THE CODE BELOW ↓ :x:
print('Your wedding will cost $'+str(price)+' dollars').

This is different from the string set in the solution file to which the result is compared.

The "$" sign is left over and creates the error.

The message should be

print('Your wedding will cost '+str(price)+' dollars')

Without the "$" sign in the last line of the exercise.
