### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by puupa** [learnpack/learnpack#1488]
1Describe the bug:

**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

running the test gives me the following errors:

![image](https://github.com/learnpack/learnpack/assets/8792366/3d60f6a7-df58-463c-9338-d8d7e70761e1)

In the test.py file you can see that in the first case is tested for value 199 with an amount 15000 and value 100 for an amount of 10000.

![image](https://github.com/learnpack/learnpack/assets/8792366/ac651c86-9790-45c6-89b0-ce8a269ad9eb)

when I build and give userinput values 199 and 100, I get as output respectively 15000 and 10000.

My code is:

![image](https://github.com/learnpack/learnpack/assets/8792366/7fbb9684-31e1-432f-8972-6cc3cb88cd7b)

**Comment by luiscmilano** [comment]
Excercise Bug: 08.2-How-Much-The-Wedding-Costs #1511

The string that is printed at the end of the exercise:

# :x: ↓ DO NOT CHANGE THE CODE BELOW ↓ :x:
print('Your wedding will cost $'+str(price)+' dollars').

This is different from the string set in the solution file to which the result is compared.

The "$" sign is left over and creates the error.

The message should be

print('Your wedding will cost '+str(price)+' dollars')

Without the "$" sign in the last line of the exercise.

**Comment by puupa** [comment]
@luiscmilano thanks, I committed the correction and submitted a pull request
