### ISSUE TITLE
Excercise Bug: 01.1-like-word

### ISSUE THREAD

**Issue by Alberbor** [learnpack/learnpack#1489]
Describe the bug:

**1. Exercise Name:** 01.1-like-word

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

After checking by comparison once and again teh solutions VS my coe... seems no difference but restuls as incorrect... May it be possible? or am I mistaken?

**Comment by rvpacheco** [comment]
it works fine
