### ISSUE TITLE
Excercise Bug: 35-square-each-odd-number

### ISSUE THREAD

**Issue by flaviaolivera** [learnpack/learnpack#1491]
Describe the bug: It says that "Then, the output should be: 1,3,5,7,9" but the output should be the square of that numbers so it has to be 1, 9, 25, 49, 81

**1. Exercise Name:** 35-square-each-odd-number

**2. Repository URL:** https://github.com/4GeeksAcademy/master-python-programming-exercises

**Comment by rvpacheco** [comment]
output is fine

![Image](https://github.com/learnpack/learnpack/assets/124650306/6d8a6de5-3e88-4fcf-be9e-aee47ee575ac)
