### ISSUE TITLE
Excercise Bug: 38-sort-tuples-ascending

### ISSUE THREAD

**Issue by flaviaolivera** [learnpack/learnpack#1492]
Describe the bug: The output should be [('Jason', '21', '85'), ('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Tom', '19', '80')]

**1. Exercise Name:** 38-sort-tuples-ascending

**2. Repository URL:** https://github.com/4GeeksAcademy/master-python-programming-exercises

**Comment by rvpacheco** [comment]
that's the output:


![Image](https://github.com/learnpack/learnpack/assets/124650306/ddaccc24-f1ad-4a6c-b145-27a299720142)
