### ISSUE TITLE
Excercise Bug: 03-Position-relative-vs-absolute

### ISSUE THREAD

**Issue by Thragull** [learnpack/learnpack#1493]
Describe the bug:

**1. Exercise Name:** 03-Position-relative-vs-absolute

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

It's not a bug itself, but since the body Background is in blue color and also the #firstDiv, the exercise is not fully visible to understand the meaning of it. I have changed the color of the body background to red in order to visualize the exercise properly.

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/learnpack/learnpack/issues/1487)

**Comment by AnggieAlava** [comment]
Link to PR https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/55

**Comment by tommygonzaleza** [comment]
Agregale pruebas unitarias al ejercicio
