### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by danielamfernandez** [learnpack/learnpack#1496]
Describe the bug: literalmente aunque lo haga igual al tutorial sin typos ni nada, aunque le haga copypaste a la solucion, me pone que esta mal!

**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by luiscmilano** [comment]
Excercise Bug: 08.2-How-Much-The-Wedding-Costs #1511

The string that is printed at the end of the exercise:

# :x: ↓ DO NOT CHANGE THE CODE BELOW ↓ :x:
print('Your wedding will cost $'+str(price)+' dollars').

This is different from the string set in the solution file to which the result is compared.

The "$" sign is left over and creates the error.

The message should be

print('Your wedding will cost '+str(price)+' dollars')

Without the "$" sign in the last line of the exercise.

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/learnpack/learnpack/issues/1487)
