### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by alondragerke** [learnpack/learnpack#1498]
Describe the bug:
El vídeo que debería estar en el link no funciona, da el mensaje de "The requested URL was not found on this server"

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
