### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by ierrandonea** [learnpack/learnpack#15]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

The code seems working, however, validation doesn't seem to work properly when comparing...

## Other details: 
1. Exercises: 22-Russian-Roulette
2. Current URL: https://fc7c9316-2e36-4209-a533-2c84bffdc653.ws-us02.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by ElviraQDP** [comment]
Keep trying!
