### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by TheNeonSpray** [learnpack/learnpack#150]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

No compila

## Other details: 
1. Exercises: 16-Rand-from-one-to-six
2. Current URL: https://cc552223-9fc5-43ef-9f32-a51054e99fa8.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by ElviraQDP** [comment]
Lo acabo de chequear y me compilo ¿Puedes intentarl de nuevo? gracias!
