### ISSUE TITLE
Excercise Bug: 14-goodbye

### ISSUE THREAD

**Issue by mcamilaortega** [learnpack/learnpack#1501]
Describe the bug:
 Compile errors through out the whole exercise. Not able to see while building 
**1. Exercise Name:** 14-goodbye

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

**Comment by AnggieAlava** [comment]
In codespace the exercise has no problems in constructing the steps correctly. 

![Image](https://github.com/learnpack/learnpack/assets/131820456/8f44907e-2c0b-4a04-8d54-717f49ce19cd)
