### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by Dageti** [learnpack/learnpack#1507]
This exercise is not working properly with the correct input, tried even copying and pasting the solution and is still throwing errors

**Comment by luiscmilano** [comment]
Excercise Bug: 08.2-How-Much-The-Wedding-Costs #1511

The string that is printed at the end of the exercise:

# :x: ↓ DO NOT CHANGE THE CODE BELOW ↓ :x:
print('Your wedding will cost $'+str(price)+' dollars').

This is different from the string set in the solution file to which the result is compared.

The "$" sign is left over and creates the error.

The message should be

print('Your wedding will cost '+str(price)+' dollars')

Without the "$" sign in the last line of the exercise.

**Comment by tommygonzaleza** [comment]
Ya fue resuelto en master
