### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by NicolasArayaB** [learnpack/learnpack#151]
Hrs: <hrs>0.5</hrs>

# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

In this exercise, the instructions ask to create a matrix of random 0's, and 1's based on a parameter. 
The tester expect a matrix of  only 1's, so when you run the test, it send you the error message that the result is incorrect.
![2021-01-22 (2)](https://user-images.githubusercontent.com/63371423/105565491-cd913f80-5d05-11eb-9ca2-569ef01942f9.png)

## Other details: 
1. Exercises: 22-Matrix-Builder
2. Current URL: https://ff0139bf-5347-4f55-acfa-f52d665004a1.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/14
Hrs: <hrs>0.5</hrs>
