### ISSUE TITLE
Excercise Bug: 02-Display-none

### ISSUE THREAD

**Issue by DonBeta** [learnpack/learnpack#1510]
Describe the bug:

**1. Exercise Name:** 02-Display-none

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

**Comment by AnggieAlava** [comment]
![Image](https://github.com/learnpack/learnpack/assets/131820456/395a4999-f52a-4b31-9dd7-d07401596de5)

Funciona correctamente.
