### ISSUE TITLE
Excercise Bug: 04-Call-a-function

### ISSUE THREAD

**Issue by gri54** [learnpack/learnpack#1512]
Describe the bug:
I cannot see the image below

**1. Exercise Name:** 04-Call-a-function

**2. Repository URL:** https://github.com/4GeeksAcademy/python-functions-programming-exercises

**Comment by AnggieAlava** [comment]
The images in the exercise are built correctly.



![Image](https://github.com/learnpack/learnpack/assets/131820456/18d470be-c8d6-4f34-95b4-2a0552d04bb4)
