### ISSUE TITLE
Excercise Bug: 03.1-your-first-component

### ISSUE THREAD

**Issue by mjhs1999** [learnpack/learnpack#1513]
Describe the bug:

**1. Exercise Name:** 03.1-your-first-component

**2. Repository URL:** https://github.com/4GeeksAcademy/react-tutorial-exercises

Una de las cosas que podemos hacer gracias a JSX es llamar funciones com si fueran etiquetas HTML, por ejemplo 
should be:

Una de las cosas que podemos hacer gracias a JSX es llamar funciones como si fueran etiquetas HTML, por ejemplo

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/118
