### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by Fabianyzb** [learnpack/learnpack#1514]
Describe the bug:

**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

No funciona con ningún resultado

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/learnpack/learnpack/issues/1487)
