### ISSUE TITLE
Excercise Bug: 016-array-border

### ISSUE THREAD

**Issue by jfcm90** [learnpack/learnpack#1518]
Describe the bug:

**1. Exercise Name:** 016-array-border

**2. Repository URL:** https://github.com/4GeeksAcademy/numpy-tutorial-exercises

When I use the following code:
s = (5,5)
Matrix = np.ones (s)
Matrix[1:-1,1:-1] = 0
print (Matrix)

This gives an error, but when looking at the requested output, both are the same:

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
 
 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

**Comment by AnggieAlava** [comment]
#### Repository not found, or name of the exercise changed.

**Comment by AnggieAlava** [comment]
![Image](https://github.com/learnpack/learnpack/assets/131820456/166aa5be-d5a0-4b4a-b8c9-af0a62509b41)

Using the user code, and the hide.solution code, in both cases the test approves, the result in both is correct. In conclusion, the bug has already been solved.
