### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by Karel-CR** [learnpack/learnpack#1519]
Describe the bug: Despite the code is all right, as the url given doesn't exist it doesn't shows anything.

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

The requested URL was not found on this server.

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
