### ISSUE TITLE
Exercise in wrong directory

### ISSUE THREAD

**Issue by NicolasArayaB** [learnpack/learnpack#152]
**Describe the bug**
On the js-array exercises, on the folder of exercise 20.3, you can found the sub-folder 21.
If you go with the  next-> button of the preview, you wont be able to do it . Also, I moved it to the /exercises folder, but I couldn't find it in the preview menu  either.

**In what exercise**

**Exercise:** 20.3 - 21.
**Repository:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

![2021-01-22 (3)](https://user-images.githubusercontent.com/63371423/105565950-35e12080-5d08-11eb-9bfc-1f0f24bdf0be.png)

**Comment by ElviraQDP** [comment]
I just moved the exercise into the right folder, thank you for letting us know!
