### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by Skomorac** [learnpack/learnpack#1520]
Describe the bug:

A click to provided link [https://assets.breatheco.de/apis/video/why-pair-programming](url) in  exercise for video opens page with 404 error

![error 14 video tag](https://github.com/learnpack/learnpack/assets/56019597/9c8c659a-dc8c-45db-9df4-3150771ef1f4)

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Resuelto en este PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/125
