### ISSUE TITLE
Excercise Bug: 22-Integral

### ISSUE THREAD

**Issue by juanvicente0104** [learnpack/learnpack#1522]
Describe the bug:

**1. Exercise Name:** 22-Integral

**2. Repository URL:** https://github.com/4GeeksAcademy/master-python-programming-exercises

There is not a bug but the instructions are not clear at all!
The instructions should specify clearly that the user should create a function named generate_dict() that takes n as an input. This is the only way the tests passes!

**Comment by AnggieAlava** [comment]
The instructions are updated, the exercise actually asks to create a squares_dictionary() function that receives "n" as imput, everything runs as it should.

![Image](https://github.com/learnpack/learnpack/assets/131820456/5aee35ff-39ad-4b7a-b8b6-db26dbe8d169)
