### ISSUE TITLE
Excercise Bug: 14-Divide-and-Conquer

### ISSUE THREAD

**Issue by AltaciosTheDev** [learnpack/learnpack#1523]
Describe the bug:

**1. Exercise Name:** 14-Divide-and-Conquer

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

I think the bug is with the test. The exercise is correct but it keeps saying the odd must come before the even.

![bug array exercise 14](https://github.com/learnpack/learnpack/assets/133562096/3adeccf1-0231-401d-b98b-7ab77b1c3c56)

**Comment by AnggieAlava** [comment]
![Image](https://github.com/learnpack/learnpack/assets/131820456/0a28596e-7c28-4dce-818d-1f8ce8cbcf3b)


### The bug no longer occurs.
