### ISSUE TITLE
Excercise Bug: 061-removeFromBackOfNew

### ISSUE THREAD

**Issue by AltaciosTheDev** [learnpack/learnpack#1524]
Describe the bug:

**1. Exercise Name:** 061-removeFromBackOfNew

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

Preview instruction image and base code is the same of the exercise 60. 
![image](https://github.com/learnpack/learnpack/assets/133562096/5712bfec-0fdc-4636-8cd8-8869dff2789d)

**Comment by AnggieAlava** [comment]
Exercise 60 is about the student deleting the first element of the array, while exercise 61 is about deleting the last element of the array.


![Image](https://github.com/learnpack/learnpack/assets/131820456/f1ac555f-490e-42af-b52c-c6d28647af3a)



![Image](https://github.com/learnpack/learnpack/assets/131820456/39f127a3-7a64-4347-86d1-76cbe0244927)
