### ISSUE TITLE
Excercise Bug: 03-Multiply_two_values

### ISSUE THREAD

**Issue by yjlmotley** [learnpack/learnpack#1525]
Describe the bug:

**1. Exercise Name:** 03-Multiply_two_values

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

When I hit build, the JavaScript code isn't running in a way it's printing to the console.

**Comment by AnggieAlava** [comment]
![Image](https://github.com/learnpack/learnpack/assets/131820456/5306b751-51de-4c4b-b19c-7d59f5a36636)


#### The construction button is working properly.
