### ISSUE TITLE
Excercise Bug: 05.2-dataframe-iloc

### ISSUE THREAD

**Issue by AndresBuendia** [learnpack/learnpack#1526]
Describe the bug:
I've encountered an inconsistency in the exercise instructions regarding the use of the iloc command in Pandas. The issue is as follows:

Inconsistency in Example Explanation:
The provided example in the instructions states:

"The iloc command lets you retrieve any cell in your data_frame. For example, to print the cell in the x-axis:2 and y-axis:4 we would have to type the following: print(data_frame.iloc[2,4])"

However, there's a discrepancy in the comment of the example code:

"# Print only item in the Row: 2, Col: 1"

This comment contradicts the actual code (iloc[2,4]), which would access the cell at Row 3 and Column 5 (considering zero-based indexing).

Mismatch in Exercise Requirement and Test Expectation:
The exercise instructions ask to print the DataFrame row 133 and column 6. According to zero-based indexing in Pandas, this would translate to iloc[132, 5]. However, the test seems to expect the code iloc[133, 6], which actually accesses row 134 and column 7.

These inconsistencies may lead to confusion and incorrect outcomes. I believe there might be an error either in the example provided in the instructions or in the test expectations. It would be helpful if this could be reviewed and clarified to ensure accurate and consistent guidance in the exercise.

**1. Exercise Name:** 05.2-dataframe-iloc

**2. Repository URL:** undefined

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/31
