### ISSUE TITLE
Excercise Bug: 03-Call-a-function

### ISSUE THREAD

**Issue by JoseJoaquinMartinez** [learnpack/learnpack#1528]
Describe the bug:

**1. Exercise Name:** 03-Call-a-function

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial
La imagen donde viene las medidas a utilizar en el ejercicio no se carga, por lo que no se pueden ver las medidas de los cuadrados para las funciones y no se puede completar el ejercicio
![Captura de pantalla 2023-12-06 082959](https://github.com/learnpack/learnpack/assets/61237112/f8fdd269-e63b-4f34-952a-518d9dd0a568)

**Comment by rvpacheco** [comment]
si se ve la imagen

![Image](https://github.com/learnpack/learnpack/assets/124650306/48b2992a-aca6-4fc2-b274-f4208abfaf02)

**Comment by tommygonzaleza** [comment]
- [ ] Descarga la imagen, subela a github y ponle la ruta relativa a la imagen

**Comment by rvpacheco** [comment]
listo: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/102
