### ISSUE TITLE
Typo Error Excercise

### ISSUE THREAD

**Issue by Shmaither** [learnpack/learnpack#153]
# Typo error describing href relative path in anchor tag

There's a typo error on the second anchor tag example. 

It says: 
`<a href="/graphics/image.png">Take me to index.html that is inside the /graphics/ directory</a>`

it should say:
`<a href="/graphics/image.png">Take me to image.png that is inside the /graphics/ directory</a>`

I hope it helps.

## Other details: 
1. Exercises: 08-relative-vs-absolute-path-anchor-tag
![typoError_ Exercises 08](https://user-images.githubusercontent.com/58092795/105567241-5a340180-5cf6-11eb-85de-1899d262f2a4.jpg)

2. Current URL: https://c5e47a3e-f048-4a95-9c5a-08fca33036bb.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by ElviraQDP** [comment]
Thank you, it does help! it has been corrected.
