### ISSUE TITLE
Excercise Bug: 10.1-And_One_and_a_Two_and_a_Three

### ISSUE THREAD

**Issue by brootware** [learnpack/learnpack#1535]
Describe the bug:
There is a formatting error in the instructions that is misleading when we are solving the exercise. The instruction of the [README.md](https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/blob/master/exercises/10.1-And_One_and_a_Two_and_a_Three/README.md) is as per below:

## 💻 Example console output:

```py
fullname: John Doe
phone: 123-123-2134
email: test@nowhere.com
```

So I wrote the code following the instruction and got the test failed error. Only after looking through the test code, I could see that the formatting should be as below (having a space in between key and the colon).

```py
fullname : John Doe
phone : 123-123-2134
email : test@nowhere.com
```

If the maintainers are ok, I can do a PR to [this](https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/blob/master/exercises/10.1-And_One_and_a_Two_and_a_Three/README.md) to resolve the bug.

**1. Exercise Name:** 10.1-And_One_and_a_Two_and_a_Three

**2. Repository URL:** https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/120
