### ISSUE TITLE
Excercise Bug: 11-Create-A-New-Function

### ISSUE THREAD

**Issue by Rafa-Carrasco** [learnpack/learnpack#1539]
Describe the bug:

**1. Exercise Name:** 11-Create-A-New-Function

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Compiles ok and return the right results,  but it gives an error even when the exact script is copied from the video tutorial

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/99
