### ISSUE TITLE
Bicho excercise

### ISSUE THREAD

**Issue by Norris2021** [learnpack/learnpack#154]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Hola. Del ejercicio 10 al 15 cuando lo realizo le doy click a BUILD y no me muestra lo que realice.

## Other details: 
1. Exercises: 11-nested-tags
2. Current URL: https://f5336c8e-2137-479e-b69f-9f81556a4576.ws-eu03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by ElviraQDP** [comment]
Hola, acabo de verificar y esta funcionando ¿Quizas tuviste problemas de conexion o Gitpod estaba con problemas?
