### ISSUE TITLE
Excercise Bug: 19-Bottles-Of-Milk

### ISSUE THREAD

**Issue by Rafa-Carrasco** [learnpack/learnpack#1543]
Describe the bug:

**1. Exercise Name:** 19-Bottles-Of-Milk

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Output in the solution.hide.py doesn't look like the one on the instructions (no spaces between lines)

**Comment by rvpacheco** [comment]
the line break in the readme has been removed.
pull request: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/103
