### ISSUE TITLE
Excercise Bug: 12.1-body-content

### ISSUE THREAD

**Issue by JorgeAJT** [learnpack/learnpack#1544]
Describe the bug:
The input tag hasn't explained previously so it's very difficult to understand this part without the knowledge of that tag.

**1. Exercise Name:** 12.1-body-content

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

**Comment by AnggieAlava** [comment]
This reading may be extra helpful : https://www.geeksforgeeks.org/html-input-tag/

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/breatheco-de/exercise-postcard/pull/126
