### ISSUE TITLE
Excercise Bug: 10.1-And_One_and_a_Two_and_a_Three

### ISSUE THREAD

**Issue by jronald88** [learnpack/learnpack#1545]
Describe the bug:

**1. Exercise Name:** 10.1-And_One_and_a_Two_and_a_Three

**2. Repository URL:** https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

using the code given in the solution, the exercise reports back as not as expected

**Comment by rvpacheco** [comment]
yes, it works if you use the soultion: 

![Image](https://github.com/learnpack/learnpack/assets/124650306/fc174fd4-7ab6-4efa-aa77-075bbd8c3c2d)
