### ISSUE TITLE
Excercise Bug: 007-change-vector-values

### ISSUE THREAD

**Issue by jronald88** [learnpack/learnpack#1548]
Describe the bug:

**1. Exercise Name:** 007-change-vector-values
 The output is as expected. Without passing the test, I cannot progress in the unit. 

**2. Repository URL:** undefined

**Comment by AnggieAlava** [comment]
#Numpy

**Comment by AnggieAlava** [comment]
![Image](https://github.com/learnpack/learnpack/assets/131820456/4f37f144-8f3c-46c9-a585-1d9d09da5680)

The exercise and its test are working properly
