### ISSUE TITLE
Excercise Bug: 04.4-Add_items_to_array_looping

### ISSUE THREAD

**Issue by Tobifads** [learnpack/learnpack#1550]
Describe the bug:
The code compiles successfully on learnpack but the test options keeps leading to disconnected.

**1. Exercise Name:** 04.4-Add_items_to_array_looping

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by AngelesRocks** [comment]
@tommygonzaleza El ejercicio "04.4-Add_items_to_array_looping" compila correctamente en LearnPack. Ejecuté el script de prueba , y no se han encontrado errores de compilación ni problemas en la ejecución del código del ejercicio.

![Image](https://github.com/learnpack/learnpack/assets/131820456/61b71b51-aafa-4231-b07c-44cf50e906e3)
