### ISSUE TITLE
Excercise Bug: 21-Filter-an-array

### ISSUE THREAD

**Issue by KitsuneDai** [learnpack/learnpack#1554]
Describe the bug:

**1. Exercise Name:** 21-Filter-an-array

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

In the solution are write 
----------------------------------------------------------
let allNames = ["Romario", "Boby", "Roosevelt", "Emiliy", "Michael", "Greta", "Patricia", "Danzalee"];

// Your code here
let resultingNames = allNames.filter(function(item) {
   if item[0] === "R";
});

console.log(resultingNames);
--------------------------------------------------------------
"return item" is missing in conditional statements to compile the exercise.

Regards

**Comment by rvpacheco** [comment]
I checked the issue and the solution its working well
