### ISSUE TITLE
Bug Exercise: 07.1-test-post-todo

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1555]
Repository: https://github.com/breatheco-de/python-flask-api-tutorial

Exercise: 07.1-test-post-todo

Bueno, estoy terminando las cosas que me faltaban y en el módulo "Todo List API with Python Flask Interactive" hay un bug en el 7.1 donde el test no le manda payload al endpoint, por lo que retorna 415 y siempre falla. Después de un poco de lectura y comparación con el test del 7.0 me di cuenta que es este el problema :
(.learn/exercises/07.1-test-post-todo/test.py)

```py
@pytest.mark.it("The endpoint POST /todos should exist")
def test_return(client):
    response = client.post('/todos')
    assert response.status_code in [200, 201]
```

Cuando debería tener un body (o payload, como indica el punto 7.0)  "  json=json.dumps({})  " para que el endpoint lo acepte:

```py
@pytest.mark.it("The endpoint POST /todos should exist")
def test_return(client):
    response = client.post('/todos',json=json.dumps({}))
    assert response.status_code in [200, 201]
```

Paso esta info para que puedan corregir el learnpack y para quienes quieran entregar los modulos que les faltan lo puedan hacer

**Comment by AngelesRocks** [comment]
@tommygonzaleza  Ya esta corregido tal cual indicas, solo faltaba agregar esa linea de codigo. 
Aqui esta el link al Pull Request https://github.com/breatheco-de/python-flask-api-tutorial/pull/84
