### ISSUE TITLE
Excercise Bug: 23-Bottles_of_milk

### ISSUE THREAD

**Issue by TomasArancibia** [learnpack/learnpack#1556]
Describe the bug: There is an incongruence between the expected output that is shown and a test case:
![Captura de pantalla 2024-02-05 194900](https://github.com/learnpack/learnpack/assets/101353494/1f733c8b-e86d-4db8-9d2c-24536fb60239)
As is seen in the image of the expected output, the correct algoritm should print two diferrent strings, each for one of the parts of the lyric, the way of doing this two strings is by calling two times per quantity of milks bottles the function consol.log(). But there is a test case that tells you that you have to do the function by calling consol.log() only 99 or 100 times in total. That can only be done if you print both parts of the lyric for each quantity of bottles, but by doing this the is not posible to have the exact expected output as the one that the exercise shows.

**1. Exercise Name:** 23-Bottles_of_milk

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by tommygonzaleza** [comment]
Ya esta resuelto
