### ISSUE TITLE
Excercise Bug: 00.1-Inline-Styles

### ISSUE THREAD

**Issue by sebas-masia** [learnpack/learnpack#1558]
Describe the bug: It's showing incorrect starting code, the instructions never talk about applying styles to a table

**1. Exercise Name:** 00.1-Inline-Styles

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/134

**Comment by tommygonzaleza** [comment]
It will be solved in this [issue](https://github.com/breatheco-de/breatheco-de/issues/7057)
