### ISSUE TITLE
Excercise Bug: 04-fieldsets-labels-and-styles

### ISSUE THREAD

**Issue by JorgeAJT** [learnpack/learnpack#1559]
Describe the bug:

**1. Exercise Name: From exercise 04 to the last one. I cannot check the solution of my exercise. 

**2. Repository URL:(https://bookish-broccoli-5gg567pv5jpgc7rj.github.dev/)

**Comment by AnggieAlava** [comment]
Repositorio : https://github.com/4GeeksAcademy/html-forms-tutorial-exercises

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/64
