### ISSUE TITLE
Excercise Bug: 11-Your_first_if

### ISSUE THREAD

**Issue by alejo0022** [learnpack/learnpack#1560]
Describe the bug:
me da error al testear dice que no esta completo pero todo lo que me pide esta bien 

**1. Exercise Name:** 11-Your_first_if

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by AnggieAlava** [comment]
![Image](https://github.com/learnpack/learnpack/assets/131820456/bb4b9829-bd4c-491a-a633-2750b962bd7d)

The bug has been fixed, it does not happen anymore.
