### ISSUE TITLE
Excercise Bug: 09-Beautify

### ISSUE THREAD

**Issue by dparkar00** [learnpack/learnpack#1561]
Describe the bug:

**1. Exercise Name:** 09-Beautify

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

Says that there are supposed to be 6 strong tags but picture only shows 2

**Comment by AnggieAlava** [comment]
@dparkar00 Visually they should all have the <strong> tag to handle the same standard.
