### ISSUE TITLE
Excercise Bug: 00.1-Inline-Styles

### ISSUE THREAD

**Issue by justicetrace** [learnpack/learnpack#1562]
Describe the bug: Terminal wants <table> inline style background color "green". Not seen on Instructions in LearnPack.

**1. Exercise Name:** 00.1-Inline-Styles

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by rvpacheco** [comment]
se arreglo el readme: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/139
