### ISSUE TITLE
Excercise Bug: 04.1-Combined-Rules

### ISSUE THREAD

**Issue by KOTHECODE** [learnpack/learnpack#1564]
Describe the bug:

**1. Exercise Name:** 04.1-Combined-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**3. Issue: Unable to reset exercise.

**Comment by tommygonzaleza** [comment]
We are still working to allow reseting all files, currently it only reset the entry file, in your exercises' case it's the HTML file
