### ISSUE TITLE
Excercise Bug: 21.3-Filter-list

### ISSUE THREAD

**Issue by alecisnero** [learnpack/learnpack#1565]
Describe the bug:

**1. Exercise Name:** 21.3-Filter-list

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by AnggieAlava** [comment]
Everything works as expected

![Image](https://github.com/learnpack/learnpack/assets/131820456/2e885416-0858-4623-9c0d-738a18ca421b)
