### ISSUE TITLE
Excercise Bug: 14-video-tag

### ISSUE THREAD

**Issue by MarcosVieco** [learnpack/learnpack#1566]
Describe the bug:

**1. Exercise Name:** 14-video-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Si quito el atributo "muted" no me reproduce el video, se queda parado en el primer fotograma y no escucho el sonido tampoco

**Comment by tommygonzaleza** [comment]
Ya esta funcionando
