### ISSUE TITLE
Excercise Bug: 00.1-Inline-Styles

### ISSUE THREAD

**Issue by jdugard3** [learnpack/learnpack#1567]
Describe the bug:

Instructions do not make sense... Background color is suppose to be green but according to the instructions its suppose to be orange. 
Also it states not to use the style tag, but how am I suppose to make the changes without using the tag? This may be user error. 

**1. Exercise Name:** 00.1-Inline-Styles

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by AnggieAlava** [comment]
This issue will be resolved in the next [task](https://github.com/breatheco-de/breatheco-de/issues/7057)
