### ISSUE TITLE
Build button doesn't update /dist folder

### ISSUE THREAD

**Issue by arnaldoperez** [learnpack/learnpack#1568]
**Describe the bug**
The build button doesn't update the folder for the preview. If you move to the next exercise and then go back, it does update the preview

**In what exercise**
[This exercise](https://github.com/arnaldoperez/javascript-events-tutorial-exercises) step 7

**Comment by tommygonzaleza** [comment]
Se resolvera [aqui](https://github.com/breatheco-de/breatheco-de/issues/7202)
