### ISSUE TITLE
Excercise Bug: 00.1-Inline-Styles

### ISSUE THREAD

**Issue by Kakomanato** [learnpack/learnpack#1569]
Describe the bug:

**1. Exercise Name:** 00.1-Inline-Styles

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

The index file seems to be related to another exercise. Also when the excersise is solved following the instructions, the testing feature refers to "setting the background of the table green" which has nothing to do with the instructions.

**Comment by tommygonzaleza** [comment]
we are working to solve this issue on a different one
