### ISSUE TITLE
Excercise Bug: 03-list-styling

### ISSUE THREAD

**Issue by MarcosVieco** [learnpack/learnpack#1572]
Describe the bug:

Si le doy a validar me pone que el ejercicio está bien pero aun no lo he empezado.

**1. Exercise Name:** 03-list-styling

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by AnggieAlava** [comment]
[Pull Request](https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/137)
