### ISSUE TITLE
Excercise Bug: 06-center-content

### ISSUE THREAD

**Issue by justicetrace** [learnpack/learnpack#1574]
Describe the bug:
Exercise does not instruct to make ".myDiv {background: grey;}.

**1. Exercise Name:** 06-center-content

**2. Repository URL:** https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises

**Comment by AnggieAlava** [comment]
Link to PR: https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/58
