### ISSUE TITLE
Excercise Bug: 01-Console

### ISSUE THREAD

**Issue by Carlos2607-a** [learnpack/learnpack#1575]
Describe the bug:

el learnpack no me funciona desde el local, no entiendo porque.

**1. Exercise Name:** 01-Console

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by tommygonzaleza** [comment]
Se va a resolver [aqui](https://github.com/breatheco-de/breatheco-de/issues/7090)

**Comment by Charlytoc** [comment]
¿Tienes la extensión de LearnPack instalada? @Carlos2607-a
