### ISSUE TITLE
Excercise Bug: 01-Style-tag

### ISSUE THREAD

**Issue by panf9** [learnpack/learnpack#1576]
Describe the bug:
hay un error en la escritura de la siguiente frase: Es importante **_clarar_** que tu codigo CSS debe estar encerrado dentro de etiquetas <style>.

debe decir: Es importante aclarar que tu codigo CSS debe estar encerrado dentro de etiquetas <style>.

**1. Exercise Name:** 01-Style-tag

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by AnggieAlava** [comment]
[Pull Request](https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/136)
