### ISSUE TITLE
Excercise Bug: 022-isEvenLength

### ISSUE THREAD

**Issue by Mogurkazan** [learnpack/learnpack#1577]
Describe the bug:

**1. Exercise Name:** 022-isEvenLength

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by AnggieAlava** [comment]
The exercise works properly.

![Image](https://github.com/learnpack/learnpack/assets/131820456/1d923baf-328e-4a58-b57c-363996b1cc5e)
