### ISSUE TITLE
Excercise Bug: 02-on-click-Hello-World

### ISSUE THREAD

**Issue by truittjanney** [learnpack/learnpack#1578]
Describe the bug:

**1. Exercise Name:** 02-on-click-Hello-World

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises

I have the exact html and JS document as the solution, and the alert showing "hello world" does not show.

**Comment by AnggieAlava** [comment]
[Pull Request](https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/36)
