### ISSUE TITLE
Bug in 01-Style-tag

### ISSUE THREAD

**Issue by gustarting** [learnpack/learnpack#1596]
Lesson: Learn CSS Interactively 
    
Explain the problem 
    Inline styles no tiene la opcion de Run tests(solo la opción de Run) y tampoco sale el check verde. Gracias :)
Provide an image or example of the problem 
![image](https://github.com/learnpack/learnpack/assets/89204234/4b7037b1-e528-4dde-aeed-a455bd11d6f7)

**Comment by tommygonzaleza** [comment]
Ya fue resuelto!
