### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by achaves100** [learnpack/learnpack#160]
# What was the expected behavior?

I am not able to save my work. I have "Autosave" activated, I have used "Save" and "Save All", and all my work is lost once I close the browser.

## Other details: 
1. All excercises
2. Current URL: https://bb78aaa8-66a9-4ca9-a5ec-88622879f61f.ws-us03.gitpod.io/#/workspace/css-tutorial-exercises-course

**Comment by ElviraQDP** [comment]
Hello, your work is not lost you should be able to find it on your workspaces in gitpod: https://gitpod.io/workspaces/
