### ISSUE TITLE
Learnpack no termina cuando todos los test son correctos, pero sí cuando uno falla

### ISSUE THREAD

**Issue by marcogonzalo** [learnpack/learnpack#1612]
Lesson: Installing Windows on a Virtual Machine 
    
Explain the problem 
Cuando todos los test pasan, Learnpack se queda (tal vez) en bucle y no muestra el resultado. Si cambio el archivo y pongo un dato que es incorrecto, sí me imprime los test buenos y los que fallan
    
Provide an image or example of the problem 
![Captura de pantalla de 2024-04-10 21-02-04](https://github.com/learnpack/learnpack/assets/410890/5b7b30bc-89bc-4b26-8b64-3cf58120b820)

**Comment by alesanchezr** [comment]
Se movio este issue a breatheco-de
