### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by TAPIAR7** [learnpack/learnpack#164]
# What was the expected behavior?
console.log('Good news! That color is available');
console.log('We are sorry, that color is not available');

Please take 2 minutes to explain what happened, include screenshot if possible.
It is not getting to correct result, I tried with another too, and my code works as expected, but in gitpod is not working fine.

Code:
function getColor(selection)
{
	switch(selection){
        // Add more options here
        case 'red':
            console.log('red')
            return true;
        case 'green':
            return true;
        case 'blue':
            return true;
	    default:
	    	return false;  //returns false because the user picked an unavailable color
	}
}

var colorname = prompt('What color do you want?');
console.log(colorname);
var isAvailable = getColor(colorname);

if(isAvailable)
	console.log('Good news! That color is available');
else 
	console.log('We are sorry, that color is not available');

## Other details: 
1. Exercises: 14-Your-first-switch
2. Current URL: https://c68ee087-4844-4dfd-9fa0-a69facc69f0f.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/21
Hrs: <hrs>0.5</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.5</hrs>
