### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by ginysp** [learnpack/learnpack#165]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.
The function calls 99 times and the compiler says no

// Your code here:
function song(){
    var lyric="";
    for(var i = 99;i<=99;i--)
    {
        if(i==1)
        {
            lyric += i + " bottle of milk on the wall, " +i+" bottle of milk. Take one down and pass it around, no more bottles of milk on the wall. No more bottles of milk on the wall, no more bottles of milk. Go to the store and buy some more";
            break;
        }else{
            lyric += i + " bottles of milk on the wall, " +i+" bottles of milk. Take one down and pass it around, ";
        }
    }
    return lyric;
}
console.log(song());

## Other details: 
1. Exercises: 24-Bottles-of-milk
2. Current URL: https://aabf51a7-fd4c-46b0-97b0-7befbe68625c.ws-us03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/21
Hrs: <hrs>0.8</hrs>

**Comment by tommygonzaleza** [comment]
Replace the first test of that exercise with a test that checks that the student is using a for loop.

**Comment by tommygonzaleza** [comment]
Test improved, now checking for all the possible values and that you do it with a for loop

PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/37
TOTAL Hours: <hrs>1.2</hrs>
