### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by alessf95** [learnpack/learnpack#1673]
Lesson: Javascript Events 
    
Explain the problem: learnpack doesnt allows to make the test, it's says "not test available" so it doesnt check that you finish an excercise.
    
Provide an image or example of the problem 

![image](https://github.com/user-attachments/assets/0f60bc06-0706-4a12-9217-00b3e2dda0c5)
![image](https://github.com/user-attachments/assets/923915dd-f9ab-4a29-9058-309f2d8b12a9)

**Comment by jseiglie** [comment]
It does not show on any exercises from the Javascript Events tutorial to run the test, displaying 'no test available'.
Expected behavior:
It should allow to run the test and provide feedback on the console
