### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by notanumber93** [learnpack/learnpack#17]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Grammar issue, in the instructions should sais "li" and not "il"

## Other details: 
1. Exercises: 09-formating-Text
2. Current URL: https://d1a33abd-74c8-47c2-a6f1-bbe5adb674b3.ws-us02.gitpod.io
3. Repository: unknown

**Comment by ElviraQDP** [comment]
the erro has been fixed. Thank you!
