### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by shepherdlewis000** [learnpack/learnpack#190]
# What was the expected behavior?

I'm getting failed tests for the first few exercises for an unknown reason, even if I just copy and paste the exact code as given...
 
01.1
![image](https://user-images.githubusercontent.com/71042305/108323924-7bb4cb80-7184-11eb-9c04-4fe63c5e3ef5.png)
![image](https://user-images.githubusercontent.com/71042305/108324180-cafafc00-7184-11eb-9d96-a626e120e0b9.png)
![image](https://user-images.githubusercontent.com/71042305/108324247-e1a15300-7184-11eb-9ba5-fdc58429dd90.png)
![image](https://user-images.githubusercontent.com/71042305/108324316-fa116d80-7184-11eb-9285-cffd2ff41cda.png)

01.2 (Instructions are entirely unclear and I think worded wrong, but I made an educated guess that this should pass
![image](https://user-images.githubusercontent.com/71042305/108324570-4fe61580-7185-11eb-9245-facd481368fc.png)
Because of the unclear directions I also tried with the name "John" 

If I look in the console window I see this...
![image](https://user-images.githubusercontent.com/71042305/108324778-93d91a80-7185-11eb-9753-05c7106dc267.png)

I had high hopes for these exercises. It's a shame all the work was put into them but they don't run correctly I think!

## Other details: 
1. Exercises: The first couple - I didn't go further because console froze up and I couldn't go to "Next"
2. Current URL: 
3. Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by tommygonzaleza** [comment]
It has been fixed with the new learnpack-react plugin
