### ISSUE TITLE
Excercise Bug number 19- for loops and arryays repl

### ISSUE THREAD

**Issue by DarioQuintanilla2109** [learnpack/learnpack#20]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.
<img width="733" alt="arrays_loops_repl" src="https://user-images.githubusercontent.com/50418335/91352101-59cf2300-e7b7-11ea-8632-6247d78e472b.PNG">

Console output same as instructions, not passing test. Included screen shot of code and results. 

## Other details: 
1. Exercises: 19-And-One-and-a-Two-and-a-Three
2. Current URL: https://f02feac9-57e0-4835-b20a-dca2cbdce106.ws-us02.gitpod.io
3. Repository: uknown

**Comment by DarioQuintanilla2109** [comment]
Number 19 on arrays and looping repl.

**Comment by tommygonzaleza** [comment]
The test is working fine, I just checked it!
