### ISSUE TITLE
javascript-arrays-exercises-tutorial / Ejercicio 21.3 / Test Not Working

### ISSUE THREAD

**Issue by emendez20** [learnpack/learnpack#201]
Hrs: <hrs>0.5</hrs>

**Describe the bug**
Las instrucciones dicen que la busqueda NO debe ser case sensitive. Pero el test espera lo siguiente:
    Expected substring: "Liam,William,James,Benjamin,Samuel,Camila"
    Received string:    "Liam,William,James,Benjamin,Amelia,Samuel,Camila

Eso deja por fuera a Amelia.

**In what exercise**
javascript-arrays-exercises-tutorial / Ejercicio 21.3

**Code**
```
let names = ['Liam','Emma','Noah','Olivia','William','Ava','James','Isabella','Logan','Sophia','Benjamin','Mia','Mason','Charlotte','Elijah','Amelia','Oliver','Evelyn','Jacob','Abigail','Lucas','Harper','Michael','Emily','Alexander','Elizabeth','Ethan','Avery','Daniel','Sofia','Matthew','Ella','Aiden','Madison','Henry','Scarlett','Joseph','Victoria','Jackson','Aria','Samuel','Grace','Sebastian','Chloe','David','Camila','Carter','Penelope','Wyatt','Riley'];

//declare your function here
function filterByName(arr,filterCriteria){
    let newArray = arr.filter(function(arr){
        return (arr.toLowerCase().includes(filterCriteria.toLowerCase()));
    });
    return newArray;
}
console.log(filterByName(names, 'am'));

```

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/13
Hrs: <hrs>0.5</hrs>
