### ISSUE TITLE
getAllElementsButNth is not working

### ISSUE THREAD

**Issue by chall298** [learnpack/learnpack#210]
Hrs: <hrs>0.5</hrs>

**Describe the bug**

getAllElementsButNth is not working, it says I got it right when its obviously incorrect

**In what exercise**
If applicable, what exercise were you trying to complete?

getAllElementsButNth

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

![getAllElementsButNth()](https://user-images.githubusercontent.com/49170970/110348596-d0b76500-7fff-11eb-9979-6e0b3eb265eb.png)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/31
Hrs: <hrs>0.5</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.5</hrs>
