### ISSUE TITLE
countAllCharacters is in spanish only!!!!

### ISSUE THREAD

**Issue by chall298** [learnpack/learnpack#216]
**Describe the bug**

its only has the Spanish version

**In what exercise**
If applicable, what exercise where you trying to complete?

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by ElviraQDP** [comment]
Could tell which exercise? or what tutorial were you working on?
