### ISSUE TITLE
Positional argument

### ISSUE THREAD

**Issue by williambarberjr** [learnpack/learnpack#221]
**Describe the bug**
1. Positional argument was required (i.e. def hello_world(todos = todos): instead of just def hello_world(todos):)

I would say broadly otherwise, it was never explained how to check if basic flask functions like jsonify are working - how to test them in the console etc. Would be useful for determining if the error was my use of flask.jsonify() instead of flask.json.jsonify() or something along those lines.

**In what exercise**
If applicable, what exercise where you trying to complete?
05 - Returning JSON

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by tommygonzaleza** [comment]
On which repository is this exercise located?
