### ISSUE TITLE
Translate error

### ISSUE THREAD

**Issue by Moskzow** [learnpack/learnpack#223]
**Describe the bug**
There is an error when you select the Spanish language. The Spanish word (imagen) is not there.

**In what exercise**
08 Imagen Redondeada

**Screenshot**
![Que_dice](https://user-images.githubusercontent.com/80925925/112183559-a9b38280-8bfe-11eb-9139-799b6f20eda0.jpg)

**Comment by ElviraQDP** [comment]
it has been fixed! thank you
