### ISSUE TITLE
Spanish Translation issue

### ISSUE THREAD

**Issue by bracket2code** [learnpack/learnpack#225]
**Describe the bug**
font-type is translated into font-size

**In what exercise**
06-Practicing-Rules

**Screenshot**
1. English [https://www.awesomescreenshot.com/image/7145252?key=492c93614fc9cd17686e268ac726429b](url)
2. Spanish [https://www.awesomescreenshot.com/image/7145285?key=d5737b8deb998a23c6a21fe438148cb2](url)

**Comment by ElviraQDP** [comment]
The problem has been fixed! thank you for letting us know!
