### ISSUE TITLE
Excercise Bug - React Exercises: 03.3-component-properties  (Test don't match with instructions)

### ISSUE THREAD

**Issue by marcogonzalo** [learnpack/learnpack#241]
Hrs: <hrs>0.5</hrs>

# What was the expected behavior?

The content (in spanish) ask for change from Bob Dylan to Paul McCartney but tests fail because are expecting Bob Dylan. The same happens with the rest of tests

## Other details: 
1. Exercises: 03.3-component-properties
2. Current URL: https://maroon-roadrunner-tlzof5tt.ws-eu03.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by tommygonzaleza** [comment]
Pull request created

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/42
Hrs: <hrs>0.5</hrs>
