### ISSUE TITLE
Exercise 21 "The Beatles"

### ISSUE THREAD

**Issue by sara-tustra** [learnpack/learnpack#244]
Hrs: <hrs>0.5</hrs>

**Describe the bug**

The exercise doesn't solve, i tried concatenating a string with line breaks and i tried printing in loops all with the expected output and still have issues, I attached screenshots
![Captura de Pantalla 2021-05-14 a la(s) 15 03 08](https://user-images.githubusercontent.com/77685910/118316991-80f48e80-b4c5-11eb-8c07-ae86aedd4d70.png)
![Captura de Pantalla 2021-05-14 a la(s) 15 02 17](https://user-images.githubusercontent.com/77685910/118317038-8fdb4100-b4c5-11eb-8ed3-5dd74682b071.png)

**In what exercise**
If applicable, what exercise where you trying to complete?

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by tommygonzaleza** [comment]
Pull request sent!

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/24
Hrs: <hrs>0.5</hrs>

**Comment by alesanchezr** [comment]
Maybe this bug is done, but please re-do the test based on what we did for js

**Comment by alesanchezr** [comment]
<hrs>0.95</hrs>
