### ISSUE TITLE
Excercise Bug :  Test case needs to be updated to reflect dynamic time.

### ISSUE THREAD

**Issue by brootware** [learnpack/learnpack#245]
# What was the expected behavior?
The test is asserting to expect static time out put of ```Current time: 19 hrs 45 min and 06 sec```

Following the instruction the learner will not be able to pass the test without this knowledge as the instruction is to print out current time from API request.

Test case to this exercise link is here - https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises/blob/master/exercises/04-response-body-json/test.py

## Other details: 
1. Exercises: 04-response-body-json
2. Current URL: https://amethyst-piranha-3bc6ycng.ws-us04.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises

**Comment by alesanchezr** [comment]
Yes but the test is mocking the API endpoint, so its ok to expect a specific time.
