### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by N-Archer** [learnpack/learnpack#248]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

In the React Tutorial Exercises (03.2), the image link is dead, providing the classic, "File Not Found".

I recommend this image or similar:
https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Bob_Dylan_-_Azkena_Rock_Festival_2010_2.jpg/800px-Bob_Dylan_-_Azkena_Rock_Festival_2010_2.jpg

Hope this helps,
Nate

## Other details: 
1. Exercises: 03.2-a-real-component
2. Current URL: https://purple-ocelot-0x92btuz.ws-us08.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by ElviraQDP** [comment]
Thank you!!! :))
