### ISSUE TITLE
Error Test Function EuroToDollar

### ISSUE THREAD

**Issue by legg2710** [learnpack/learnpack#249]
let oneEuroIs = {
    "USD": 1.206,
    "JPY": 127.9,
    "GBP": 0.8,
}

function fromEuroToDollar(a){
  return a * oneEuroIs["USD"]

}

const dollars = fromEuroToDollar(1000)

console.log(dollars)
<------------------------------------------------->
  ● One euro should be 1.206 dollars

    TypeError: fromEuroToDollar is not a function

      4 |
      5 |     // use the function like its suppoed to be used
    > 6 |     const dollars = fromEuroToDollar(3.5)
        |                     ^
      7 |
      8 |     // if 1 euro are 1.206 dollars, then 3.5 euros should be (3.5 * 1.2)
      9 |     const expected = 3.5 * 1.2; 

      at Object.<anonymous> (test.js:6:21)

  console.log
    1206

**Comment by tommygonzaleza** [comment]
On which repository is it located?
