### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by jdglez91** [learnpack/learnpack#25]
# What was the expected behavior?
not passing the test
Please take 2 minutes to explain what happened, include screenshot if possible.

## Other details: 
1. Exercises: 01.4-building-a-layout
2. Current URL: https://da2d8678-5743-43c4-b5bb-c1c8b4d212ff.ws-us02.gitpod.io
3. Repository: uknown

**Comment by alesanchezr** [comment]
Can you be more explicit?
