### ISSUE TITLE
06 Constantes

### ISSUE THREAD

**Issue by legg2710** [learnpack/learnpack#250]
No se anexo el video tutorial al ejercicio pero si esta disponible en youtube.

**Comment by ElviraQDP** [comment]
podrías indicarme en que repositorio?

**Comment by legg2710** [comment]
Hola elvira, es este:
https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by ElviraQDP** [comment]
esta funcionando!
