### ISSUE TITLE
Problema con el test unitario de https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

### ISSUE THREAD

**Issue by legg2710** [learnpack/learnpack#253]
**Describe the bug**
La terminal no arroja los resultados que se imprimen segun lo solicitado en el ejercicio.

**In what exercise**
07.2 Letter Counter

**Screenshot**
![image](https://user-images.githubusercontent.com/83027075/121749999-8ac7dc80-cad9-11eb-9118-d29d6c6c206b.png)
![image](https://user-images.githubusercontent.com/83027075/121750040-9fa47000-cad9-11eb-85c9-164491ee6e32.png)

Segun las instrucciones del tutorial en la segunda screenshot la terminal deberia mostrar de manera ordenada la cantidad de letras en el texto.

Code:

let par = "Lorem ipsum dolor sit amet consectetur adipiscing elit Curabitur eget bibendum turpis Curabitur scelerisque eros ultricies venenatis mi at tempor nisl Integer tincidunt accumsan cursus"
let counts = {};

for(let i in par){
    const letter = par[i].toLowerCase();
    console.log(letter);
    if(letter == " ") continue;
    else if(counts[letter] == undefined){
        console.log("Found "+letter+" for the first time")
            counts[letter] = 1;
    } 
    else {
         console.log("Found "+letter+" more than once")
          counts[letter] =  counts[letter] + 1;
    }
    
}
console.log(counts);

**Comment by legg2710** [comment]
Repositorio:
https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Comment by tommygonzaleza** [comment]
El test está funcionando bien, lo único es que pide que solo se utilice un console.log() al final del ejercicio y esta condición no se cumple en tu código.

**Comment by tommygonzaleza** [comment]
The test is working fine, the problem is that they are only asking to use one console.log() at the end of the exercise and you are not matching that condition on your code.

**Comment by ElviraQDP** [comment]
gracias @tommygonzaleza !
