### ISSUE TITLE
English selected but Spanish shown

### ISSUE THREAD

**Issue by YodaFace** [learnpack/learnpack#257]
**Describe the bug**
While working on the exercise, it shows the US flag (for english) selected, but the instructions show in Spanish. No hablo espanol. 

**In what exercise**
If applicable, what exercise where you trying to complete? 91 countAllCharacters
![Screen Shot 2021-06-14 at 1 39 55 PM](https://user-images.githubusercontent.com/13352282/121942544-39586100-cd16-11eb-97c5-b33070288dee.png)

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by ElviraQDP** [comment]
en que repositorio?

**Comment by ElviraQDP** [comment]
Hi,  it has been fixed!
