### ISSUE TITLE
El ejercicio no se ejecuta

### ISSUE THREAD

**Issue by diegoejp** [learnpack/learnpack#259]
Este error aparece:
File "/workspace/python-beginner-programming-exercises/exercises/07-Create-a-Basic-HTML/app.py", line 10
SyntaxError: Non-ASCII character '\xe2' in file /workspace/python-beginner-programming-exercises/exercises/07-Create-a-Basic-HTML/app.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by tommygonzaleza** [comment]
Tendría que ver tu código para ver por qué te sale ese error. Yo lo acabo de hacer y me funcionó perfecto.
