### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Carlos84sh** [learnpack/learnpack#26]
# What was the expected behavior?

don´t have the close in body </body>

Please take 2 minutes to explain what happened, include screenshot if possible.

## Other details: 
1. Exercises: 05-Specificity
2. Current URL: https://d8532b1f-80ef-4d52-a481-411f89ef9b56.ws-eu01.gitpod.io
3. Repository: uknown

**Comment by ElviraQDP** [comment]
podrias ser más específico por favor?
