### ISSUE TITLE
Exercise Bug

### ISSUE THREAD

**Issue by brcre001** [learnpack/learnpack#262]
# What was the expected behavior?

My code works but the test doesn't approve it.
```
window.onload = function() {
	console.log("The website was loaded...");
	let countries = ["USA", "France", "Italy", "Brazil", "Colombia", "Belize", "Venezuela"];

	// your code here
	let selector = document.querySelector("#mySelect");
	countries.map(element => {
		let option = document.createElement("option");
		option.innerHTML = element;
		selector.appendChild(option);
	});

	selector.addEventListener("change", function(event) {
		alert(event.target.value);
	});
};
```

Please take 2 minutes to explain what happened, include screenshot if possible.

## Other details: 
1. Exercises: 13-Add-Options-to-the-Select
2. Current URL: https://crimson-rat-m9zudh74.ws-us09.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by tommygonzaleza** [comment]
This is the same issue as #192 which has been solved before.
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/19
