### ISSUE TITLE
issues with notes lesson 80

### ISSUE THREAD

**Issue by Joshfishman97** [learnpack/learnpack#264]
**Describe the bug**
If the array at the given key is empty, it should return 0.
If the property at the given key is not an array, it should return 0.
If there is no property at the given key, it should return 0.
in the message in the beginning of notes it at the first note. if the given key is an array and the array is empty return 0.
**In what exercise**
80

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by tommygonzaleza** [comment]
Hello Josh how is it going? Can you describe what the error is?
