### ISSUE TITLE
lesson 23 of math.js

### ISSUE THREAD

**Issue by Joshfishman97** [learnpack/learnpack#265]
**Describe the bug**
the instructions are misleading, instead of the test output saying " x (fail) 2. The output in the console should match the one in the instructions! " they should say "The output in the console should return an object with occupied,total and available slots just like the one in the instructions, but with different numbers that match with the smaller parking state"
**In what exercise**
If applicable, what exercise where you trying to complete?

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by ElviraQDP** [comment]
could you tell us what exercises are you working on?
