### ISSUE TITLE
91 countAllCharacters 

### ISSUE THREAD

**Issue by Joshfishman97** [learnpack/learnpack#267]
**Describe the bug
The instructions are only written in Spanish.

**In what exercise**
If applicable, what exercise where you trying to complete?

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).

**Comment by ElviraQDP** [comment]
Hello! could you please tell me what repo are you working? which exercises?
