### ISSUE TITLE
 Remove DOM Element: Part Two

### ISSUE THREAD

**Issue by Joshfishman97** [learnpack/learnpack#268]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.
change this one to ```expect(document.querySelector).toHaveBeenCalledWith("#parentLi");```
this ONE ```expect(document.querySelector).toHaveBeenCalledWith("#parentLI");```

## Other details: 
1. Exercises: 09-Remove-DOM-Element-part-two
2. Current URL: https://moccasin-dragonfly-2k5z2dw1.ws-us11.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by ElviraQDP** [comment]
this issue has been solved
