### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by GMDEEP** [learnpack/learnpack#272]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.
Added an Index.html for browser

## Other details: 
1. Exercises: 04-conditional-rendering
2. Current URL: https://turquoise-lynx-8wumx74h.ws-us11.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by GMDEEP** [comment]
Exercise is missing an index.html file inside the dist folder

**Comment by ElviraQDP** [comment]
issue fixed
