### ISSUE TITLE
Hello without head

### ISSUE THREAD

**Issue by kiddopro** [learnpack/learnpack#275]
**Describe the bug**
The screenshot speaks for itself, in the exercise it asks to create an html structure without a head and with an h1 in the body. But it keeps marking that there is a head or title.

**In what exercise**
Exercise 3 Hello without head.

**Screenshot**
https://www.awesomescreenshot.com/image/11130465?key=e25d82fe4cd816a3e8e7ce317bf4b2ad

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/24
Hrs: <hrs>0.1</hrs>
