### ISSUE TITLE
Test Error- (01.2) Like MS Word

### ISSUE THREAD

**Issue by al4142** [learnpack/learnpack#280]
**Describe the bug**
Its building exactly what the instructions are asking for. But the test is not passing. 

**In what exercise**
If applicable, what exercise where you trying to complete?
repository https://github.com/4GeeksAcademy/html-tutorial-exercises-course
(01.2) Like MS Word

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).
![image](https://user-images.githubusercontent.com/87880461/127397455-f22eba14-8716-4ed5-af00-26afee481fc6.png)

**Comment by ElviraQDP** [comment]
as in Microsoft Word?
