### ISSUE TITLE
Migrate bootstrap exercises to bootstrap 5

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#281]
https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/19
Hrs: <hrs>2.75</hrs>

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/23
Missing PR

**Comment by alesanchezr** [comment]
<hrs>2.75</hrs>
