### ISSUE TITLE
Change all learnpack exercises images to relative paths

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#282]
Instead of absolute paths like:

```
![01.1 Preview HTML Exercises](https://github.com/4GeeksAcademy/html-tutorial-exercises-course/blob/master/.learn/assets/01.2-Like-Word.png?raw=true)
```

We should use:
```
![01.1 Preview HTML Exercises](../assets/01.2-Like-Word.png?raw=true)
```

Depending on where the `exercises` folder is, you need to add `../` or `../../`. 

Incremental exercise have `../../` because the exercise folder is inside ./learn.
Isolated exercises have `../` (just one) because the exercise folder is don't the root of the repo.

Make sure the image works (not broken) on gitpod and also on github.

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/77

**Comment by tommygonzaleza** [comment]
- [ ]  Build a postcard using HTML/CSS
- [ ]  HTML5 Forms (10 hrs)
- [ ]  Learn CSS (10 hrs)
- [ ]  Learn CSS Layouts (4 hrs)
- [ ]  Learn Bootstrap (10 hrs)
- [ ]  Introduction to The DOM (4 hrs)
- [ ]  Events inside The DOM (4 hrs)
- [ ]  Looping with Javascript (8 hrs)
- [ ]  Javascript Functions (2 hrs)
- [ ]  Object Oriented Programmming is Javascript
- [ ]  Master Javascript with 150 exercises (50 hrs)
- [ ]  Learn React.js (3 hrs)
- [ ]  Unit testing with Jest (2 hrs)
- [ ]  Python for Beginners (20 hrs)
- [ ]  Practice Looping Lists and Tuples (30 hrs)
- [ ]  Practice functions (10 hrs)
- [ ]  Master Python (50 hrs)
- [ ]  Python API Requests (10 hrs)
- [ ]  Build API's with Python Flask

**Comment by ElviraQDP** [comment]
- Build a postcard using HTML/CSS - was already done
- Learn HTML - PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/46
-  HTML5 Forms (10 hrs) - https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/20
-  Learn CSS (10 hrs) - https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/45
-  Learn CSS Layouts (4 hrs) - was already done
-  Learn Bootstrap (10 hrs) - was already done
-  Introduction to The DOM (4 hrs) - was already done
-  Events inside The DOM (4 hrs) - has no images
- Javascript for Beginners - has no images
-  Looping with Javascript (8 hrs) - has no images
-  Javascript Functions (2 hrs) - was already done
-  Object Oriented Programmming is Javascript - has no images
-  Master Javascript with 150 exercises (50 hrs) -has no images
-  Learn React.js (3 hrs) - https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/81 (Learnpack is failing)
-  Unit testing with Jest (2 hrs) - already done
-  Python for Beginners (20 hrs) - has no images
-  Practice Looping Lists and Tuples (30 hrs) - has no images
-  Practice functions (10 hrs) - has no images
-  Master Python (50 hrs) -has no images
-  Python API Requests (10 hrs) - has no images
-  Build API's with Python Flask- has no images
-

**Comment by tommygonzaleza** [comment]
There are some changes requested on 

- Learn HTML: https://github.com/learnpack/learnpack/issues/561 4GeeksAcademy/html-tutorial-exercises-course#46

**Comment by tommygonzaleza** [comment]
Waiting for the HTML forms approval
