### ISSUE TITLE
Re-do tests about the DOM using the dom.js library.

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#283]
This is the dom.js library with some examples:

https://github.com/breatheco-de/exercise-postcard/tree/main/.learn/utils

**Comment by alesanchezr** [comment]
I alreadi re-did everything until 09.. we have to finish from 09 until the end.

**Comment by tommygonzaleza** [comment]
I'm having the same problem of this other issue (https://github.com/learnpack/learnpack/issues/328) on the tenth exercise.

I have to check something that happens after clicking a button, but I don't know how to do that

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/35
Hrs: <hrs>4.45</hrs>
