### ISSUE TITLE
Fix pre-filling for issues on learnpack-ide when click on reporting a new bug

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#284]
Hrs: <hrs>1.5</hrs>

Just make sure that the url that the student is redirected to, includes pre-filled all the necessary information about the exercise, here is the solution:

https://github.com/Omonroy36/breathecode-ide/blob/a791105f02c19d0cf881f087ba24262db75acef6/src/js/components/sidebar/sidebar.js#L33

**Comment by tommygonzaleza** [comment]
PR: https://github.com/learnpack/coding-ide/pull/3
Hrs: <hrs>1.5</hrs>

**Comment by tommygonzaleza** [comment]
It is not working, it's not using the template @alesanchezr
