### ISSUE TITLE
Improve bootstrap exercises' tests

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#289]
**Is your feature request related to a problem? Please describe.**
Some of these tests don't have the best solution, we should improve them.

**Additional context**
Repository: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/21
Hrs: <hrs>2.3</hrs>

**Comment by tommygonzaleza** [comment]
PR: 4GeeksAcademy/bootstrap-exercises-tutorial#23
Missing PR

**Comment by alesanchezr** [comment]
<hrs>2.3</hrs>
