### ISSUE TITLE
The tests for `python-lists-loops` /  `12.4-Map_list_of_objects` are not working

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#291]
This is a bug reported a year ago, but I want to check if it is still true:
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/395

https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/tree/master/exercises/12.4-Map_list_of_objects

**Comment by tommygonzaleza** [comment]
It is working now.
Hrs: <hrs>0.05</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.05</hrs>
