### ISSUE TITLE
Python Test `python-beginner`  Exercise 9

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#292]
Original issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/454

Exercise 9 in python-beginner-programming-exercises

x (fail) 0. You should update only line 5 using randint()

This error appears even when you only edit that line

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/31
Hrs: <hrs>0.5</hrs>
