### ISSUE TITLE
Tutorial de ejercicio de 12 HTML no sigue las instrucciones

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#293]
Tutorial de ejercicio de 12 HTML no sigue las instrucciones

Original issue:

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/545

**Comment by alesanchezr** [comment]
The wrong conflict was resolved, its ok that you soved another one.

But the code on the PR 26 is not reflected on master, probably because you deleted your fork and forked again, make sure to reflect the fixed on those exercises into your new master and PR agan.

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/47
TOTAL Hours: <hrs>1.05</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1.05</hrs>
