### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Carlos84sh** [learnpack/learnpack#30]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Well, The exercise is fine. The only problem is the resolution video not working

## Other details: 
1. Exercises: 06-Constants
2. Current URL: https://d847fc27-fa8d-4d6e-8475-1f9a3e867fa4.ws-eu01.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by ElviraQDP** [comment]
Thank you for letting us know! We will try to improve it
