### ISSUE TITLE
Exercise correct, correction fail

### ISSUE THREAD

**Issue by Folkenciyo** [learnpack/learnpack#300]
**Describe the bug**
I have built the exercise correctly appearing on the webside "HTML tag are similar to MS Word elements" and still correcting as a wrong exercise.
I have writed like that:

<!DOCTYPE html>
<html>
	<body>
		<p>HLTM tags are similar to MS Word elements</p>
	</body>
</html>

Also like that:

<p>HLTM tags are similar to MS Word elements</p>

**In what exercise**
this exercise is the 1.2 on the begining

**Screenshot**
https://www.awesomescreenshot.com/image/11544513?key=d4dcb1118d6fbcd60ebc6f51347a077d

**Comment by ElviraQDP** [comment]
@tommygonzaleza this is the second issue with this unit testing. Could  you check it please?

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/26
Hrs: <hrs>0.1</hrs>

**Comment by tommygonzaleza** [comment]
Conflict Solved.
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/32
Hrs: <hrs>0.15</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.15</hrs>
