### ISSUE TITLE
Learnpack `test` command

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#302]
The test command can receive the name of the exercise as an argument:

```bash
# test all exercises
learnpack test

# test only one exercise
learnpack test 01-hello-world
```
- [ ] optionally accept one single exercise name, if given, instead of running all tests run only the ones for that exercise
- [ ] Detect each exercise language using the `detect` function already developed.
- [ ] Make sure you re-use the current code, the same functions already being used by the start command.
- [ ] Develop unit tests for the command
- [ ] Depending on the language use respective plugin to test
- [ ] The command will print the stdout on the terminal and exit with process.exit(1) if error or process.exit(0) if success.

**Comment by ajoseerazo** [comment]
Working on this

**Comment by ajoseerazo** [comment]
8h
