### ISSUE TITLE
Python Beginner Exercises - 18 - The Beatles

### ISSUE THREAD

**Issue by brcre001** [learnpack/learnpack#303]
**Describe the bug**
The app.py did not pass the test because of having a blank line between line 1 (the comment) and the line where I define my function.

**In what exercise**
Python Beginner Exercises - 18 - The Beatles

**Screenshot**
![18BeatlesProblem](https://user-images.githubusercontent.com/83432261/128419549-f8581b2c-de55-4f9d-837f-7adae73ee0dd.png)
![18BeatlesSolution](https://user-images.githubusercontent.com/83432261/128419558-1c798374-b0d3-4308-bcee-0dc71c03fdf7.png)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/31
Hrs: <hrs>0.5</hrs>
