### ISSUE TITLE
Excercise Bug devuelve un error  x (fail) 0. The function rapid must receive one string and return the same but without the last letter and uppercase 

### ISSUE THREAD

**Issue by fernandoavilesrosado** [learnpack/learnpack#309]
1.Exercise Name: 07-lambda-function-two

2.Repository URL: https://github.com/4GeeksAcademy/python-functions-programming-exercises

**Comment by fernandoavilesrosado** [comment]
El error devuelto no coincide con lo que se pide en el enunciado del ejercicio.

**Comment by tommygonzaleza** [comment]
The test is working fine.
Hrs: <hrs>0.1</hrs>
