### ISSUE TITLE
Excercise 20 Bug on linkt to replit

### ISSUE THREAD

**Issue by marcogonzalo** [learnpack/learnpack#31]
The exercise 20, (ES & EN) has a link to Arrays repl.it classroom https://repl.it/classroom/invite/BB4WDpk and some people says they can't access (I can), I don't know if it's because of some access restrictions from Replit.

**Comment by alesanchezr** [comment]
I think so, I will delete that link thank you!

**Comment by alesanchezr** [comment]
What is this class? Javascript arrays?

**Comment by ElviraQDP** [comment]
yes, I fix it
