### ISSUE TITLE
Issue with Test on Exercise 20.5 Map array of objects

### ISSUE THREAD

**Issue by paola9896** [learnpack/learnpack#310]
**Describe the bug**
When I test the exercise, one date of birth does not match the expected output (name: 'Joe', birthDate: new Date(1986,10,24)). However, the other outputs are correct.

**In what exercise**
 20.5 Map array of objects - 
https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).
![Capture](https://user-images.githubusercontent.com/74715265/128746271-1eeff673-d6ae-4c80-93fa-b78a25b83173.PNG)

**Comment by ElviraQDP** [comment]
the test expects to get them all right...

**Comment by paola9896** [comment]
Thank you for replying.
