### ISSUE TITLE
Bug in exercise 25 Techno Beats

### ISSUE THREAD

**Issue by paola9896** [learnpack/learnpack#311]
**Describe the bug**
The test asks for a function that does not exist.

**In what exercise**
https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial -- 25 Techno Beats

**Screenshot**
If possible, add a screenshot of the error. You can use [awesome screenshot for free](https://www.awesomescreenshot.com/).
![image](https://user-images.githubusercontent.com/74715265/128749652-ab3b297a-364f-4243-9a39-7bf3c0027150.png)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/27
Hrs: <hrs>0.3</hrs>
