### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Folkenciyo** [learnpack/learnpack#315]
1.Exercise Name: 02-create-index

2.Repository URL: https://github.com/breatheco-de/exercise-postcard

On the first instruction, once you test it, apear the next error message. And don´t let to continue because you need to test it before to continue.

![image](https://user-images.githubusercontent.com/86403857/128879739-1404991f-9628-4414-8c6a-6c102892b93f.png)
https://www.awesomescreenshot.com/image/11786238

**Comment by ElviraQDP** [comment]
@tommygonzaleza this is second issue regarding this test, would you mind checking? It might be just the internet but just in case..

**Comment by Folkenciyo** [comment]
100% solve! now I don´t have any problem. Thank you very much
