### ISSUE TITLE
Fix PR for CSS exercises.

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#316]
A lot of the exercises have the same issue with the test (I think all of them)
Exercise:
![image](https://user-images.githubusercontent.com/56565994/128926849-25c30e6d-4a3a-48f8-83f6-47cad7d7073b.png)

Test:
![image](https://user-images.githubusercontent.com/56565994/128926890-2b35bbb8-0ad8-4b01-908d-1762ccdf577e.png)

1.Exercise Name: 01.2-Your-First-Style

2.Repository URL: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/27
Hrs: <hrs>0.4</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.5</hrs>
