### ISSUE TITLE
The test is asking for an incorrect url- -06-Practicing-Rules

### ISSUE THREAD

**Issue by Norbert305** [learnpack/learnpack#319]
1.Exercise Name: 06-Practicing-Rules

2.Repository URL: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

![image](https://user-images.githubusercontent.com/83515541/129488731-c0dc2781-5c34-4f46-92dd-f734e16dc07c.png)

**Comment by ElviraQDP** [comment]
fixed
