### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by karinagiuseppina** [learnpack/learnpack#321]
1.Exercise Name: 03.2-a-real-component

2.Repository URL: https://github.com/4GeeksAcademy/react-tutorial-exercises

The link used for the image is different than the one that is compared in the text, so it reports it as a test fail even though it is the link that is given to us in the instructions. This also happens on th previous excercisas where Bob Dylan images is required.

**Comment by tommygonzaleza** [comment]
Same issue as https://github.com/learnpack/learnpack/issues/296

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/64
Hrs: <hrs>0.15</hrs>
