### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by pickelmikel** [learnpack/learnpack#323]
1.Exercise Name: 01.2-Retrieve-items

2.Repository URL: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

Line 5 of exercise states "# Print in the console the 4th element on the list `spanish_translations`   "
    However, my_list is the only list and was confused.  The Exercise only wanted the 4th element in my_list.
        print(my_list[3])

Maybe the exercies just needs a spanish_translations list?
I would love to help fix issues, but just wanted to point this out.  Thanks!

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/58
Hrs: <hrs>0.05</hrs>
