### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by victorbstan** [learnpack/learnpack#326]
1.Exercise Name: 03.2-a-real-component

2.Repository URL: https://github.com/4GeeksAcademy/react-tutorial-exercises

The validation test does not have the same provided data from the example:
```
 <img
          alt="Card image cap"
          className="card-img-top"
    -     src="https://ucarecdn.com/f8cf81eb-3bab-4bba-9431-668884eab174/-/resize/300x/"
    +     src="https://github.com/4GeeksAcademy/react-tutorial-exercises/blob/master/.learn/assets/Dylan.png?raw=true"
        />
        ```

**Comment by tommygonzaleza** [comment]
This issue has been solved before. The PR has been approved already.
Hrs: <hrs>0.05</hrs>
