### ISSUE TITLE
Excercise Bug: 10-Render-on-Click

### ISSUE THREAD

**Issue by Gitalus** [learnpack/learnpack#328]
1.Exercise Name: 10-Render-on-Click

2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

In the exercise i used this code, it works, but the test says i didn't made a innerHTML = "Hello World":

let button = document.querySelector("#superDuperButton");

button.addEventListener("click", function() {
	//your code here
	const divAmarillo = document.createElement('div');
	divAmarillo.style.background = "yellow";
	divAmarillo.innerHTML = "Hello World";
	document.querySelector('body').appendChild(divAmarillo);
});

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/27
Hrs: <hrs>0.2</hrs>

**Comment by alesanchezr** [comment]
This test is to specificy and probably will fail 99% fo the time, just make sure that these two instructions are in compliance:

```
Using the createElement function, create a div container with yellow background and "Hello World" as innerHTML.
Then append that div into the body of the website when the users clicks on the #superDuperButton
```

You can do that by looking for all divs and making sure there is one with the correct background and innerHTML.
Mock the createElement and make sure the div is an immediate child of the body.

**Comment by tommygonzaleza** [comment]
This issue is being fixed on another issue (https://github.com/learnpack/learnpack/issues/283)
