### ISSUE TITLE
Two exercises have the number 9 

### ISSUE THREAD

**Issue by gmihov001** [learnpack/learnpack#33]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

## Other details: 
1. Exercises: 09-Before-and-After
2. Current URL: https://aacb9bc8-0327-4bb4-8f98-2e5383a8499f.ws-us02.gitpod.io
3. Repository: uknown

**Comment by ElviraQDP** [comment]
could you be more explcit?

**Comment by ElviraQDP** [comment]
we already fixed it!
