### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by CRodr86** [learnpack/learnpack#331]
![bug12html](https://user-images.githubusercontent.com/88427335/130062284-81f2996b-9dd1-4449-b88c-4016ce5fce3b.jpg)
1.Exercise Name: 12-my-first-table

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
The issue is already been fixed
