### ISSUE TITLE
Crear una lista DOM list de li- exercise 7 The dom

### ISSUE THREAD

**Issue by LewLeal** [learnpack/learnpack#332]
1.Exercise Name: 07-Create-DOM-list-of-li
Test validation is wrong! for it to work, the li tags must be capitalized (LI)
2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by ElviraQDP** [comment]
@tommygonzaleza  este es el ejercicio que genera confunsion p los li no se usan en mayuscula (ver imagen de ejemplo) entonces yo cambie todo el test y la app.js para que funcionara, lo puedes revisar porfa? gracias
