### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by rcavero** [learnpack/learnpack#333]
1.Exercise Name: 09-formating-Text

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Creo que hay un bug, por lo que he comentado por slack, aunque no estoy del todo seguro.
Con el código que he hecho se reproduce exactamente lo que pide el ejercicio, exactamente con el mismo formato, pero aún así me dan 2 errores:
x (fail) 3. Two(4) <p> exist
x (fail) 4. Two(1) <strong> exist

De todos modos, adjunto mi código para que se pueda comprobar si es así:

`<!DOCTYPE html>
<html>
	<head>
		<title>4Geeks Academy</title>
		<style>
			blockquote {
				border-left: 2px solid red;
				background: #fbfbfb;
				padding: 5px;
			}
		</style>
	</head>
	<body>
		<h1>This wil be your heading</h1>
		<p>Then, you start talking about some interesting stuff that nobody wants to read</p>
		<p>Then you can <b>quote</b> someone to add credibility:</p>
		<blockquote>
			<p>A quotation is a handy thing to have about, saving one the trouble of thinking for oneself, always a laborious business</p>
			<p>- A.A. Milne, If I May</p>
		</blockquote>
		<p>Finally you can have some bullets to summarize everything, after all, new generations have this things in common:</p>
		<ul>
			<li>Don't like to read long texts.</li>
			<li>Have the spawn of attention of a bird.</li>
			<li>Skip long paragraphs straight to the bullet points</li>
		</ul>
	</body>
</html>`

Gracias y un saludo, Ramón

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/31
Hrs: <hrs>0.15</hrs>
