### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by rcavero** [learnpack/learnpack#334]
1.Exercise Name: 10-replicate-html

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Ocurre lo mismo que el anterior ejercicio en éste. Me da los siguientes errores:

✓ (done) 0. Order of html tags
     ✓ (done) 1. <h1> tag & innerHTML Exist
     x (fail) 2. <h2> tag & innerHTML Exist
     x (fail) 3. All <p> tags and innerHTML Exist
     ✓ (done) 4. <ol> Exist
     ✓ (done) 5. <ul> Exist
     ✓ (done) 6. <li> Exist
     x (fail) 7. <li> Inner HTML Exist
     ✓ (done) 8. <a> tag and href Exist

En cambio, con el código que he hecho consigo exactamente el resultado que pide el ejercicio. Adjunto el código:

<!DOCTYPE html>
<html>
	<head>
		<title>4Geeks Academy</title>
	</head>
	<body>
		<h1>The learning essay</h1>
		<h2>3 reasons you know you are learning</h2>
		<p>We are going to explain in this paragraph the 3 most common signs that you should look into yourself to recognize if you are learning.</p>
		<ol>
			<li>You are able to complete the exercises by yourself.</li>
			<li>You understand what the teacher is talking about</li>
			<li>You are able to have conversations about the topic</li>
		</ol>
		<h2>3 reasons you know love what you are learning</h2>
		<ul>
			<li>Time passes fast.</li>
			<li>You are anxious to finish this exercise and start the next one.</li>
			<li>Is 12am and you don't want to go to sleep.</li>
		</ul>
		<p>If you can't sleep, what better than watching videos of cats? <a href="">click here</a></p>
	</body>
</html>

Gracias y un saludo,
Ramón

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/32
Hrs: <hrs>0.5</hrs>

**Comment by alesanchezr** [comment]
resolver conflicto del PR

**Comment by alesanchezr** [comment]
<hrs>0.5</hrs>
