### ISSUE TITLE
Exercise Bug

### ISSUE THREAD

**Issue by jaimecr24** [learnpack/learnpack#336]
1.Exercise Name: 08-relative-vs-absolute-path-anchor-tag

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

![image](https://user-images.githubusercontent.com/67288569/130319676-0c2374e4-4e6a-44de-a96a-74cbab349f78.png)

He puesto el código con el camino relativo al ejercicio 3 pero continuamente me da error.

**Comment by ElviraQDP** [comment]
![Error](https://user-images.githubusercontent.com/63673743/130486623-3ccfa079-1587-4bcd-bb69-08447076db7f.png)

**Comment by ElviraQDP** [comment]
that's the result when I tried the exercise

**Comment by ElviraQDP** [comment]
Hols, estamos trabajando en esto!

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/32
Hrs: <hrs>0.1</hrs>
