### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by jamaldonadoa** [learnpack/learnpack#340]
Hrs: <hrs>0.1</hrs>

1.Exercise Name: 09-formating-Text

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

![image](https://user-images.githubusercontent.com/89169301/130534373-57fb99d8-7bdc-410c-a94e-68ce71df1c9b.png)

A pesar de contar con una etiqueta <p> la validación indica no tenerla.

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/32
Hrs: <hrs>0.1</hrs>

**Comment by alesanchezr** [comment]
Hrs: <hrs>0.1</hrs>
