### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by plopez1985** [learnpack/learnpack#341]
1.Exercise Name: 01.2-Like-Word

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course
![image](https://user-images.githubusercontent.com/89365508/130552374-0012ea3c-e02b-49ef-a6d4-c5fde3c3c06b.png)

**Comment by tommygonzaleza** [comment]
The test is working fine, I guess this was fixed already.
Hrs: <hrs>0.05</hrs>
