### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by VicDario** [learnpack/learnpack#344]
1.Exercise Name: 25-Techno-beat

2.Repository URL: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial

Testing your exercise using the node engine.
Socket error: testing-error   ● The output in the console should match the one in the instructions!

    TypeError: console.log.trim is not a function

      46 |     let _test4 = _lyricsGenerator([1,0,1])
      47 |     let _test5 = _lyricsGenerator([1,1,1])
    > 48 |     expect(console.log.trim()).toHaveBeenCalledWith(_test1);
         |                        ^
      49 |     expect(console.log.trim()).toHaveBeenCalledWith(_test2);
      50 |     expect(console.log.trim()).toHaveBeenCalledWith(_test3);
      51 |     expect(console.log.trim()).toHaveBeenCalledWith(_test4);

      at Object.<anonymous> (exercises/25-Techno-beat/test.js:48:24)

   undefined 

     ✓ (done) 0. The function named lyricsGenerator should exist
     ✓ (done) 1. console.log() function should have been called 5 times
     x (fail) 2. The output in the console should match the one in the instructions!

**Comment by tommygonzaleza** [comment]
Fixed before, PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/27
Hrs: <hrs>0.05</hrs>
