### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Joaquinabarca95** [learnpack/learnpack#347]
Hrs: <hrs>0.05</hrs>

1.Exercise Name: 01.4-building-a-layout

2.Repository URL: https://github.com/4GeeksAcademy/react-tutorial-exercises

img expected (https://ucarecdn.com/f8cf81eb-3bab-4bba-9431-668884eab174/-/resize/300x/) is different from the one given in the data.image (https://i.pinimg.com/736x/08/a9/b8/08a9b8cc805a1b6a7037819719ab2427.jpg)

**Comment by tommygonzaleza** [comment]
It was fixed with another issue.
Hrs: <hrs>0.05</hrs>
