### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by joanderkrist** [learnpack/learnpack#349]
1.Exercise Name: 04.1-Combined-Rules

2.Repository URL: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

señala error en los propiedades del shorthand del background, lo hice igual que el tutorial, pero el test señala que debe recibir "bdbdbd" siendo esto incorrecto

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/30
Hrs: <hrs>0.15</hrs>
