### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by jamaldonadoa** [learnpack/learnpack#350]
1.Exercise Name: 01-Add-Bootstrap-To-Your-Website

2.Repository URL: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

La validación de los dos Scripts está errada, indica que no hay dos a pesar de estar y exactamente donde me pide el código.

**Comment by alesanchezr** [comment]
<hrs>0.25</hrs>
