### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by kiddopro** [learnpack/learnpack#351]
Hrs: <hrs>0.5</hrs>

1.Exercise Name: 12-Dynamic-HTML-String

2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

When you see the preview of the page, it doesn't show the entire result, and the console don't show errors.

![image](https://user-images.githubusercontent.com/82285542/131532363-9a7ef946-b833-46d7-b289-915d605805cc.png)

![uno](https://user-images.githubusercontent.com/82285542/131532450-91d8b7e9-d108-48ac-a6a9-d89e81d77132.PNG)

**Comment by tommygonzaleza** [comment]
It looks like it's not updating, it works when you close the workspace and open it again

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/27
Hrs: <hrs>0.5</hrs>
