### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by soydeif** [learnpack/learnpack#360]
1.Exercise Name: 12-Rand-From-One-to-Six

2.Repository URL: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

3-build, reset and test buttom are missing.

**Comment by soydeif** [comment]
en general esta actividad, no solo la 12, sino varias de ellas dentro del mismo repositorio tienen varios errores interactivos.

**Comment by tommygonzaleza** [comment]
I tried to replicate the issue but it worked for me.
Hrs: <hrs>0.1</hrs>
