### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by arielstark1** [learnpack/learnpack#363]
1.Exercise Name: 05-returning-json

2.Repository URL: https://github.com/breatheco-de/python-flask-api-tutorial

The instructions ask to modify the return statement of the hello_world method; however, this is not the function that should be modified, it is the function that is executed on the /todos endpoint. So, the instructions are misleading.

**Comment by ElviraQDP** [comment]
help required @tommygonzaleza

**Comment by ElviraQDP** [comment]
PR: https://github.com/breatheco-de/python-flask-api-tutorial/pull/38

I need your input in this PR @tommygonzaleza
