### ISSUE TITLE
Parece que el test funciona mal. La función retorna 2, pero lo lee como 'a'.

### ISSUE THREAD

**Issue by jaimecr24** [learnpack/learnpack#364]
1.Exercise Name: 085-getIndexOf

2.Repository URL: https://github.com/4GeeksAcademy/master-javascript-programming-exercises.git

![image](https://user-images.githubusercontent.com/67288569/132999066-8228909f-954e-443d-91fa-6fd1bd1b24ff.png)
![image](https://user-images.githubusercontent.com/67288569/132999088-717dce2e-f142-4742-9334-ca9ac59e2007.png)
![image](https://user-images.githubusercontent.com/67288569/132999092-b747eb39-4a76-426c-86c9-83e82496f17f.png)

**Comment by jaimecr24** [comment]
Las imágenes son mi código, la prueba sobre chrome y el resultado del test. No sé por qué el test recibe una 'a' cuando la función está retornando un 2.

**Comment by tommygonzaleza** [comment]
This issue is already fixed.
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/45
Issue: Issue #353
Hrs: <hrs>0.05</hrs>
