### ISSUE TITLE
Excercise Bug - 163-FashionInventory-A

### ISSUE THREAD

**Issue by jaimecr24** [learnpack/learnpack#370]
1.Exercise Name: 163-FashionInventory-A (y 164-165)

2.Repository URL: https://github.com/4GeeksAcademy/master-javascript-programming-exercises.git

Y por último los ejercicios 163, 164 y 165. En los tres me ocurre lo mismo. Devuelvo el array que se pide, pero la prueba no lo acepta como válido. Las imágenes son del 163. Como se puede ver en la prueba sobre Chrome, el valor que devuelve la función (res) es el mismo que comprueba la prueba.

![image](https://user-images.githubusercontent.com/67288569/132999543-e385c4cb-f367-41df-bdfd-d2b5f9629511.png)
![image](https://user-images.githubusercontent.com/67288569/132999548-d1b8b160-fbbc-4929-82cd-6025da4e1099.png)
![image](https://user-images.githubusercontent.com/67288569/132999556-1ba8db8a-89c3-4bda-97b9-79f4d3ae5e63.png)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/61
Hrs: 0.5

**Comment by tommygonzaleza** [comment]
PR conflict solved and some extra on this exercise.

Hrs: <hrs>0.75</hrs>
