### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by esilvera** [learnpack/learnpack#371]
1.Exercise Name: 10.1-Creating-Your-First-Function

2.Repository URL: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

3.This exercise is in Javascript and the actual practice is Python

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/33

**Comment by tommygonzaleza** [comment]
PR https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/39
Hrs: <hrs>0.25</hrs>

**Comment by alesanchezr** [comment]
Hrs: <hrs>0.25</hrs>
