### ISSUE TITLE
Command learnpack clean is not removing resets folder

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#374]
Command learnpack clean is not removing resets folder

**Comment by tommygonzaleza** [comment]
- [ ]  Build a postcard using HTML/CSS
- [ ] Learn HTML
- [ ]  HTML5 Forms (10 hrs)
- [ ]  Learn CSS (10 hrs)
- [ ]  Learn CSS Layouts (4 hrs)
- [ ]  Learn Bootstrap (10 hrs)
- [ ]  Introduction to The DOM (4 hrs)
- [ ]  Events inside The DOM (4 hrs)
- [ ]  Javascript for beginners
- [ ]  Looping with Javascript (8 hrs)
- [ ]  Javascript Functions (2 hrs)
- [ ]  Object Oriented Programmming is Javascript
- [ ]  Master Javascript with 150 exercises (50 hrs)
- [ ]  Learn React.js (3 hrs)
- [ ]  Unit testing with Jest (2 hrs)
- [ ]  Python for Beginners (20 hrs)
- [ ]  Practice Looping Lists and Tuples (30 hrs)
- [ ]  Practice functions (10 hrs)
- [ ]  Master Python (50 hrs)
- [ ]  Python API Requests (10 hrs)
- [ ]  Build API's with Python Flask

**Comment by tommygonzaleza** [comment]
-  Build a postcard using HTML/CSS: https://github.com/breatheco-de/exercise-postcard/pull/30
-  Learn Bootstrap (10 hrs): https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/25
-  Introduction to The DOM (4 hrs): https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/32
-  Events inside The DOM (4 hrs): https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/8
- Javascript beginners: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/33
-  Looping with Javascript (8 hrs): https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/49
-  Javascript Functions (2 hrs): https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/34
-  Object Oriented Programmming is Javascript: https://github.com/4GeeksAcademy/object-oriented-javascript-tutorial-exercises/pull/6
-  Master Javascript with 150 exercises (50 hrs): https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/50
-  Learn React.js (3 hrs): https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/76
-  Unit testing with Jest (2 hrs): https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/13
-  Python for Beginners (20 hrs): https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/38
-  Practice Looping Lists and Tuples (30 hrs): https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/62
-  Practice functions (10 hrs): https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/23
-  Master Python (50 hrs): https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/24
-  Build API's with Python Flask: https://github.com/breatheco-de/python-flask-api-tutorial/pull/20

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.9</hrs>

**Comment by alesanchezr** [comment]
not the right version, hours stay the same because the version was .19 instead of .17

**Comment by tommygonzaleza** [comment]
Done

**Comment by alesanchezr** [comment]
Hrs: <hrs>0.9</hrs>
