### ISSUE TITLE
Excercise Bug Mastering JS 108

### ISSUE THREAD

**Issue by Norbert305** [learnpack/learnpack#383]
1.Exercise Name: 108-getSmallestElementAtProperty

2.Repository URL: undefined

![image](https://user-images.githubusercontent.com/83515541/133937811-4ef1d180-3e1f-4595-9755-a7c6c69c29bf.png)

**Comment by Norbert305** [comment]
109 I think has a bug as well in mastering js.

**Comment by tommygonzaleza** [comment]
Hello @Norbert305! How are you?? Can you please give us a description of what the issue is
