### ISSUE TITLE
Bug on 22-Russian-Roulette, test passing with incorrect code

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#390]
1) Exercise: 22-Russian-Roulette

2) Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

3) Description: The test is passing even though the code is wrong. I'm not assigning any parameter and it is still wrong.
![image](https://user-images.githubusercontent.com/56565994/134952178-a45c5739-f0ca-4190-9b05-c95410b26ebd.png)

**Comment by tommygonzaleza** [comment]
Add to the test:

- Check if the function exists.
- Check if the function returns something.
- Check if the console.log() have been called with a number (Use regex)

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/45

**Comment by kiddopro** [comment]
Hrs: <hrs>0.25</hrs>

**Comment by tommygonzaleza** [comment]
@alesanchezr we need your help to find the best approach for this exercises' test. 

On the last is that approach fine? Or the commented one is better? And what about the `!bulletPosition` as a parameter?

**Comment by tommygonzaleza** [comment]
I modified the app.js file, changed the name of some variables. You should modify the test as well.

The readme should include an explanation of using functions value as parameter of other functions

**Comment by kiddopro** [comment]
Hrs: <hrs>0.3</hrs>

**Comment by kiddopro** [comment]
Hrs: <hrs>0.583</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.583</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.583</hrs>
