### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by barcelonabrian11** [learnpack/learnpack#392]
1.Exercise Name: 05-Create-DOM-Element-First

2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises
![image](https://user-images.githubusercontent.com/88598302/135074277-1bc7c1f6-1efb-44d0-a17e-80c7550807ef.png)

**Comment by tommygonzaleza** [comment]
This issue has been fixed already when we redid all the tests

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.1</hrs>

**Comment by tommygonzaleza** [comment]
It didn't add it in the bill either @alesanchezr
