### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by OliverPradaLara** [learnpack/learnpack#393]
1.Exercise Name: 12-split-postcard-body

2.Repository URL: https://github.com/breatheco-de/exercise-postcar
![Captura de pantalla de 2021-09-30 21-43-52](https://user-images.githubusercontent.com/49795876/135548956-ed0c7621-f706-48e9-beb2-26fead7caa9c.png)
d

**Comment by kiddopro** [comment]
the problem was that the user did not save the styles.css file. So the test does not notice the new changes.
Hrs: <hrs>0.17</hrs>

**Comment by tommygonzaleza** [comment]
It doesn't add the issue to the bill

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.17</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.17</hrs>
