### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by willy5360** [learnpack/learnpack#399]
1.Exercise Name: 001-isOldEnoughToDrink

2.Repository URL: undefined

After wasting 1hr trying to understand why 21 wasnt able to be "true", I've notice that Age variable should have been inside fuction's paranthesis
![image](https://user-images.githubusercontent.com/84270420/135728278-43c32d60-6a54-4f45-bff4-7ffd83e5c789.png)

**Comment by tommygonzaleza** [comment]
Hello @willy5360 ! The problem is that you shouldn't declare a variable a but you should  receive the age as parameter, that way this function can work with any age that user inputs
