### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by DarioQuintanilla2109** [learnpack/learnpack#40]
# What was the expected behavior?

Please take 2 minutes to explain what happened, include screenshot if possible.

Missing opening curly bracket of function calculateSumListener() . May cause confusion among students. 

## Other details: 
1. Exercises: 03-sum-values
2. Current URL: https://e920edb9-65ba-4217-bb45-b899470de5ec.ws-us02.gitpod.io
3. Repository: uknown

**Comment by ElviraQDP** [comment]
Wiich exercises are these ones? js functions?
