### ISSUE TITLE
Create a new exercise to replace number 10 (absolute vs relative) on HTML Beginner

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#402]
The exercise will come with a working relative URL and will ask the student to convert it using an absolute URL.

You can use the {{publicUrl}} template variable in the readme to help students understand what URL they should use to convert the relative into absolute.

Maybe you can suggest them to right click on the image to view the public absolute URL.,

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/37
Hrs: <hrs>1.5</hrs>

**Comment by alesanchezr** [comment]
Hrs: <hrs>1.5</hrs>
