### ISSUE TITLE
Multiples README's errors

### ISSUE THREAD

**Issue by Tozzigh** [learnpack/learnpack#408]
1.Exercise Name: 02-Select-DOM-Element

2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

ISSUES:
1.In the HTML there is no paragraph with the id **#theParagraph**, so remove this text from README or add this exact id in the html `<p>` element.

2.This information are incorrect. We cannot show fontSize of an element like this "**console.log(aux.style.fontSize)**" otherwise we can use this "**console.log(window.getComputedStyle(aux).fontSize)**".

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/34
