### ISSUE TITLE
Test Bug

### ISSUE THREAD

**Issue by Tozzigh** [learnpack/learnpack#410]
1.Exercise Name: 09-Remove-DOM-Element-part-two

2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

ISSUE:
First test fail with this code while fourth test should fail:
```javascript
  let list = document.querySelector("#parentLi");
  let childs = list.childNodes;  
  list.parentNode.removeChild(childs[3]);
```

**Comment by tommygonzaleza** [comment]
Redo this test from scratch, add all the tests that it should have. 

Use the testing library if needed: https://testing-library.com/docs/dom-testing-library/api-events

Check the other exercises' tests for guidance.
