### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Tozzigh** [learnpack/learnpack#412]
1.Exercise Name: 13-Add-Options-to-the-Select

2.Repository URL: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

Is this html line of code necessary? 
```javascript 
<button onClick="alert('asdasd');">Hello</button>
```

**Comment by ElviraQDP** [comment]
yes it is

**Comment by tommygonzaleza** [comment]
Actually, I think @Tozzigh is right, that line of code is not adding anything to the exercise and it'll be better to remove it. Can you please remove that line @ElviraQDP?

**Comment by ElviraQDP** [comment]
Where is that line? couldn't find it

**Comment by tommygonzaleza** [comment]
I fixed it in a different commit
