### ISSUE TITLE
addding George's comments, verify to dd changes to spanish README

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#419]
https://github.com/breatheco-de/exercise-postcard/blob/main/README.md

**Comment by tommygonzaleza** [comment]
Where is the pull request with the changes? Can you provide it please

**Comment by ElviraQDP** [comment]
PR merged by @alesanchezr  here is the commit

https://github.com/ElviraQDP/exercise-postcard/commit/1f76ad281670b9acaeb398554e9916c0681dced3
