### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by bselket822** [learnpack/learnpack#423]
1.Exercise Name: 02-Hello-World

2.Repository URL: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

Problems section reads ',' expected. '

**Comment by kiddopro** [comment]
The test has no problems but if we had at least a screenshot with the code that the user entered it would be better.
Hrs: <hrs>0.08</hrs>

**Comment by tommygonzaleza** [comment]
@bselket822 Hello! Can you please provide a better description of what the issue is or at least provide us with your code? Thank you!
