### ISSUE TITLE
Change the titles of the issues

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#434]
I suggest changing the titles of the issues from `Exercise Bug` to `Exercise Bug: name-of-the-exercise`.

This way we can identify the issues in a better way when we need to solve them.

**Comment by ElviraQDP** [comment]
I agree

**Comment by alesanchezr** [comment]
<hrs>0.25</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.25</hrs>
