### ISSUE TITLE
python lesson had javascript examples

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#436]
https://github.com/breatheco-de/content/pull/551/files

**Comment by tommygonzaleza** [comment]
I don't have access to modify this repository, therefore I can't modify the mistake nor merge it, anyway it has a lot of errors, I'm going to add a review so you can fix them

**Comment by tommygonzaleza** [comment]
Hello @alesanchezr! This issue is related with breatheco-de, what should I do in this case as I don't have access to those repositories and I've never worked with breatheco-de, let me know what to do
