### ISSUE TITLE
Excercise Bug Mastering JS 146

### ISSUE THREAD

**Issue by Norbert305** [learnpack/learnpack#438]
1.Exercise Name: 146-ArrayToObject[Part-1]

2.Repository URL: https://github.com/4GeeksAcademy/master-javascript-programming-exercises

![image](https://user-images.githubusercontent.com/83515541/137044743-7ee7c64e-0725-4183-ab18-52fd73226287.png)

**Comment by tommygonzaleza** [comment]
This issue has been fixed already
