### ISSUE TITLE
upload image to asset folder https://github.com/ElviraQDP/python-lists-loops-programming-exercises/tree/master

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#439]
https://www.awesomescreenshot.com/image/14992622?key=a0e49c58ca7f239075ae758bf954ee58 to ex 12.2

**Comment by tommygonzaleza** [comment]
Add  the first image as code on the readme instead of image

**Comment by ElviraQDP** [comment]
the first image was coded and the second image was uploaded: PR https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/74
