### ISSUE TITLE
Improve this new exercise instructions

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#446]
- [ ] Modify the README.md file to make a strong and good readme.
- [ ] Create the translation to Spanish of the English readme (README.es.md file).
- [ ] Find a good image for the exercise, right now it's using one that I found on internet but it could be better.
- [ ] Add improvement to the HTML if you consider that there is a better way to display it.

Repository: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/tree/next (Make sure you are on the branch next, which is where the exercise is located right now as it's not finished).

Exercise: 08-relative-vs-absolute-path

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/44 --> new pr with @alesanchezr changes checked
