### ISSUE TITLE
Problem with packages -  https://github.com/JimenaEB/4Geeks-Academy_exercise_conditional-profile-card

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#448]
https://github.com/breatheco-de/exercise-conditional-profile-card/issues/39

**Comment by tommygonzaleza** [comment]
@alesanchezr Look at these changes, do you think I should add them? https://github.com/JimenaEB/4Geeks-Academy_exercise_conditional-profile-card/commit/9a471fab3e88cc5e2b8501810f8a29a2f685f560#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by tommygonzaleza** [comment]
The current version of the project is working for me

**Comment by alesanchezr** [comment]
We are not using sass anymore. Packaging and node-sass keeps giving problems and the perks are too little, better to use the latest version of CSS that has almost the same features.
