### ISSUE TITLE
Excercise Bug (15-i-frame)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#457]
1.Exercise Name: 15-i-frame

2.Repository URL: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

The compiler reports the following error:

>Unexpected closing tag "iframe". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags

But I'm not sure I'm doing anything wrong, because you actually **should** close the iframe tag, shoudn't you? 🤔

**Comment by tommygonzaleza** [comment]
Hello @vitortamberlini! Maybe you had the closing repeated or something, can you share your code with me, please

**Comment by vitortamberlini** [comment]
Honestly I don't remember what happened in here, but most probably was something telling me to **not** close the iframe tag (even though you should), but...
I checked it again now and everything ran smoothly without any errors 🤔

Well... Maybe the problem solved itself? hahahah
