### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by francomargozziniv** [learnpack/learnpack#458]
1.Exercise Name: 01-welcome

2.Repository URL: https://github.com/breatheco-de/exercise-postcard

La instrucciones dicen:
"Click on the next ➡ button on the top right corner of the screen ↗ when you are ready to continue."

Pero no está habilitado el botón para test.

**Comment by ElviraQDP** [comment]
no está habilitado el botón test porque es un proyecto, no tiene test implementados y en las instrucciones no se menciona el boton "test"
