### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by Folkenciyo** [learnpack/learnpack#461]
1.Exercise Name: 06-lets-start-building

2.Repository URL: https://github.com/breatheco-de/exercise-postcard

Following the most basic step of copy paste as the instruction said, was not posible to test, then to still doing the exercise.
something wrong happens.

![postcard bug](https://user-images.githubusercontent.com/86403857/138431411-aad01d83-ecea-411b-a960-a5ad5f1afb4d.png)

**Comment by tommygonzaleza** [comment]
Hello! It looks like you didn't save the file, that could have been the issue
