### ISSUE TITLE
Exercise bug: 18-Create-a-for-loop

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#468]
The following code should also check: 
- [ ] That the `for` loop is being used
- [ ] That the output (stdout) matches

https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/blob/master/exercises/18-Create-a-for-loop/tests.js

**Comment by kiddopro** [comment]
I added an additional test to check if the standardsMaker function exists
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/44

**Comment by kiddopro** [comment]
Hrs: <hrs>0.3</hrs>
