### ISSUE TITLE
When opening the files in vscode for a particular isolated exercise, the index.html should be the last to open, that way it becomes the visible.

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#470]
You can [open this tutorial in gitpod](https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/) and click `next` to open the next exercise, you will see how all the exercise files get automatically opened: the index.html, index.css, etc.

But the index.css remains visible because is the last one to open.

It should be the index.html.

**Comment by ajoseerazo** [comment]
@alesanchezr I cannot reproduce this issue. When I click in `Next` button, just the `index.html` file get opened. It is already fixed?

**Comment by alesanchezr** [comment]
That repository does not have css or js files, only index. Try with this one: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

**Comment by ajoseerazo** [comment]
Done at https://github.com/learnpack/learnpack-cli/pull/19

**Comment by alesanchezr** [comment]
Prioritizing html files to be opened in vscode/gitpod

1.5h
