### ISSUE TITLE
Exercise Bug

### ISSUE THREAD

**Issue by keenerz** [learnpack/learnpack#471]
1.Exercise Name: 11-Font-Awesome-Icons

2.Repository URL: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

the font awesome icon link is deprecated. Plus in order for me to even use any of the icons requires me to connect and use a js script command which I haven't really covered yet. Just seems like there are parts that do not sync up anymore with the current site.

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/34
Hrs: <hrs>0.25</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.25</hrs>
