### ISSUE TITLE
Exercise 108 (getSmallestElementAtProperty)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#472]
The exercise asks to return undefined for the wrong cases, but the test is expecting an empty array instead.

![image](https://user-images.githubusercontent.com/22197659/139522081-80cd7a92-fb5d-47d4-b55e-1fc1ad582332.png)

![image](https://user-images.githubusercontent.com/22197659/139522090-876f81ec-caaa-45cf-bedd-0be6d1576166.png)

**Comment by tommygonzaleza** [comment]
This issue has been reported already. Here it is: https://github.com/learnpack/learnpack/issues/517
