### ISSUE TITLE
Exercise 122 (calculateBillTotal)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#475]
The README.md is not completely in english.

![image](https://user-images.githubusercontent.com/22197659/139523331-a95a9053-6d22-411a-aef8-a0e52a2f4539.png)

**Comment by vitortamberlini** [comment]
Oh and by the way, I found the description of this exercise _really_ confusing, I don't think that this taxing and tipping subject is very clear... 🤔

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/49

**Comment by tommygonzaleza** [comment]
The instructions are still in spanish: 
![image](https://user-images.githubusercontent.com/56565994/141844857-481633bb-1e83-4ea2-b77c-fd07d5ef5a6e.png)

Please create a new pull request with these changes (Remember to create a new branch for it)

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/62
