### ISSUE TITLE
Exercise 129 (findSmallestNumberAmongMixedElements)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#477]
One of the tests of this exercise is missing the following line of code:

`const findSmallestNumberAmongMixedElements = rewire('./app.js').__get__("findSmallestNumberAmongMixedElements");`

So it's impossible to pass this test because it always gives a _ReferenceError_:

![image](https://user-images.githubusercontent.com/22197659/139525635-3602fa52-107f-4cf7-a62c-8a3267bfda8b.png)

**Comment by kiddopro** [comment]
The issue was already fixed

**Comment by tommygonzaleza** [comment]
Commit where it was fixed: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/commit/e7af2b23acb927b8a988b968ff8f83970164480a#diff-d0a9e8a2df360a579c50d05f89a4cae95f94c42919f13f0931e4a9608656661f
