### ISSUE TITLE
Exercise 134 (convertScoreToGradeWithPlusAndMinus)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#478]
Typo over the README.md:

![image](https://user-images.githubusercontent.com/22197659/139526206-685647a2-1416-49db-a756-40fa6b7bfa51.png)

I guess the word 'are' shouldn't be there 🤔

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/58
