### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by mojonapower** [learnpack/learnpack#480]
1.Exercise Name: 01.1-hello-world
Canbiar en readme.es.md
linea 49
```js
<span> James is <strong>12</strong> years old </span>
```
por
```js
<span>James is <strong>12</strong> years old</span>
```
para que el test salga correcto al copiar de forma literal la instrucción dispuesta.

y en readme.md
linea 52
```jsx
<span> James is <strong>12</strong> years old </span>`
```
por
```jsx
<span>James is <strong>12</strong> years old</span>
```
2.Repository URL: https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/78
