### ISSUE TITLE
Exercise 152 (GreetCustomers)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#485]
There's probably a typo over the README.md file:

![image](https://user-images.githubusercontent.com/22197659/139577606-813b3e93-7e4c-4ef5-a291-3595f0bf6181.png)

**Comment by ElviraQDP** [comment]
https://github.com/ElviraQDP/master-javascript-programming-exercises/pull/1

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/58
