### ISSUE TITLE
Exercise 156 (findPairForSum)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#487]
README.md file is not completely in english:

![image](https://user-images.githubusercontent.com/22197659/139581759-6b0a7c22-67aa-4971-8e7a-b93f5cc6242c.png)

Also one of the tests check have multiple answers, but only one of them is accepted:

![image](https://user-images.githubusercontent.com/22197659/139581805-13aedae4-9c1c-4636-bdfa-ea7701fc1697.png)

Just to explain a bit more the image above:
You have to find two numbers inside that list that result in the second parameter of the function.
The thing is, in this case specifically, you can get the number 7 by either adding 4 + 3 (which is the test), or you could do 2 + 5 (which is my implementation), and both of them should be accepted!

Also the test uses _toBe_, but I'm pretty sure you guys wanted to write _toEqual_...?

**Comment by tommygonzaleza** [comment]
I already fixed the test, please fix the readme part only @ElviraQDP

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/59 --- readme.md fixed 
now @tommygonzaleza has to check the test

**Comment by alesanchezr** [comment]
Alsmo done, but test for ex 156 has not perfect.
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/54/files

**Comment by alesanchezr** [comment]
Tomas should not be assigned to this. Removing it, he has another issue.
