### ISSUE TITLE
Exercise 159 (averageIntegers)

### ISSUE THREAD

**Issue by vitortamberlini** [learnpack/learnpack#488]
I believe the tests are a little bit off, fisrt because there are two tests that say the exact same thing:

![image](https://user-images.githubusercontent.com/22197659/139594254-4d2431c2-4480-49d2-8977-506ecfcba6a4.png)

Also the way that the template function sum is written gives the impression that I should deal with an array, but the tests actually call it with two parameters, which is counter-intuitive.

Template of the function (with only one parameter):

![image](https://user-images.githubusercontent.com/22197659/139594384-106bc9f2-621e-4c67-983e-5d5311bbc04d.png)

Test of the function (inserting two arguments):

![image](https://user-images.githubusercontent.com/22197659/139594361-ed289015-b7e5-4209-9d33-9129886d8c2d.png)

**Comment by kiddopro** [comment]
I fixed some typing problems that could make the user confused, I also fixed the tests so that they work with the exercises and I added some hints and instructions.
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/77
Hrs: <hrs>0.417</hrs>

**Comment by kiddopro** [comment]
Also the exercise was 155 not 159 of master javascript.

**Comment by tommygonzaleza** [comment]
Modify the test so it checks for different arrays on both function, each case should be in a different test

**Comment by kiddopro** [comment]
Hrs: <hrs>0.5836</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.5836</hrs>
