### ISSUE TITLE
Validate exercise directoy and file name during `learnpack audit` and also `learnpack start`.

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#500]
There is a function that validates the exercise directory and file name with now:
https://github.com/learnpack/learnpack-cli/blob/69895255b3f3727b8569b533aae99c176c4341e0/src/managers/config/exercise.js#L95

It is only being used during the learnpack start.

- [x] Update the function to make sure exercise directories cannot have square brackets `[` in the name.
- [x] The folder must start with a number.
- [x] It can only contain numbers, letters and `-` or `_` or `.` symbols.
- [x] Include the folder name validation also in the audit command.
- [x] Make sure the validation is happening during both commands, right now the validation does not seem to be happening on learnpack start like it is supposed to.

**Comment by tommygonzaleza** [comment]
PR: https://github.com/learnpack/learnpack-cli/pull/17
Hrs: <hrs>1</hrs>

**Comment by alesanchezr** [comment]
Probe con el postcard (incremental) y la siguiente estructura de archivos, me dio error buscando el test.js, sera que la validacion no ocurren in incremental mode? o sera que validas muy tarde y da error antes cuando buscas el test.js:

![Screen Shot 2021-11-15 at 11 42 00 AM](https://user-images.githubusercontent.com/426452/141820145-c25d2e53-5a1d-47e9-9cc4-a4043da85fbd.png)

**Comment by tommygonzaleza** [comment]
No logro replicar el error, cuando lo corro en el postcard si me esta funcionando bien.
![image](https://user-images.githubusercontent.com/56565994/146061266-48361782-e5bd-46cd-99c2-190312c21583.png)

**Comment by tommygonzaleza** [comment]
Time trying to replicate the eror:

Hrs: <hrs>0.1</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1.1</hrs>
