### ISSUE TITLE
Change the name of the exercises titles inside of the readme files.

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#502]
Change the name of all the exercises titles that they have in the readme's to the name of the exercises folder.
For example:
On this exercise:
![image](https://user-images.githubusercontent.com/56565994/140405261-8c37d79e-43e2-4704-b2ec-ab8aab08f868.png)
The title of the readme files should be: 03.2-check-for-live

Please change the title of all the exercises of this repository.

Repository: https://github.com/breatheco-de/python-flask-api-tutorial/

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/65

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/python-flask-api-tutorial/pull/33
