### ISSUE TITLE
learnpack audit is not working with the relative paths of incremental exercises

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#504]
This is the error that I'm getting from images that are working.
![image](https://user-images.githubusercontent.com/56565994/140422037-20698af7-d5bb-4b60-ae26-3f2e3c156ed9.png)

**Comment by tommygonzaleza** [comment]
The command is working fine, the path was not the most direct one and it should only check for the most direct one.
Hrs: <hrs>0.1</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.1</hrs>
