### ISSUE TITLE
The relative path of the images should be the most direct one

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#505]
Repository: https://github.com/breatheco-de/python-flask-api-tutorial

The relative path of the images should be the most direct one. For example:

These exercises has relative paths like this one:
`../../../.learn/assets/install-flask.png?raw=true`

The most direct relative path to that image is:
`../../assets/install-flask.png?raw=true`

**Please change the relative path of all the images in this repository exercises to the most direct relative path**

**Comment by ElviraQDP** [comment]
[in this particular case it doesn't work when](https://github.com/breatheco-de/python-flask-api-tutorial/pull/25)
