### ISSUE TITLE
Excercise Bug: 11-Add-li-on-Click

### ISSUE THREAD

**Issue by mpobletee** [learnpack/learnpack#507]
Describe the bug:

**1. Exercise Name:** 11-Add-li-on-Click
**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

### ---- Description ----

The validation on test.js in line 29 expected **"Forth"** not **Fourth**.

test('the js code should contain an assignment line allow you assign Fourth Element with innerHTML', function () {
    document.documentElement.innerHTML = html.toString();
    const expected = 'innerHTML = "Forth element";';
    // we can read from the source code
    console.log(js.toString());
    expect(js.toString().indexOf(expected) > -1).toBeTruthy();
});

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/37
Hrs: <hrs>0.07</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.07</hrs>
