### ISSUE TITLE
Excercise Bug: 06-lambda-functions

### ISSUE THREAD

**Issue by peibol888** [learnpack/learnpack#512]
Describe the bug:

**1. Exercise Name:** 06-lambda-functions

**2. Repository URL:** https://github.com/4GeeksAcademy/python-functions-programming-exercises

OLD INCORRECT:

💡Hint

Here is how you would declare it like a normal function

# this function return True if a number is odd.
def is_odd(num):
    return (num % 2) !== 0:

NEW CORRECT:

💡Hint

Here is how you would declare it like a normal function

# this function return True if a number is odd.
def is_odd(num):
    return (num % 2) != 0

**Comment by peibol888** [comment]
inside the function should appear `return (num % 2) != 0` instead of `return (num % 2) !== 0:`

**Comment by ElviraQDP** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/25

**Comment by tommygonzaleza** [comment]
You have t run the command `learnpack clean` before staging your changes. Please run it and push your changes again

**Comment by ElviraQDP** [comment]
Wh

> You have t run the command `learnpack clean` before staging your changes. Please run it and push your changes again

why? could you explain please?

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/26
