### ISSUE TITLE
Excercise Bug: 11-Create-A-New-Function

### ISSUE THREAD

**Issue by isaacruga** [learnpack/learnpack#513]
Describe the bug:

**1. Exercise Name:** 11-Create-A-New-Function

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

(A) Test's way
```
import random

# your code here
def generate_random():
    r = random.randint(0,9)
    print(r)
    return r

```
Compile-->No stdout to display on the console

(B) Number between 0 and 9
```
import random

# your code here
def generate_random():
    return random.randint(0,9)

print(generate_random())

```
Compile--> Random Numbers between 0-9

**Comment by tommygonzaleza** [comment]
I just took a look at the test and it looks good, anyway in that case that you want to see the result in the console, you can do it as you said in the second example and the test is not specifying any of those ways to do it, it only checks what it returns.

Thank you for your feedback though!
