### ISSUE TITLE
Exercise Bug: 108-getSmallestElementAtProperty

### ISSUE THREAD

**Issue by keenerz** [learnpack/learnpack#517]
Describe the bug: for the Hints its asking for undefined but the code is looking for an empty array [], so no matter what you do it doesn't actually work. Cause the hints are not giving the right advice.  This problem is also present in 109-getLargestElementAtProperty

**1. Exercise Name:** 108-getSmallestElementAtProperty

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

**Comment by kiddopro** [comment]
Already solved

https://github.com/learnpack/learnpack/issues/518
