### ISSUE TITLE
Excercise Bug: 02-Select-DOM-Element

### ISSUE THREAD

**Issue by jesus-cano-ortega** [learnpack/learnpack#519]
Describe the bug:

**1. Exercise Name:** 02-Select-DOM-Element

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

En la etiqueta <p> falta que venga incluido el id i#theParagraph tal y como indica el enunciado

**Comment by ElviraQDP** [comment]
The exercises works for me, I don't see what the student's means

**Comment by tommygonzaleza** [comment]
Yes, it was fixed on this issue: https://github.com/learnpack/learnpack/issues/408
