### ISSUE TITLE
reviewing master javascript layout

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#521]

**Comment by tommygonzaleza** [comment]
Hello! @ElviraQDP Can you please describe this issue better, I'm not sure what the problem is. Thanks!

**Comment by ElviraQDP** [comment]
I'm checking the layout of the exercises, checking for the correct markdown on the README's

**Comment by tommygonzaleza** [comment]
I don't see any PR, but I'm going to close this issue as we are going to review all the exercises markdown syntax when we apply the new structure that we created.
