### ISSUE TITLE
Excercise Bug: 12-Rand-From-One-to-Six

### ISSUE THREAD

**Issue by Carolth7** [learnpack/learnpack#527]
Describe the bug:

the excercise number doesn´t match with the appropiate number, it says excercise 14 instead of 12

**1. Exercise Name:** 12-Rand-From-One-to-Six

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/41

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/43
