### ISSUE TITLE
Excercise Bug: 13-Create-A-For-Loop

### ISSUE THREAD

**Issue by arianrdcas** [learnpack/learnpack#536]
Describe the bug:

**1. Exercise Name:** 13-Create-A-For-Loop

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by arianrdcas** [comment]
El ejericicio numero 13 aparece como ejercicio 16 en el cuadro del leanrpack

**Comment by tommygonzaleza** [comment]
Este issue ya fue reportado y se está trabajando para corregirlo.

Muchas gracias por reportarlo @arianrdcas
