### ISSUE TITLE
14 Excercise javascrip dia 3 prework Bug

### ISSUE THREAD

**Issue by riveromj** [learnpack/learnpack#54]
# What was the expected behavior?
cuando compilo genera error y cuando hago el test esta correcto

## Other details: 
1. Exercises: 14-Your-first-switch
2. Current URL: https://ed4abc88-c3aa-48d1-bfd6-89ecca112ef6.ws-eu01.gitpod.io
3. Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

**Comment by ElviraQDP** [comment]
este ejercicio es muy capcioso, fijate en cada detalle de tu codigo! y lee bien las instrucciones...:)
