### ISSUE TITLE
Change the title of the exercises that has sections (Change the numbers)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#540]
Repository: https://github.com/4GeeksAcademy/master-javascript-programming-exercises

![image](https://user-images.githubusercontent.com/56565994/142926169-eb620a1b-b77d-4c37-a9c9-3efad59d4801.png)

Change the name of the exercises to the ideal structure. When exercises have more than one part, you should add the other part as sections of this one, so if you have the exercise: `01-Hello`if it has three sections, the name of them should be:

1. `01.1-Hello`
2. `01.2-Hello`
3. `01.3-Hello`

And then as you are changing the initial number of the titles, you should change the number of the following exercises as well.

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/64

**Comment by tommygonzaleza** [comment]
Change the names of the readme titles.

i.e.: `146.1 ArrayToObject-Part-1` should be `146.1 ArrayToObject`

**Comment by tommygonzaleza** [comment]
It has a conflict with the main branch, please fix it

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/64/files
