### ISSUE TITLE
EX 159.4 from https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/64 is missing a test.js

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#548]
I just found a README.md.es file that corresponds to exercise 159.4 - FashionInventory-D. I created the folder, app.js and both README's but the test is missing @tommygonzaleza

**Comment by tommygonzaleza** [comment]
I created the test which checks if the function exists, and if the function returns the correct array with two different inputs

PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/67
Hrs: <hrs>0.55</hrs>
