### ISSUE TITLE
ex 159.4 folder and README's created

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#549]

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/65

**Comment by tommygonzaleza** [comment]
You have to add the files inside a folder named 159.4-FashionInventory-D.

Remember to change the title of the readmes to the name of the folder exercise

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/64/

**Comment by tommygonzaleza** [comment]
You have to solve the conflict that it has with the main branch

**Comment by tommygonzaleza** [comment]
The files are still outside of the folder

**Comment by tommygonzaleza** [comment]
And it has a conflict with the main branch, please fix it

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/65
