### ISSUE TITLE
Excercise Bug: 21-factorial

### ISSUE THREAD

**Issue by Alquem** [learnpack/learnpack#556]
Describe the bug:

**1. Exercise Name:** 21-factorial

**2. Repository URL:** https://github.com/4GeeksAcademy/master-python-programming-exercises

cannot test the answer
there is no test file

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/27
Hrs: <hrs>0.45</hrs>
