### ISSUE TITLE
Learnapck language flags are down

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#560]
This is the original issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2010

Solution:

Lets implement our own flags in the react.js application.

**Comment by tommygonzaleza** [comment]
PR: https://github.com/learnpack/coding-ide/pull/7
Hrs: <hrs>0.9</hrs>

I tried to do it myself and then I saw that the only problem was that the other API was down
