### ISSUE TITLE
Excercise Bug: 108-getSmallestElementAtProperty

### ISSUE THREAD

**Issue by Baldonak** [learnpack/learnpack#570]
Describe the bug:

**1. Exercise Name:** 108-getSmallestElementAtProperty

**2. Repository URL:** undefined

The tutorial instructions are:

-   If the array is empty, it should return **undefined.**

-   If the property at the given key is not an array, it should return **undefined.**
 
-   If there is no property at the key, it should return **undefined.**

But the tests replace undefined for **empty array**

**Comment by tommygonzaleza** [comment]
This issue has been reported already. Here it is: https://github.com/learnpack/learnpack/issues/517
