### ISSUE TITLE
Excercise Bug: 147-ArrayToObject-Part-2

### ISSUE THREAD

**Issue by Baldonak** [learnpack/learnpack#574]
Describe the bug:

**1. Exercise Name:** 147-ArrayToObject-Part-2

**2. Repository URL:** undefined

It is necessary rename de variable "output": The terminal message error with this name

**Comment by tommygonzaleza** [comment]
That problem has been fixed already, it is working fine and output has been declared with let so it can be reused.
Hrs: <hrs>0.1</hrs>
