### ISSUE TITLE
Excercise Bug: 04-Call-a-function

### ISSUE THREAD

**Issue by InTr0p** [learnpack/learnpack#594]
Describe the bug:

Al apretar la ayuda "Tutorial" Direcciona al tutorial que debería estar en el ejercicio  02-Hello-World 

**1. Exercise Name:** 04-Call-a-function

**2. Repository URL:** undefined

**Comment by tommygonzaleza** [comment]
Can you check this issue please @kiddopro?

The video tutorial should be on the README file, make sure that the video is the correct one.

**Comment by kiddopro** [comment]
the Spanish version of the exercise did not have a tutorial.

PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/27

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.085</hrs>
