### ISSUE TITLE
The readmes are not clear enough 

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#603]
1. Exercise Name: 159.1-FashionInventory-A, 159.2-FashionInventory-B and 159.3-FashionInventory-C

2. Repository URL: https://github.com/4GeeksAcademy/master-javascript-programming-exercises

3. Description: None of the readmes of exercises 159.1, 159.2, and 159.3 are asking to create a specific function, the readme and the tests should talk about the same

**Comment by ElviraQDP** [comment]
- 159. 1 - Fashion Inventory A - english README **only** - PR https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/74 (Spanish README will be translated after approval)

**Comment by tommygonzaleza** [comment]
You should modify the Spanish version as well.

- 159.1: Add some hints to the exercise. (Change the flat list explanation by matrix)
- 159.2: Remove your changes from the 159.1 exercise. Improve explanation based on the test's solution, change the expected output and add some hints.
- 159.3: I'll review this exercise myself, I'll ask for help with the readme after it.

**Comment by ElviraQDP** [comment]
159. 1 - Fashion Inventory A -  - PR https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/74 

159.2 - Fashion Inventory B. - - PR https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/75

159. 3 - Fashion Inventory C -   - PR https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/76

**Comment by tommygonzaleza** [comment]
I added more comments on both PRs

**Comment by tommygonzaleza** [comment]
159.2 - Fashion Inventory B. - - PR 4GeeksAcademy/master-javascript-programming-exercises#75

you have to remove the changes you made on exercise 159.1 as they are on the other PR.

You should also modify the readmes to have the same structure that we added to exercise 159.1

**Comment by ElviraQDP** [comment]
PR for 159.2: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/88
