### ISSUE TITLE
Excercise Bug: 161-phoneNumber

### ISSUE THREAD

**Issue by lienzoenblanco** [learnpack/learnpack#605]
Describe the bug:

**1. Exercise Name:** 161-phoneNumber

**2. Repository URL:** https://github.com/4GeeksAcademy/master-javascript-programming-exercises

![code](https://user-images.githubusercontent.com/92454824/148601433-462d729d-3464-46a2-ae70-9f104e7d4ac6.png)
![test](https://user-images.githubusercontent.com/92454824/148601449-f1b239a4-8057-40c0-a559-200388d4965c.png)

**Comment by tommygonzaleza** [comment]
Please check why this bug is happening @kiddopro

**Comment by kiddopro** [comment]
Already solved
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/114
