### ISSUE TITLE
Learnpack Audit is failing

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#620]
**Describe the bug**
It failed while trying to change from absolute to relative path, 
here is the repo:
https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial
here is the PR:
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/42 
Screenshot of the error:
![image](https://user-images.githubusercontent.com/63673743/149191693-047b66bf-c4e4-4844-9648-ab569e821892.png)

**Comment by tommygonzaleza** [comment]
Problem solved, there was a bug related to the regular expression of the relative images, it's been fixed.

PR: https://github.com/learnpack/learnpack-cli/pull/22
Hrs: <hrs>0.6</hrs>
