### ISSUE TITLE
Excercise Bug: 08-Bootstrap-Forms

### ISSUE THREAD

**Issue by Christi4n0** [learnpack/learnpack#622]
Describe the bug:

Test no pasa (Santiago-ft-xiv)

**1. Exercise Name:** 08-Bootstrap-Forms

**2. Repository URL:** https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

**Comment by tommygonzaleza** [comment]
Same issue as: https://github.com/learnpack/learnpack/issues/623
