### ISSUE TITLE
Excercise Bug: 08-Bootstrap-Forms

### ISSUE THREAD

**Issue by FrankLobo** [learnpack/learnpack#623]
Describe the bug:

No se está cumpliendo los parámetros que el ejercicio nos da. 

1ro, nos pide que el primer elemento sea un h2. Al hacerlo, no lo cumple y no pasa el test.
2do nos pide que agrupemos los elementos dentro de una etiqueta form. Al hacerlo, no lo cumple y no pasa el test.
3ro debe estar los 4 elementos dentro del form. Al hacerlo, no lo cumple y no pasa el test.
4to los inputs deben ser como en el ejemplo. Al hacerlo, no lo cumple y no pasa el test.
5to el boton debe tener un ancho del 100%. Al hacerlo, no lo cumple y no pasa el test.

**1. Exercise Name:** 08-Bootstrap-Forms

**2. Repository URL:** https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

**Comment by tommygonzaleza** [comment]
I had to redo the test from scratch, change the example image (As it had some details that you needed css), and I also modified the instructions to be more clear.

PR: https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/28
Hrs: <hrs>1.12</hrs>
