### ISSUE TITLE
Learnpack audit is throwing errors with valid links

### ISSUE THREAD

**Issue by ElviraQDP** [learnpack/learnpack#627]

**Comment by ElviraQDP** [comment]
repo:https://github.com/4GeeksAcademy/react-tutorial-exercises/

PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/81

The link is not broken

screenshot:
![https___github com_learnpack_learnpack_issues_282 · 4GeeksAcademy_react-tutorial-exercises@38a1459](https://user-images.githubusercontent.com/63673743/149542838-ba80e3ed-884e-46fc-8d35-e83a12cb48d1.png)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/learnpack/learnpack-cli/pull/23/files
Hrs: <hrs>0.31</hrs>

**Comment by tommygonzaleza** [comment]
I need your review on this one before accepting the change. It works but I'm not sure if on other cases it could fail, maybe you know @alesanchezr

**Comment by alesanchezr** [comment]
Hrs: <hrs>0.31</hrs>
