### ISSUE TITLE
Excercise Bug: 033-isPersonOldEnoughToDrinkAndDrive

### ISSUE THREAD

**Issue by robtha4th** [learnpack/learnpack#644]
Describe the bug: function should only allow return false because no one should ever drink and drive.

**1. Exercise Name:** 033-isPersonOldEnoughToDrinkAndDrive

**2. Repository URL:** undefined

**Comment by tommygonzaleza** [comment]
Issue already solver on this PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/85
