### ISSUE TITLE
It should return [] instead of undefined - 109-getLargestElementAtProperty

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#651]
Exercise: 109-getLargestElementAtProperty

Repository: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/

Change the readmes and the test to expect an empty array `[]` instead of `undefined`.

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/82

**Comment by kiddopro** [comment]
Hrs: <hrs>0.083</hrs>
