### ISSUE TITLE
Excercise Bug: 05.1-second-styles

### ISSUE THREAD

**Issue by Navarroseb** [learnpack/learnpack#669]
Describe the bug: El ejemplo solicita un borde redondo en badgeStyles, pero el test no lo pasa. Al quitar la propiedad borderRadius el test pasa dejando el borde cuadrado. 

**1. Exercise Name:** 05.1-second-styles

**2. Repository URL:** https://github.com/4GeeksAcademy/react-tutorial-exercises

**Comment by tommygonzaleza** [comment]
Same issue as: https://github.com/learnpack/learnpack/issues/483
