### ISSUE TITLE
The instructions are not clear enough - 08-Rounded-Image

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#695]
Repository: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/

Exercise: 08-Rounded-Image

The instructions are not clear enough, specify on two instructions:

1. Use `border-radious` to round the image.
2. Use ojbect-fit cover...

Original Issue: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/issues/23

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/46
