### ISSUE TITLE
Excercise Bug: 06-lets-start-building

### ISSUE THREAD

**Issue by juacoPinto** [learnpack/learnpack#697]
Describe the bug:

**1. Exercise Name:** 06-lets-start-building

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

I copied the exercise, exactly like the instruction said, but still send a message of error

**Comment by tommygonzaleza** [comment]
Hello @juacoPinto! Can you show us the error you are getting and the code you have, please? That way we can replicate the exact error you have and fix it

**Comment by juacoPinto** [comment]
Hello, i already had a meeting last week with one of your staf, he
explained me how to work on it, so its clarified
Thanks

**Comment by tommygonzaleza** [comment]
Perfect! Thanks!
