### ISSUE TITLE
Review the tests exercises - python-beginner-programming-exercises

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#701]
Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Exercises: Check all of them.

Some students are complaining about these exercises' tests, I need you to review them and modify those that are missing validations or have extra validations.

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/48

**Comment by kiddopro** [comment]
Hrs: <hrs>4.833</hrs>
