### ISSUE TITLE
Excercise Bug: 10-center-postcard

### ISSUE THREAD

**Issue by ViewOnPhone** [learnpack/learnpack#711]
Describe the bug:

**1. Exercise Name:** 10-center-postcard

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

The test only passes when using background and not background color

**Comment by kiddopro** [comment]
Hrs: <hrs>0.5</hrs>

**Comment by tommygonzaleza** [comment]
Separate the last test into different tests per each style (One for the width, another one for the background, and so on).

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.5</hrs>
