### ISSUE TITLE
Mock inputs of all unit tests

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#717]
Check on all the javascript and python exercises where they are using inputs (prompt on javascript). Wherever you find one, you should replace how the test works and mock the input on the tests.

Here is an example with javscript of how to mock the input on the test: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/blob/master/exercises/05-User-inputed-variables/tests.js#L9

Here is an example with python: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/blob/350aba037a518293b4b1742110d89b1266125211/exercises/08-Your-First-If/test.py#L14

**Comment by kiddopro** [comment]
Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/50
Hrs: <hrs>1</hrs>

**Comment by kiddopro** [comment]
Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/45
Hrs: <hrs>0.085</hrs>

**Comment by kiddopro** [comment]
Hrs: <hrs>4.502</hrs>

**Comment by tommygonzaleza** [comment]
> On this PR, you should change the test in order to be much more specific, it should check for the numbers that are closer to the condition and one random number between the conditions.

On this PR as well, you should change the test in order to be much more specific, it should check for the numbers that are closer to the condition and one random number between the conditions.

**Comment by tommygonzaleza** [comment]
> Repository: https://github.com/4GeeksAcademy/master-python-programming-exercises
PR: https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/31

Modify the test of the exercise 4 in order to work with mocked values

**Comment by tommygonzaleza** [comment]
> Repository: https://github.com/4GeeksAcademy/master-python-programming-exercises
PR: https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/31

Modify all the tests (That you changed on the PR) in order to work without inputs.

**Comment by tommygonzaleza** [comment]
Change the exercise 23 to work with function instead of input

**Comment by tommygonzaleza** [comment]
Change the 25th exercise's instructions in order to work with only one parameter as the solution.hide is showing

**Comment by tommygonzaleza** [comment]
Anyway, let's wait for the readme, we should start applying these changes when Elvira finishes changing the readme's instructions

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>8.353/hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>8.353</hrs>
