### ISSUE TITLE
Excercise Bug: 24-Bottles-of-milk

### ISSUE THREAD

**Issue by jsowers13** [learnpack/learnpack#718]
Describe the bug:

**1. Exercise Name:** 24-Bottles-of-milk

**2. Repository URL:** undefined

The test expects the string to print as "1 bottles of milk" instead of  "1 bottle of milk" as per the instructions
![image](https://user-images.githubusercontent.com/98606628/153972545-c7ce6da8-ab38-4aa9-b3f9-689052a04781.png)

**Comment by tommygonzaleza** [comment]
This issue has been fixed already, thank you for reporting it!
