### ISSUE TITLE
Excercise Bug: 05.1-second-styles

### ISSUE THREAD

**Issue by josecaro02** [learnpack/learnpack#752]
Describe the bug:

**1. Exercise Name:** 05.1-second-styles

**2. Repository URL:** https://github.com/4GeeksAcademy/react-tutorial-exercises

Based in the image given in the instructions, I think it will be good to add a borderRadius="50%" to match the rounded by red number. Tests only needs backgroundColor and color, but the result has a sqaure shape.

**Comment by Sadiel0** [comment]
No bug, just a suggestion.

**Comment by tommygonzaleza** [comment]
He is suggesting to add something good to the test, I think we should include it

**Comment by Sadiel0** [comment]
Then i shall do it brother
