### ISSUE TITLE
javascr-exercises-tutorial: 20 get color

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#754]
El ejercicio parece estar correcto pero los tests no apsan.

![image](https://user-images.githubusercontent.com/426452/156210255-0ea2511f-3d35-4d70-b66d-ea3ccf7888f1.png)

**Comment by kiddopro** [comment]
already solved 
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/55
