### ISSUE TITLE
READMEs structure - DOM Intro (00-Welcome - 08-Remove-DOM-Element-part-one)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#769]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

Exercises: From `00-Welcome` to `08-Remove-DOM-Element-part-one`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/41
