### ISSUE TITLE
READMEs structure - DOM Intro (09-Remove-DOM-Element-part-two - 14-Todo-List)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#770]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises

Exercises: From `09-Remove-DOM-Element-part-two` to `14-Todo-List`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/42

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/50

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/44
