### ISSUE TITLE
READMEs structure - Javascript Functions (01-Welcome - 11-Remove-vowels)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#771]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

Exercises: From `01-Welcome` to `11-Remove-vowels`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/47

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/48

**Comment by Lorenagubaira** [comment]
https://lorenagubaira-javascript-xokff7h38nf.ws-us38.gitpod.io/

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/49/commits/0fb7ae9651c3329b96ab94962cec75e725fdcde7

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/49

**Comment by tommygonzaleza** [comment]
Some files are missing the correct structure, you have to change their title, and make sure that all of them have the right structure.

Please review all the filesa again
