### ISSUE TITLE
READMEs structure - Python Beginner (00-Welcome - 10-Calling-Your-First-Function)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#772]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Exercises: From `00-Welcome` to `10-Calling-Your-First-Function`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/commit/3e6e4ddd998ae1c93119b8113f471194242295d2

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/50

**Comment by tommygonzaleza** [comment]
Please add the videos on the 00-welcome readme files
