### ISSUE TITLE
READMEs structure - Python Beginner (10.1-Creating-Your-First-Function - 19-Bottles-Of-Milk)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#773]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Exercises: From `10.1-Creating-Your-First-Function` to `19-Bottles-Of-Milk`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/51
