### ISSUE TITLE
Excercise Bug: 109-getLargestElementAtProperty

### ISSUE THREAD

**Issue by Karim-aitt** [learnpack/learnpack#777]
Describe the bug:
A pesar de que todo está bien, no da el test por valido.

Although everything is fine, the test is not valid.

https://gyazo.com/d23769e4fa832ee244964aeb2607c72d

**1. Exercise Name:** 109-getLargestElementAtProperty

**2. Repository URL:** undefined

**Comment by tommygonzaleza** [comment]
Please check do the exercise and test that is working fine @kiddopro

**Comment by kiddopro** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/112

**Comment by tommygonzaleza** [comment]
Same issue as: #789 , therefore, I'm going to delete this one
