### ISSUE TITLE
Excercise Bug: 13-check-your-code

### ISSUE THREAD

**Issue by Bevilax** [learnpack/learnpack#783]
Describe the bug:

**1. Exercise Name:** 13-check-your-code

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

code: <!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<link rel="stylesheet" href="styles.css" />
	</head>
	<body>
		<div class="postcard">
			<div class="postcard-header">
				<h1>My Postcard</h1>
				<img
				src=https://raw.githubusercontent.com/breatheco-de/exercise-postcard/e63a7916530cc850bd92aa1c2e19191837fb5c80/.learn/assets/4geeks.png/>
			</div>
		<div class="postcard-body">
				<div class="body-left">
					<p>This is pretty cool! I creaed this postcard using HTML5 and CSS3 during my 4Geeks Academy Course!</p>
					<p>This is awesome, I can' wait to start doing more things!</p>
		</div>
		<div class="body-right">
			<input type="text" placeholder="Your Name">
            <input type="text" placeholder="Your Email">
            <input type="text" placeholder="Your Comment">
		</div>
    </div>
	<div class="postcard-footer">
        <button type="button">Send My Postcard</button>
    </div> 
</div>
	</body>
</html>

**Issue**: the button code is not working.

**Comment by tommygonzaleza** [comment]
That was just an image, I'm going to delete this issue as the button wasn't expected to do something
