### ISSUE TITLE
Excercise Bug: 07-Create-a-Basic-HTML

### ISSUE THREAD

**Issue by Codekgeek26** [learnpack/learnpack#786]
Describe the bug:

**1. Exercise Name:** 07-Create-a-Basic-HTML

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises
<img width="1440" alt="Screen Shot 2022-03-15 at 11 25 25 AM" src="https://user-images.githubusercontent.com/93161320/158412501-b8ecb181-b766-4388-93e4-45cfc8f48bed.png">

my answer is correct

**Comment by tommygonzaleza** [comment]
Hello @kiddopro! Can you please review this exercise?

**Comment by dsilva06** [comment]
Hrs: <hrs>0.25</hrs>
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/59

**Comment by tommygonzaleza** [comment]
You should improve the tests, add a test to check for the html_document variable value, and another one that checks that the print is being used once by mocking the print function

**Comment by tommygonzaleza** [comment]
The title of the tests should be the description of what failed, the error. Change the second test's title.

**Comment by dsilva06** [comment]
HRS: <hrs>0.25</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.25</hrs>

**Comment by tommygonzaleza** [comment]
Total Hrs: <hrs>0.75</hrs>
