### ISSUE TITLE
Excercise Bug: 05-User-inputed-variables

### ISSUE THREAD

**Issue by anthonnytineo** [learnpack/learnpack#787]
Describe the bug:

**1. Exercise Name:** 05-User-inputed-variables

**2. Repository URL:** undefined

Hello, my name is Anthonny Tineo, I was practicing on gitpod and when checking this exercise they don't take the indicated number, it appears as if 40 was indicated every time. Greetings.

**Comment by tommygonzaleza** [comment]
Hello @anthonnytineo! That because of something used on tests which is named mock, we are basically checking your code if the user input 40 so we know what the expected output should be. That is why the test is correct, it was meant to be that way
