### ISSUE TITLE
Excercise Bug: 05.4-Add-items-to-array-looping

### ISSUE THREAD

**Issue by divRobles** [learnpack/learnpack#792]
Describe the bug:

**1. Exercise Name:** 05.4-Add-items-to-array-looping

**2. Repository URL:** undefine
![05 4](https://user-images.githubusercontent.com/101132606/158987218-81d1ace4-6731-40bc-9944-245a78bbb3db.PNG)
d

**Comment by dsilva06** [comment]
Hrs: <hrs>0.16</hrs>
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/73

**Comment by dsilva06** [comment]
Hrs: <hrs>0.16</hrs>
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/73

**Comment by tommygonzaleza** [comment]
You have to run learnpack clean

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.16</hrs>
