### ISSUE TITLE
Excercise Bug: 24-Bottles-of-milk

### ISSUE THREAD

**Issue by divRobles** [learnpack/learnpack#796]
Describe the bug:
cuando llega a 2, la frase debería ser:
2 bottles of milk on the wall, 2 bottles of milk. Take one down and pass it around, 1 bottle of milk on the wall.
(bottle en singular cuando es 1).

marca como correcto:
2 bottles of milk on the wall, 2 bottles of milk. Take one down and pass it around, 1 bottles of milk on the wall.
(bottles en plural cuando es 1).

**1. Exercise Name:** 24-Bottles-of-milk

**2. Repository URL:** undefined

**Comment by tommygonzaleza** [comment]
Hello @kiddopro! Can you please solve this issue, remember to review the readmes and the test

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/59

**Comment by kiddopro** [comment]
Hrs: <hrs>0.085</hrs>
