### ISSUE TITLE
READMEs structure - React (01-welcome - 03.1-your-first-component)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#797]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

Exercises: From `01-welcome` to `03.1-your-first-component`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/85
