### ISSUE TITLE
READMEs structure - React (03.2-a-real-component - 06-listening-to-events)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#798]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

Exercises: From `03.2-a-real-component` to `06-listening-to-events`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/86
