### ISSUE TITLE
READMEs structure - Jest (01-intro - 07-your-first-test)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#799]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/breatheco-de/exercise-unit-test-with-jest

Exercises: From `01-intro` to `07-your-first-test` (You should add the 00-welcome or replace the 01-intro by the 00-welcome)

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/28

it is necessary to verify that the structure of the welcome is correct
