### ISSUE TITLE
Excercise Bug: 09-formating-Text

### ISSUE THREAD

**Issue by nabdevtech** [learnpack/learnpack#813]
Describe the bug:

**1. Exercise Name:** 09-formating-Text

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Compiler is throwing an error that the p tag has already been closed but it hasn't:

`<!DOCTYPE html>
<html>
	<head>
		<title>4Geeks Academy</title>
		<style>
			blockquote {
				border-left: 2px solid red;
				background: #fbfbfb;
				padding: 5px;
			}
		</style>
	</head>
	<body>
		
		<h1>This will be your heading</h1>
		<p>Then, you start talking about some interesting stuff that nobody wants to read. <br> Then you can quote someone to add credibility: <blockquote>A quotation is a handy thing to have about, saving one the trouble of thinking for oneself, always a laborious business <br> - A.A. Milne, If I May</blockquote> <br>
		Finally you can have some bullets to summarize everything, after all, new generations have these things in common:
		<ul>
			<li>Don't like to read long texts</li>
			<li>Have the spawn of attention of a bird</li>
			<li>Skip long paragraphs straight to the bullet points.</li>
		</ul>
		</p>
	</body>
</html>
`

**Comment by tommygonzaleza** [comment]
Hello @nabdevtech! Can you provide us with the code you have, please.

**Comment by tommygonzaleza** [comment]
Please follow up this issue
