### ISSUE TITLE
Excercise Bug: 12-Your-first-if

### ISSUE THREAD

**Issue by arques89** [learnpack/learnpack#817]
Describe the bug:
Las instrucciones te piden que el console log diga “Are we there yet” pero el test prueba que diga “We still have a bit of driving left to go”
**1. Exercise Name:** 12-Your-first-if

**2. Repository URL:** undefined

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/62

**Comment by kiddopro** [comment]
Hrs: <hrs>0.085</hrs>
