### ISSUE TITLE
Publish all the learnpack packages on npm

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#824]
Publish all the learnpack packages on npm on the new learnpack organization.

Packages:

- @learnpack/cli (learnpack-cli)
- @learnpack/html (learnpack-html)
- @learnpack/node (learnpack-node)
- @learnpack/python (learnpack-python)
- @learnpack/dom (learnpack-dom)
- @learnpack/react (learnpack-react)

**Comment by alesanchezr** [comment]
@tommygonzaleza i have updated the package names
