### ISSUE TITLE
Excercise Bug: 06-lets-start-building

### ISSUE THREAD

**Issue by Fertacho** [learnpack/learnpack#825]
Describe the bug:

**1. Exercise Name:** 06-lets-start-building

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

I followed the instructions but when I pressed "Next" it showed me this
![Bug](https://user-images.githubusercontent.com/101839698/161880540-37421cee-ab04-4098-8657-110e5a8faff7.jpg)
.

**Comment by tommygonzaleza** [comment]
hello! the problem is that you have to test the exercise before you click on next
