### ISSUE TITLE
Excercise Bug: 03-first-flask-app

### ISSUE THREAD

**Issue by BlurryFace1900** [learnpack/learnpack#828]
Describe the bug:
All the setup is done as mentioned in the instruction. But, test fails.

**1. Exercise Name:** 03-first-flask-app

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

**Comment by tommygonzaleza** [comment]
Please make sure that the test is working fine with the instructions given @kiddopro

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.1</hrs>
