### ISSUE TITLE
Excercise Bug: 06-add-listener-with-js

### ISSUE THREAD

**Issue by bashh69** [learnpack/learnpack#829]
Describe the bug:

**1. Exercise Name:** 06-add-listener-with-js

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises

The expected result shows the number and name of this exercise not the result screenshot.

![image](https://user-images.githubusercontent.com/84740314/162633877-e7bba055-727c-40f1-962e-4d8147cef747.png)

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/14
