### ISSUE TITLE
Exercise Bug: 08.3-Sum-all-items

### ISSUE THREAD

**Issue by sardinhas12** [learnpack/learnpack#830]
Describe the bug:

**1. Exercise Name:** 08.3-Sum-all-items

**2. Repository URL:** undefined

**Comment by tommygonzaleza** [comment]
Hello! @sardinhas12! Can you provide us a description of what the issue is

**Comment by tommygonzaleza** [comment]
Hey @kiddopro! Can you follow up on this issue, please
