### ISSUE TITLE
`learnpack init` for incremental exercises not working

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#834]
<img width="570" alt="Screen Shot 2022-04-12 at 12 10 21 AM" src="https://user-images.githubusercontent.com/426452/162878895-0e3a8d7e-400c-43e6-a39a-6a60a904b678.png">

**Comment by tommygonzaleza** [comment]
Problem fixed! commit: https://github.com/learnpack/learnpack-cli/commit/af7da74254f1f19a29357b715cb19c791bd26c81
