### ISSUE TITLE
Excercise Bug: 108-getSmallerElementAtProperty

### ISSUE THREAD

**Issue by aleona-e** [learnpack/learnpack#835]
Describe the bug:

**1. Exercise Name:** 108-getSmallerElementAtProperty

**2. Repository URL:** https://4geeksacademy-masterjava-l1rufycb6po.ws-eu39a.gitpod.io/

![image](https://user-images.githubusercontent.com/99901050/162927177-cb7d0361-b222-45ba-b284-cf394196b42e.png)

-obj and output not defined

**Comment by kiddopro** [comment]
already solved.

https://github.com/4GeeksAcademy/master-javascript-programming-exercises/commit/a3ffab483120d39e507b64b986d6f776751e0922
