### ISSUE TITLE
Excercise Bug: 109-getLargestElementAtProperty

### ISSUE THREAD

**Issue by aleona-e** [learnpack/learnpack#836]
Describe the bug:

**1. Exercise Name:** 109-getLargestElementAtProperty

**2. Repository URL:** undefined
https://4geeksacademy-masterjava-l1rufycb6po.ws-eu39a.gitpod.io/

![image](https://user-images.githubusercontent.com/99901050/162930593-1969b046-a768-4fe9-8d44-d2981f91c8ab.png)

instructions not matching test specs

**Comment by kiddopro** [comment]
already solved.

https://github.com/4GeeksAcademy/master-javascript-programming-exercises/commit/24ec1d6dc0679b3397654b4aebb2ac170f357625
