### ISSUE TITLE
Excercise Bug: 05-create-anchors

### ISSUE THREAD

**Issue by Azim3triko** [learnpack/learnpack#837]
Describe the bug:

The preview image is misleading because I thought i had to center the link in the middle of the screen, but these exercises are about HTML.

**1. Exercise Name:** 05-create-anchors

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/55
