### ISSUE TITLE
Excercise Bug: 05-Anonymous-functions

### ISSUE THREAD

**Issue by christianmartinroffey** [learnpack/learnpack#839]
Describe the bug:

**1. Exercise Name:** 05-Anonymous-functions

**2. Repository URL:** undefined

https://share.getcloudapp.com/mXuYbqqK

test gives error:

undefined 

     ✓ (done) 0. Call the console.log function once
     ✓ (done) 1. The console.log output does not match what we expected
     x (fail) 2. Did you called the function multy with the two parameters? 

console.log (multy(324234,47));
 has two parameters and build shows result

**Comment by tommygonzaleza** [comment]
The issue has been reported already, thanks!
