### ISSUE TITLE
Add the tests to the exercises from `01-terminal` to `05-Data_Frame`

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#841]
Add the tests to the exercises from `01-terminal` to `05-Data_Frame`

Repository: https://github.com/4GeeksAcademy/python-pandas-tutorial

Exercises: From `01-terminal` to `05-Data_Frame`

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/1

**Comment by kiddopro** [comment]
Hrs: <hrs>0.5</hrs>
