### ISSUE TITLE
Add the tests to the exercises from `05.1-from_dict` to `06.3-Group_by`

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#842]
Add the tests to the exercises from `05.1-from_dict` to `06.3-Group_by`

Repository: https://github.com/4GeeksAcademy/python-pandas-tutorial

Exercises: From `05.1-from_dict` to `06.3-Group_by`

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/2

**Comment by kiddopro** [comment]
Hrs: <hrs>0.9</hrs>
