### ISSUE TITLE
Excercise Bug: 12-Rand-From-One-to-Twelve

### ISSUE THREAD

**Issue by Jdvd01** [learnpack/learnpack#854]
Describe the bug:

**1. Exercise Name:** 12-Rand-From-One-to-Twelve

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

el test esta fallando

**Comment by kiddopro** [comment]
The problem was a regular expression in the test that expected to have the values of the random.randrange output in a variable specifically named random_number but the instructions did not ask for it.
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/56

**Comment by kiddopro** [comment]
Hrs: <hrs>0.16</hrs>
