### ISSUE TITLE
Excercise Bug: 108-getSmallestElementAtProperty

### ISSUE THREAD

**Issue by JoelGhub** [learnpack/learnpack#867]
Describe the bug:

**1. Exercise Name:** 108-getSmallestElementAtProperty

**2. Repository URL:** undefined
![image](https://user-images.githubusercontent.com/78375066/164500282-51881f43-ed91-4d33-a58e-65882f70fa8f.png)
![image](https://user-images.githubusercontent.com/78375066/164500335-577cc5f5-0635-499d-a0d2-7eee1b331dad.png)

**Comment by kiddopro** [comment]
There was no issue with the test, perhaps the test were not up to date.

**Comment by kiddopro** [comment]
Hrs: <hrs>0.085</hrs>

**Comment by kiddopro** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/commit/a3ffab483120d39e507b64b986d6f776751e0922
