### ISSUE TITLE
Excercise Bug: 109-getLargestElementAtProperty

### ISSUE THREAD

**Issue by JoelGhub** [learnpack/learnpack#868]
Describe the bug:

**1. Exercise Name:** 109-getLargestElementAtProperty

**2. Repository URL:** undefined

![image](https://user-images.githubusercontent.com/78375066/164500912-04d9c015-7418-4f62-b680-bd9af1104298.png)

**Comment by kiddopro** [comment]
The test has no issue at all and has been updated.

**Comment by kiddopro** [comment]
Hrs: <hrs>0.085</hrs>

**Comment by kiddopro** [comment]
https://github.com/4GeeksAcademy/master-javascript-programming-exercises/commit/24ec1d6dc0679b3397654b4aebb2ac170f357625
