### ISSUE TITLE
The main README of a repository have an error that makes it ugly

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#869]
Repositoy: https://github.com/4GeeksAcademy/python-functions-programming-exercises

This is how the main readme looks like: 
![image](https://user-images.githubusercontent.com/56565994/164557202-37f3a84e-4c4b-4d53-9115-5654920e8fd7.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/56565994/164557253-fb35f31a-efa1-47a7-872e-73e8a16fb845.png)

You should remove the 4Geeks Logo and remove the other image from the table and add it after it as it is shown in the second image that I shared with you

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/29
