### ISSUE TITLE
Excercise Bug: 11-Your_first_if

### ISSUE THREAD

**Issue by Danielum225** [learnpack/learnpack#883]
Describe the bug:

**1. Exercise Name:** 11-Your_first_if

**2. Repository URL:** undefined
La respuesta me da la sensación de que esta mal y por eso al intentar corregir el ejercicio me dice que esta mal el mío.

**Comment by kiddopro** [comment]
The tests are working correctly.

**Comment by kiddopro** [comment]
Hrs: <hrs>0.085</hrs>
