### ISSUE TITLE
Excercise Bug: 03-Call-a-function

### ISSUE THREAD

**Issue by fabeto10** [learnpack/learnpack#884]
Describe the bug:

**1. Exercise Name:** 03-Call-a-function

**2. Repository URL:** undefined

En la lectura en español se refiere a buscar el área de un cuadrado dando dos valores diferentes... un cuadrado siempre tiene lados iguales, este ejercicio hace referencia a lo que es un rectángulo pero dice "cuadrado".

**Comment by Lorenagubaira** [comment]
repository: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial
exercise: 4

**Comment by tommygonzaleza** [comment]
@kiddopro Fix the test as well please

**Comment by tommygonzaleza** [comment]
@Lorenagubaira Actually the test is fine, the problem is on the description of the readme files, on the example they are calculating the squareArea of a rectangle, change it to calculate the squareArea of a square with dimensions 4 x 4

**Comment by Sadiel0** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/60 

HRS : <hrs> 0.10 </hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.1</hrs>
