### ISSUE TITLE
Excercise Bug: 06-forEach_loop

### ISSUE THREAD

**Issue by abaron32** [learnpack/learnpack#899]
Describe the bug:

**1. Exercise Name:** 06-forEach_loop

**2. Repository URL:** https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises

In the instructions of the exercise says that to see if a number x is divisible by 2 you have to do (x % 2 === 0). I think it should be: (x % 2 == 0)

**Comment by kiddopro** [comment]
No problem with the tests, it was just a suggestion.
