### ISSUE TITLE
Excercise Bug: 20.5-Map-arrays-of-objects

### ISSUE THREAD

**Issue by FabiofourGeeksacademy** [learnpack/learnpack#900]
Describe the bug:

**1. Exercise Name:** 20.5-Map-arrays-of-objects

**2. Repository URL:** undefined

in the exercise it says print
Hello my name is Joe and I am 13 years old**.**
but in the text the format varies to
Hello**,** my name is Joe and I am 35 years old

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/69

**Comment by tommygonzaleza** [comment]
Hello! The solution given for this problem is incorrect, if you check the birth date of Joe on the test file it is different, the result shouldn't be 13. Please make sure the results are fine comparing with what the test is expecting

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/70
