### ISSUE TITLE
Excercise Bug: 19-Bottles-Of-Milk

### ISSUE THREAD

**Issue by sbarcelona11** [learnpack/learnpack#908]
Describe the bug:

**1. Exercise Name:** 19-Bottles-Of-Milk

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

The function number_of_bottles must exist but is defined

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/60

**Comment by kiddopro** [comment]
Hrs: <hrs>0.085</hrs>
