### ISSUE TITLE
Excercise Bug: 24-Javascript_Objects

### ISSUE THREAD

**Issue by matiasmunozs** [learnpack/learnpack#909]
Describe the bug:

El valor final deberia dar 74 y no 94

**1. Exercise Name:** 24-Javascript_Objects

**2. Repository URL:** undefined

**Comment by kiddopro** [comment]
There was no problem with the test, it was a problem on the student's solution side. I also added a solution.hide file.
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/67

**Comment by kiddopro** [comment]
Hrs: <hrs>0.16</hrs>
