### ISSUE TITLE
Excercise Bug: 07-Do_while

### ISSUE THREAD

**Issue by CristianLazoQuispe** [learnpack/learnpack#913]
Describe the bug:

**1. Exercise Name:** 07-Do_while

**2. Repository URL:** undefined

the question must be "on the console from 20 to 1" because with that logic everything is correct in the test.

**Comment by kiddopro** [comment]
The "problem" was that the instructions were not very descriptive, at least for this student, and I think he was a little bit right

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/82

**Comment by kiddopro** [comment]
Hrs: <hrs>0.16</hrs>

**Comment by tommygonzaleza** [comment]
You forgot to run `learnpack clean`, there fore it has reset file.

**Comment by tommygonzaleza** [comment]
Anyway, the solution was not ok so I had to close the PR, the solution should be to add the 1 before LIFTOFF as you did but without modifying the rest. And you should change at the beginning of the instructions to ask for the numbers between 20 and 1 instead of 20 and 0

**Comment by kiddopro** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/86

**Comment by kiddopro** [comment]
Hrs: <hrs>0.243</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.243</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.243</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.243</hrs>
