### ISSUE TITLE
Excercise Bug: 10-Find_avg

### ISSUE THREAD

**Issue by camidelgado** [learnpack/learnpack#924]
Describe the bug:

**1. Exercise Name:** 10-Find_avg

**2. Repository URL:** undefined
my_list = [2323,4344,2325,324413,21234,24531,2123,42234,544,456,345,42,5445,23,5656,423]

#Your code here:
aux=0
aux=sum(my_list)/len(my_list)
print(aux)

this is my code, and I got the same expected result.

**Comment by tommygonzaleza** [comment]
Hello @Sadiel0! Please make sure that the tests are working fine, otherwise, fix the test

**Comment by Sadiel0** [comment]
PR : https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/81 

<hrs> 0.10 </hrs>

**Comment by tommygonzaleza** [comment]
You left the solution to the exercise but you didn't change the test or something else. Was the test working fine? Anyway, you don't have to leave the solution in the app.py

**Comment by tommygonzaleza** [comment]
<hrs>0.1</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.1</hrs>
