### ISSUE TITLE
Excercise Bug: 159.4-FashionInventory-D

### ISSUE THREAD

**Issue by CarlosLukass** [learnpack/learnpack#927]
Describe the bug:

Hi, my code pass all the test except the 2nd one, say the function need to return something but my function already return the data and the anothers test are passed, retun correctly data passed so i think are something wrong with the test.

**1. Exercise Name:** 159.4-FashionInventory-D

**2. Repository URL:** undefined

**Comment by Sadiel0** [comment]
Test works fine.
