### ISSUE TITLE
Excercise Bug: 07-post_todo

### ISSUE THREAD

**Issue by LeyCod** [learnpack/learnpack#928]
Describe the bug:

**1. Exercise Name:** 07-post_todo

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial 

=================================== FAILURES ===================================
_________________________________ test_return __________________________________

client = <FlaskClient <Flask 'src.app'>>

    @pytest.mark.it("The endpoint POST /todos should exist")
    def test_return(client):
        response = client.post('/todos')
>       assert response.status_code in [200, 201]
E       assert 400 in [200, 201]
E        +  where 400 = <WrapperTestResponse streamed [400 BAD REQUEST]>.status_code

.learn/exercises/07-post_todo/test.py:101: AssertionError
===================== 1 failed, 10 passed in 0.14 seconds ======================
,
          Your code must to comply with the following tests: 

     x (fail) 0. The endpoint POST /todos should exist 

Teniendo el endpoint hecho no lo reconoce. 
https://breathecode-pythonflask-j7mfc6pj4xk.ws-eu45.gitpod.io/

**Comment by tommygonzaleza** [comment]
Hello! This issue has been reported already, we are working to fix the problem, thank you reporting it
