### ISSUE TITLE
Exercise bug - 00-welcome (Pandas)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#929]
There is a misspelled part on the 00-welcome readme.es.md file:
![image](https://user-images.githubusercontent.com/56565994/168665845-661bc63a-ece9-4ed3-9bf6-dcc37037c7d9.png)

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/python-pandas-tutorial/pull/7

i fixed this but in the same branch "Pandas00-05"
