### ISSUE TITLE
Learnpack does not reset in HTML exercises

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#934]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2674

**Comment by tommygonzaleza** [comment]
Hello @alesanchezr  @ehiber! I couldn't replicate the error, anyway from what you are showing that you have in the console, it doesn't look like it is related with the reset button, it looks like you are running learnpack at the same time in different terminals

**Comment by tommygonzaleza** [comment]
@ehiber can you replicate it again with me? In a meeting or video

**Comment by tommygonzaleza** [comment]
It is actually reseting
