### ISSUE TITLE
Excercise Bug: 12-Rand-From-One-to-Twelve

### ISSUE THREAD

**Issue by Orealba** [learnpack/learnpack#936]
Describe the bug:

**1. Exercise Name:** 12-Rand-From-One-to-Twelve

**2. Repository URL:** undefined
en ningún lugar dice que debo crear una variable llamada random_number, si colocas sólo random.randrange(1,13) debería estar bien igual y no lo acepta
![Captura de pantalla 2022-05-21 a las 22 33 11](https://user-images.githubusercontent.com/92450839/169668130-506c0f02-a2ed-441c-9c29-101e4b070d74.png)
.

**Comment by Sadiel0** [comment]
Test ran perfect without using the random_number variable
