### ISSUE TITLE
Excercise Bug: 12.3-Map_data_types

### ISSUE THREAD

**Issue by RominaGonella** [learnpack/learnpack#937]
Describe the bug:

**1. Exercise Name:** 12.3-Map_data_types

La letra del ejercicio indica que se debe modificar la función map, pero en realidad debe modificarse la función type_list. No sé si está puesto de forma intencional, pero puede generar confusión

**2. Repository URL:** undefined

**Comment by Sadiel0** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/84 

HRS :  <hrs> 0.09 </hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.09</hrs>
