### ISSUE TITLE
Excercise Bug: 12-split-postcard-body

### ISSUE THREAD

**Issue by SantaGosu** [learnpack/learnpack#938]
Describe the bug:
i went to try and complete the page and it says:
    ✓ (done) 0. Make sure you have your index.html
     ✓ (done) 1. Make sure you created the styles.css file
     ✓ (done) 2. Make sure your index.html contains the <link> tag
     ✓ (done) 3. Create a div inside the .postcard-body and add the class .body-left to it
     ✓ (done) 4. Create another div inside the .postcard-body and add the class .body-right to it
     x (fail) 5. The .postcard-body css selector should had a display: flex 
and here is my code in css: * {
	border: 1px dashed red;
	min-height: 10px;
}
body {
	background: black;
}
.postcard {
	width: 400px;
	height: 300px;
	margin: auto;
	background: white;
}
.postcard-header {
	display: flex;
}
.postcard-header img {
	width: 50px;
	height: 50px;
}
.postcard-body {
	display: flex;
}

unless you see somewhere i went wrong it wont let me pass onto the next lesson

**1. Exercise Name:** 12-split-postcard-body

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

**Comment by kiddopro** [comment]
The test has no problems, maybe the student forgot to save the CSS file.

**Comment by kiddopro** [comment]
Hrs: <hrs>0.25</hrs>
