### ISSUE TITLE
Change coding-ide version to 1.0.73

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#941]
- [ ]  Build a postcard using HTML/CSS
- [ ]  HTML5 Forms (10 hrs)
- [ ]  Learn CSS (10 hrs)
- [ ]  Learn CSS Layouts (4 hrs)
- [ ]  Learn Bootstrap (10 hrs)
- [ ]  Introduction to The DOM (4 hrs)
- [ ]  Events inside The DOM (4 hrs)
- [ ]  Looping with Javascript (8 hrs)
- [ ]  Javascript Functions (2 hrs)
- [ ]  Object Oriented Programmming is Javascript
- [x]  Master Javascript with 150 exercises (50 hrs)
- [ ]  Learn React.js (3 hrs)
- [ ]  Unit testing with Jest (2 hrs)
- [ ]  Python for Beginners (20 hrs)
- [ ]  Practice Looping Lists and Tuples (30 hrs)
- [ ]  Practice functions (10 hrs)
- [ ]  Master Python (50 hrs)
- [ ]  Python API Requests (10 hrs)
- [ ]  Build API's with Python Flask

**Comment by Sadiel0** [comment]
1. https://github.com/breatheco-de/exercise-postcard/pull/47
2. https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/23
3. https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/50
4. https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/22
5. https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/31
6. https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/47
7. https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/16
8. https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/pull/71
9. https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/55
10. https://github.com/4GeeksAcademy/object-oriented-javascript-tutorial-exercises/pull/9
11. Master JS (done)
12. Learn React (done)
13. https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/30
14. https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/55
15. https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/83
16. https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/30
17. https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/37
18. https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises/pull/11
19. https://github.com/breatheco-de/python-flask-api-tutorial/pull/42

HRS : <hrs> 1 </hrs>
