### ISSUE TITLE
Excercise Bug: 01.1-hello-jsx

### ISSUE THREAD

**Issue by 6reis** [learnpack/learnpack#948]
Describe the bug:

**1. Exercise Name:** 01.1-hello-jsx

**2. Repository URL:** https://github.com/4GeeksAcademy/react-tutorial-exercises

**3 Se solicita James y pasa el test con jonh

**Comment by tommygonzaleza** [comment]
Hola! Estoy cerrando el issue porque en el test y las instrucciones se solicita que se utilice la variable name, el valor de la variable es "john" por eso el test chequea por "john"
