### ISSUE TITLE
Change the following repos to start using the new LearnPack version

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#949]
On the `.gitpod.Dockefile` there is where we install LearnPack for the workspace. At this moment it is installing the previous version, but we have migrated to a new one, so we have to change it here on the dockerfile in order to download this version.

Where you have `learnpack@0.1.22` change it to `@learnpack/learnpack`.

Repositories:
- [x]  Build a postcard using HTML/CSS
- [ ]  HTML5 Forms (10 hrs)
- [ ]  Learn CSS (10 hrs)
- [ ]  Learn CSS Layouts (4 hrs)
- [ ]  Learn Bootstrap (10 hrs)
- [ ]  Introduction to The DOM (4 hrs)
- [ ]  Events inside The DOM (4 hrs)
- [ ] Javascript for beginners
- [ ]  Object Oriented Programmming is Javascript
- [ ]  Unit testing with Jest (2 hrs)
- [ ]  Practice functions (10 hrs)
- [ ]  Master Python (50 hrs)
- [ ]  Python API Requests (10 hrs)
- [ ]  Build API's with Python Flask

**Comment by Sadiel0** [comment]
1. https://github.com/breatheco-de/exercise-postcard/pull/48
2. https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/24
3. https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/51
4. https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/23
5. https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/32
6. https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/48
7. https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/17
8. https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/68
9. https://github.com/4GeeksAcademy/object-oriented-javascript-tutorial-exercises/pull/10
10. https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/31
11. https://github.com/4GeeksAcademy/python-functions-programming-exercises/pull/31
12. https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/38
13.  https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises/pull/12
14. https://github.com/breatheco-de/python-flask-api-tutorial/pull/43

HRS : <hrs> 0.68 </hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.68</hrs>
