### ISSUE TITLE
Audit command should check for four new properties on the config object

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#950]
The command should check if the config object has:

- [ ] bugs-link (string) - add error
- [ ] duration (integer) - add warning
- [ ] difficulty (string) - add warning
- [ ] video-solutions (string) - add warning

Here is how the audit command is checking other config properties: https://github.com/learnpack/learnpack-cli/blob/main/src/commands/audit.ts#L98

Here is how we're adding an error: https://github.com/learnpack/learnpack-cli/blob/main/src/commands/audit.ts#L99

Adding warnings has the same structure but instead of `errors` you should use `warnings`

Repository: https://github.com/learnpack/learnpack-cli/

File: https://github.com/learnpack/learnpack-cli/blob/main/src/commands/audit.ts

**Comment by kiddopro** [comment]
PR: https://github.com/learnpack/learnpack-cli/pull/38

**Comment by kiddopro** [comment]
Hrs: <hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
- [ ] The error message should be different on each of the validations
- [ ] Include the properties in the IConfig interface instead of IConfigObj
- [ ] Include the properties in the config property

**Comment by kiddopro** [comment]
I need to change the name of the properties. For that reason I put the issue In progress once again.

**Comment by kiddopro** [comment]
https://github.com/learnpack/learnpack-cli/pull/40
camelCase

**Comment by kiddopro** [comment]
Hrs: <hrs>1.085</hrs>
