### ISSUE TITLE
READMEs structure - Postcard Exercise (01-welcome - 08-adding-styles)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#959]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/breatheco-de/exercise-postcard

Exercises: From `01-welcome` to `08-adding-styles`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/exercise-postcard/pull/50
