### ISSUE TITLE
READMEs structure - Learn HTML Exercises (01-welcome - 07-anchor-same-page)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#961]
Modify the READMEs structure according to the file (The link is at the bottom of the issue).

Repository: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

Exercises: From `01-welcome` to `07-anchor-same-page`

Structure File: https://docs.google.com/document/d/1sGV3OzNXCgZnB1RJlhZKJJ6n8HFRGPRt7IWKg0IrQvs/edit?usp=sharing

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/57
