### ISSUE TITLE
Excercise Bug: 07-anchor-same-page

### ISSUE THREAD

**Issue by Goldammer2003** [learnpack/learnpack#969]
Describe the bug:

**1. Exercise Name:** 07-anchor-same-page

**2. Repository URL:** https://github.com/4GeeksAcademy/html-tutorial-exercises-course
Note -> This text is not written by a native english speaker 

When i create the two anchors (one that scrolls the user to the end of the website and another one that sends the user to the beginning of the website) these are not shown when I load the page. I checked also the tutorial if I had some mistake, but everything seems to be right. Surely there is still the possibility that I mixed something up, but since I checked with the solution this might not be the case. Also, I was wondering if it is normal that if you are not finished with all the exercises in one module the program does not really save your progress. Clearly if I am done with all the exercises from one module, I label it as done with my tasks at the 4geeks page, but is there any way to save progress within one module/ bigger practise (as it is called at the 4geeks page)?

**Comment by tommygonzaleza** [comment]
Hello! Can you send me the code to check why it didn't load correctly, please? The problem should be on your code

On the other side, you can save your progress on gitpod or upload it to github and save it on your repository
