### ISSUE TITLE
Fix open in gitpod button

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#973]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8691-33094-3469c391472963bc002bd26fd83fa575) 

---
**Source URL**:
[https://www.learnpack.co/](https://www.learnpack.co/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.67</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Fixed
