### ISSUE TITLE
Create a LearnPack project with  10 exercises

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#976]
Create a LearnPack project by reading the documentation. 

Take 10 exercises from this repository: https://github.com/Rahni1/javascript-challenges

Here is LearnPack's Webpage: https://www.learnpack.co/

**Comment by UmiKami** [comment]
Question: Is the 01-hello-world folder necessary?
Reason:
![Image](https://user-images.githubusercontent.com/60261375/174403845-d6f79ee8-7d64-41a6-8317-92feee96ffe7.png)

**Comment by UmiKami** [comment]
Thought: JEST documentation seems rather sparse. Finding it hard to find answers in google. 
Example: When I tried to look for how to know if a function exists using JEST in google, I only got very few answers and most of them used a totally different method or outdated version of JEST. I now know how check if a function exists but google didn't help.

**Comment by UmiKami** [comment]
Here's the link to the repo:
https://github.com/UmiKami/javasacript-10-challenges-learnpack

**Comment by UmiKami** [comment]
Issue: When testing, it doesn't output the tests passed message on the console if everything is correct.
Steps:
1. Added a new test to the test.js while the learnpack was running
2. app is rewired within test and the test checks if the function is truthy
3. Go back to the app.js and create the require function
4. "All tests passed" message doesn't appear in the terminal anymore

https://user-images.githubusercontent.com/60261375/174456686-0635bc24-e54a-41ff-a163-5ee05d720fb6.mov

**Comment by UmiKami** [comment]
Finding issues validating console.log output, I am able to validate output if and only if I call the functions from the app.js. If the functions are called using expect().toBe(), the test won't pass because it's only reading the console.log originating from the app.js.

Because this and because I do not want to get stuck for a long time. I am going to proceed to just check for what the functions return and specify this on the user instructions.

**Comment by UmiKami** [comment]
The LongestWord challenge on https://github.com/Rahni1/javascript-challenges/blob/master/LongestWord.js has a bug in the solution which I found using the test.js

Sample input: `"Hello my name is Nicola de Fuentevideo"`
Expected Output: "Fuentevideo"
Actual Output: "Nicola"

Original Code:
```JavaScript
function longestWord(sen) {
  let str = sen.split(" ");
  let longest = 0;
  sen = null;
  for (let i = 0; i < str.length-1; i++) {
    if (longest < str[i].length) {
      longest = str[i].length;
      sen = str[i];
    }
  }
  return sen
}
```

My fix:
```JavaScript
function longestWord(sen) {
  let str = sen.split(" ");
  let longest = 0;
  sen = null;
// we do not have to subtract 1, else we won't get to the last word
  for (let i = 0; i < str.length; i++) {
    if (longest < str[i].length) {
      longest = str[i].length;
      sen = str[i];
    }
  }
  return sen
}
```

**Comment by UmiKami** [comment]
The FormatPhoneNumber challenge on https://github.com/Rahni1/javascript-challenges/blob/master/FormatPhoneNumber.js has a bug in the solution found by the test.js

**Sample input:** `(7,8,6,7,4,0,2,3,1,4)`
**Expected Output:** `"(786) 740-2314"`
**Actual Output:** `"(78) 6740-2314"`

**Original Code:**
```JavaScript
function formatPhoneNumber(numbers) {
  const args = Array.prototype.slice.call(arguments);
  args.splice(6, 0, "-");
  args.splice(2, 0, ") ");
  args.splice(0, 0, "(");
  return (args.join(""));
}
```

**My fix:**
```JavaScript
function formatPhoneNumber(numbers) {
  const args = Array.prototype.slice.call(arguments);
  args.splice(6, 0, "-");
  //fix | It was adding the parenthesis after the second character when it should be added after the 3rd character
  args.splice(3, 0, ") ");
  args.splice(0, 0, "(");
  return (args.join(""));
}
```

**Comment by UmiKami** [comment]
learnpack finished, all 10 exercises tested and ready to go

**Comment by UmiKami** [comment]
**A posteriori thoughts:** 

1. The hardest part was definitely doing the tests. As a beginner with JEST I find myself having a hard time with:
            - validating console.log output based on a test parameter. 
            - finding any useful solutions on google
            - JEST documentation lacking details, or having pages that are hard to access directly from the doc main page

2. Due to having a hard time validating console output, I limited myself to validating function outputs. 
3. I want to go back and improve upon it.
            - Start validating console output
            - Check for variables
            - Check for the user not inputing the solution directly into the return or console.log

**Comment by tommygonzaleza** [comment]
Add the rest of the exercises to this repository and then we can prepare a pull requests

**Comment by UmiKami** [comment]
Hrs: <hrs>0.75</hrs>

**Comment by UmiKami** [comment]
When comparing arrays using the toEqual function, console won't out the "All tests passed." message when the output is correct.

**Comment by UmiKami** [comment]
14-Fibonacci needs to be reviewed 
Reason: Unclear instructions

**Comment by UmiKami** [comment]
15-Multiply and Skip needs to be reviewed
Reason: Unclear instructions

**Comment by UmiKami** [comment]
18-NameChange assistance needed to find if a method or variable exists within a function

**Comment by UmiKami** [comment]
All exercises up and working except number 18 which's test is not working for the reasons mentioned above.

**Comment by UmiKami** [comment]
Hrs: <hrs>1.25</hrs>

**Comment by tommygonzaleza** [comment]
Please use the order given for the exercises.
Change the Fibonacci exercise to ask for a function that is given a number "n" (That represents the number of numbers you should return) returns the first "n" numbers of the Fibonacci sequence

**Comment by UmiKami** [comment]
repo name updated: https://github.com/UmiKami/javasacript-20-challenges-learnpack

**Comment by UmiKami** [comment]
Order of exercises changed to original. ✅
Fibonacci exercise restructured. ✅

**Comment by UmiKami** [comment]
Hrs: <hrs>0.35</hrs>

**Comment by tommygonzaleza** [comment]
Use the README.md of the original repository. Modify it to add the open in gitpod button like in the academy's repositories.

**Comment by UmiKami** [comment]
https://github.com/UmiKami/javascript-challenges

**Comment by UmiKami** [comment]
Hrs: <hrs>2.1</hrs>

**Comment by tommygonzaleza** [comment]
review the README.es.md file, it has some translation errors

**Comment by UmiKami** [comment]
Done fixing the README.es.md file.

**Comment by tommygonzaleza** [comment]
Add all the exercises files of the original repository. Then you should add all the LearnPack's Exercises into a folder named `exercises` located in the root of the project (Remember to change the `exercisesPath` in the learn.json)

**Comment by UmiKami** [comment]
reorganization finished
