### ISSUE TITLE
Excercise Bug: 11-Font-Awesome-Icons URGENT

### ISSUE THREAD

**Issue by Zaphrog** [learnpack/learnpack#978]
Describe the bug:
Hola Tomás! Hay ese tema de compatibilidad. Funciona con íconos de fontawesome v4 pero no con v6 (la actual y la que aparece cuando buscas fontawesome. En verdad tienes que buscar específicamente v4 para que salga algo). Tenemos que poner la pista o lograr que sea compatible con v6
**1. Exercise Name:** 11-Font-Awesome-Icons

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by tommygonzaleza** [comment]
Commit: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/commit/ce353cfa37b6431829591db9312f53b671f2d502
