### ISSUE TITLE
Excercise Bug: 05-Anonymous-functions

### ISSUE THREAD

**Issue by Archikins** [learnpack/learnpack#980]
Describe the bug:

test.js is incorrect

it('Did you called the function multy with the two parameters?', () => {
    const regex = /multy\s*\(\s*324234\s*,\s*47\s*\)/gm;
    const fileContent = fs.readFileSync('./exercises/**06-Anonymous-functions/app.js**');
    const match = regex.exec(fileContent);
    expect(match).toEqual(expect.anything());
});

is calling a file on a folder that doesn't exists

**1. Exercise Name:** 05-Anonymous-functions

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

**Comment by Sadiel0** [comment]
PR : https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/64

HRS : 0.25

**Comment by tommygonzaleza** [comment]
You should also add two tests that checks for values with different parameters

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.5</hrs>
