### ISSUE TITLE
Excercise Bug: 09-Array-Methods

### ISSUE THREAD

**Issue by Archikins** [learnpack/learnpack#981]
Describe the bug:

test.js is calling a file from a folder that doesn't exists

**1. Exercise Name:** 09-Array-Methods

**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

**Comment by Sadiel0** [comment]
PR : https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/54/files
HRS : 0.15

**Comment by tommygonzaleza** [comment]
You should also test for the following bullets:
- sortNames exists.
- sortNames should return something.
- sortNames should return an array.

**Comment by Sadiel0** [comment]
PR : https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/68

HRS : <hrs> 0.25 </hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.25</hrs>
