### ISSUE TITLE
Excercise Bug: 099-computeAverageOfNumbers

### ISSUE THREAD

**Issue by marellanorero** [learnpack/learnpack#982]
Describe the bug:

**1. Exercise Name:** 099-computeAverageOfNumbers

**2. Repository URL:** undefined

El ejercicio pide devolver el promedio de los elementos en el array, lo cual mi solución ya hace
En la corrección dice que debe devolver los impares, lo cual no coincide con las instrucciones

**Comment by Sadiel0** [comment]
PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/123

HRS : <hrs>  0.18 </hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.18</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.18</hrs>
