### ISSUE TITLE
Review the Tests javascript Beginners (01-Hello_World - 12-How_much_the_wedding_costs)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#992]
Improve the tests of the following exercises. Remember to take into account the following aspects:

- The function exists.
- The function returns something.
- The function returns the correct output with the possible different values.

Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

Exercises: From `01-Hello_World` to `12-How_much_the_wedding_costs`

**Comment by tommygonzaleza** [comment]
Please replace `var` by `let` or `const` on all exercises

**Comment by tommygonzaleza** [comment]
Add the final hours after this comment

**Comment by dsilva06** [comment]
HRS: <hrs>3</hrs>

**Comment by tommygonzaleza** [comment]
There are a lot of errors because of changing var to let. And run `learnpack clean`

**Comment by dsilva06** [comment]
hrs: <hrs>3.50</hrs>

**Comment by tommygonzaleza** [comment]
The exercises 09, 10 and 12 doesn't have a solution.hide.js

**Comment by tommygonzaleza** [comment]
The test of the 9th exercise should check for the function's functionality.

**Comment by tommygonzaleza** [comment]
Remember you should check your changes before sending them to me, they shouldn't have all these errors. It's normal to have 2 or three but here there are like 20 and it takes too much time to solve it

**Comment by tommygonzaleza** [comment]
<hrs>5</hrs>
