### ISSUE TITLE
Review the Tests javascript Beginners (13-Your_first_switch - 24-Javascript_Objects)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#993]
Improve the tests of the following exercises. Remember to take into account the following aspects:

- The function exists.
- The function returns something.
- The function returns the correct output with the possible different values.

Repository: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

Exercises: From `13-Your_first_switch` to `24-Javascript_Objects`

**Comment by dsilva06** [comment]
pr: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/105
hrs:<hrs>6</hrs>
