### ISSUE TITLE
Review the Tests Python Beginners (01-Console - 10-Calling-Your-First-Function)

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#994]
Improve the tests of the following exercises. Remember to take into account the following aspects:

- The function exists.
- The function returns something.
- The function returns the correct output with the possible different values.

Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises

Exercises: From `01-Console` to `10-Calling-Your-First-Function`

**Comment by UmiKami** [comment]
02-Declare Variables: Added regex to test `'Print the variable on the console'`
The instructions say to print the variable, no the string literal itself, regex checks if print is called with a variable and not a string literal. The test also checks if the value of the output is `"Yellow\n"`

**Comment by UmiKami** [comment]
Hrs: <hrs>0.17<hrs>

**Comment by UmiKami** [comment]
03-Multiply-Two-Values
Same as 02, test passed with hard coded arithmetic operation. Test now checks that the user is not printing the arithmetic operation itself but the variable that holds the operation.

**Comment by UmiKami** [comment]
Cumulative hrs:

Hrs: <hrs>0.27</hrs>

**Comment by UmiKami** [comment]
05-User-Inputed-Values
Name of the variable should not be changed, therefore, added a test to check if such variables exists.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.39</hrs>

**Comment by UmiKami** [comment]
06-String-Concatenation 
User can no longer hard code the answer. User cannot change name of the_new_string variable

**Comment by UmiKami** [comment]
Hrs: <hrs>0.52</hrs>

**Comment by UmiKami** [comment]
07-Create-Basic-HTML
No flaws found. Solution can be hard coded but only after the concatenation has been done. Tests do not pass without the correct concatenation which is to be expected.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.55</hrs>

**Comment by UmiKami** [comment]
Learnpack gets stuck we can cancel input during program runtime. 
[video](https://imgur.com/a/8tE4Q0r)

**Comment by UmiKami** [comment]
08-Your-First-If...
Everything looks good. The total variable name can be modified and tests would pass. Besides that, the instruction cannot be avoid.

**Comment by UmiKami** [comment]
08.1 How Much The Wedding Costs
Up to 50
More than 200 
tests were not being asserted, added assertion statement

**Comment by UmiKami** [comment]
Hrs: <hrs>0.72</hrs>

**Comment by UmiKami** [comment]
09 Random Numbers
The regex was not being asserted properly. Only the last regex line (4) was being asserted. Every regex to be asserted was assigned a number in the end from 1 - 4. Now if the user returns something that is not the default give variable, the test won't pass.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.80</hrs>

**Comment by UmiKami** [comment]
10-Calling Your First Function
The user should no longer be able to hardcode the expected output value on the return statement.

**Comment by UmiKami** [comment]
Hrs: <hrs>1.02</hrs>

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/65
Hrs: <hrs>1.02</hrs>

**Comment by tommygonzaleza** [comment]
Hey @UmiKami ! Can you please modify the test of the 9th exercise, it is not well developed. It should check that the function exists, the value that the functions returns, etc. Not everything should be checked with regex

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/67
Hrs: <hrs>1.19</hrs>

**Comment by tommygonzaleza** [comment]
Exercise 09:
- Change name of test functions.
- Change the condition on the third test.
- Review the forth test.
- The loops of the test should loop less times

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/67
Hrs: <hrs>1.35</hrs>

**Comment by UmiKami** [comment]
Function names fixed.
Third test is now inclusive [1, 10]
Forth test is being asserted outside the loop
Loops iterate the minimum amount of times

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1.35</hrs>
